### ISSUE TITLE
Updating the sound project #2

### ISSUE THREAD

**Issue by CCCPDriver** [GaijinEntertainment/fmod_studio_warthunder_for_modders#10]
Hello! 
You said that you will update the sound project very soon before the end of the month. Already on March 28, can you tell exactly when the update will be released? Thanks.

**Comment by Uchuujin01** [comment]
Hello! No, can't tell when exactly, but it will be soon after the 1st april minor update (02.04.2020 - 06.04.2020). I was wrong about this month, sorry.

**Comment by CCCPDriver** [comment]
> Hello! No, can't tell when exactly, but it will be soon after the 1st april minor update (02.04.2020 - 06.04.2020). I was wrong about this month, sorry.

Ok. Thank you.

**Comment by Uchuujin01** [comment]
Work in progress...

**Comment by CCCPDriver** [comment]
> Work in progress...

Hello. 
I understand that you will update the project today?

**Comment by Uchuujin01** [comment]
No, as I said, I'm working on it. After the update we must fix possible problems and then start working on project for modders. Nex week I'll finish it.

**Comment by 787992** [comment]
> No, as I said, I'm working on it. After the update we must fix possible problems and then start working on project for modders. Nex week I'll finish it.

Take your time, you guys doing stellar job! I just hope you will fix never ending loops for mgs/autocannons and randomly disappearing sounds.

**Comment by Uchuujin01** [comment]
"never ending loops for mgs/autocannons and randomly disappearing sounds." - what do you mean? It happened in game? I did not get any similar official reports so far. Can you make a video of a problem and sent it to me?

**Comment by Uchuujin01** [comment]
And, please, describe sound problems in details.

**Comment by Uchuujin01** [comment]
"you guys doing stellar job" - thank you!

**Comment by ChoukaiKaiNi** [comment]
> Take your time, you guys doing stellar job! I just hope you will fix never ending loops for mgs/autocannons and randomly disappearing sounds.

I think he is referring to the rather confusing way machine gun sounds are implemented in FMOD? It's tricky to figure out but I don't think its a bug.

**Comment by 787992** [comment]
> what do you mean? It happened in game?

Oh, pretty hard to catch this bug, happens in game yea, mostly when ai event shooting, player sounds is always fine, probably the reason why nobody notices that.
Explosion sounds often tend to disappear, artillery is fine, rockets or high-caliber rapid fire - 5-6 explosions and sound goes to silence. Not sure about ai tank cannon sounds pretty hard to notice what bugs out here.
Just my few cents, everything using vanilla pack.

**Comment by Uchuujin01** [comment]
"Explosion sounds often tend to disappear, artillery is fine, rockets or high-caliber rapid fire - 5-6 explosions and sound goes to silence. Not sure about ai tank cannon sounds pretty hard to notice what bugs out here." - yes, it was a problem, but, that's why we reworked all weapon system. After this major update it definitely works better.

**Comment by 787992** [comment]
>  So, this information is obsolete, I think.

Here, i'm sure there's more issues, but these that came to mind first.
(note, in first video i turned off gunfire volume, to hear explosions properly)
https://www.youtube.com/watch?v=fgfesMXur9Y
https://www.youtube.com/watch?v=xMc_7PH_TlY
https://www.youtube.com/watch?v=9FmyOm_XE9I
https://www.youtube.com/watch?v=yARGEVmpsnE

**Comment by Uchuujin01** [comment]
"Here, i'm sure there's more issues, but these that came to mind first." - thank you, I'll check what it can be. We can't reproduce this bug, it is definitely not normal situation.

**Comment by Uchuujin01** [comment]
> > So, this information is obsolete, I think.
> 
> Here, i'm sure there's more issues, but these that came to mind first.
> (note, in first video i turned off gunfire volume, to hear explosions properly)
> https://www.youtube.com/watch?v=fgfesMXur9Y
> https://www.youtube.com/watch?v=xMc_7PH_TlY
> https://www.youtube.com/watch?v=9FmyOm_XE9I
> https://www.youtube.com/watch?v=yARGEVmpsnE
> (not only loop spaa guns bugs out, mgs quite often too)

Thank you for your report, I found a problem. Now everything will be ok with explosions and grenade launcher sounds. If you will find enything else, please, report!

**Comment by Uchuujin01** [comment]
> > So, this information is obsolete, I think.
> 
> Here, i'm sure there's more issues, but these that came to mind first.
> (note, in first video i turned off gunfire volume, to hear explosions properly)
> https://www.youtube.com/watch?v=fgfesMXur9Y
> https://www.youtube.com/watch?v=xMc_7PH_TlY
> https://www.youtube.com/watch?v=9FmyOm_XE9I
> https://www.youtube.com/watch?v=yARGEVmpsnE
> (not only loop spaa guns bugs out, mgs quite often too)

But, I dont understand this "(not only loop spaa guns bugs out, mgs quite often too)" - what do you mean?

**Comment by CCCPDriver** [comment]
Pls FIX) https://forum.warthunder.ru/index.php?/topic/282475-nepravilnoe-pozitsionirovanie-zvuki-dvigatelya-u-tanka-197122/&ct=1586164759

**Comment by Uchuujin01** [comment]
> Pls FIX) https://forum.warthunder.ru/index.php?/topic/282475-nepravilnoe-pozitsionirovanie-zvuki-dvigatelya-u-tanka-197122/&ct=1586164759

Thank you, done )

**Comment by Uchuujin01** [comment]
> When someone shooting nearby and sound never stops, quite hard to catch it in game, happens pretty randomly

We'll see what it can be, thank you for report!

**Comment by 787992** [comment]
Almost forgot about this one:
https://youtu.be/Rlco2YBIwqI
Feels like sound resets after sight view, applies to any tank engine, helicopters too, planes fine.

**Comment by Uchuujin01** [comment]
> Almost forgot about this one:
> https://youtu.be/Rlco2YBIwqI
> Feels like sound resets after sight view, applies to any tank engine, helicopters too, planes fine.

Hello! It was already fixed, I hope soon it will be on production cirquit

**Comment by ChoukaiKaiNi** [comment]
Thank for the update! I wasn't expecting dialogue and music so that's a great bonus :D

**Comment by Uchuujin01** [comment]
> Thank for the update! I wasn't expecting dialogue and music so that's a great bonus :D

I hope everything is ok with update, because there are a lot of changes, about hundred thousand of files, and it was not so easy to update this repo.

**Comment by Uchuujin01** [comment]
If there are any problems with project, please, let me know!

**Comment by 787992** [comment]
> Hello! It was already fixed,
Good to know! Thanks!

> If there are any problems with project, please, let me know!
Cheers!

**Comment by Uchuujin01** [comment]
> When someone shooting nearby and sound never stops, quite hard to catch it in game, happens pretty randomly

Hello! We unable to reproduce this bug for now ( can you please describe this situation in details? What type of battle (ground, naval, air)?

**Comment by Uchuujin01** [comment]
> When someone shooting nearby and sound never stops, quite hard to catch it in game, happens pretty randomly

Is it recent bug, or maybe it was only before the latest major patch?

**Comment by Avarik** [comment]
I think some of the events in dialogs_radio_chat are not working.
I was trying to modify the ones in the "vt" folder but sadly none worked. (vt_chat_1 for example)

I then tried to play them unmodded using the playSound action in the mission editor, and to my surprise nothing was heard there too.

What's even more interesting, is that other languages such as "it" and "en" do work, but "vt" does not work at all.

**Comment by Uchuujin01** [comment]
> I think some of the events in dialogs_radio_chat are not working.
> I was trying to modify the ones in the "vt" folder but sadly none worked. (vt_chat_1 for example)
> 
> I then tried to play them unmodded using the playSound action in the mission editor, and to my surprise nothing was heard there too.
> 
> What's even more interesting, is that other languages such as "it" and "en" do work, but "vt" does not work at all.
> 
> I'm trying to make a sound mod that doesn't use most of the existing sound events or less commonly used ones, all of them need to be played using playSound pretty much, I was hoping "vt" will serve that purpose for the time being.

yes, see patchnote for language details, not all languages added for now in fmod project for modders.

**Comment by Avarik** [comment]
Ah, I assumed I was still able to use those events since they were showing...that's ok then, no worries.
Thank you! : D

**Comment by Uchuujin01** [comment]
> Ah, I assumed I was still able to use those events since they were showing...that's ok then, no worries.
> Thank you! : D

Ah, I understood what are you talking about. Yes, empty language events can be used. But i'm not sure about work conditions of vietnamese localisation. It should work, but probably there are some restrictions.

**Comment by Avarik** [comment]
> Ah, I understood what are you talking about. Yes, empty language events can be used. But i'm not sure about work conditions of vietnamese localisation. It should work, but probably there are some restrictions.

Sadly I wasn't able to get it to work, however the EN sound events work flawlessly...not an ideal situation but it's something.
Is there any way to get those Vietnamese events to work though? Or any for that matter? : O

**Comment by Uchuujin01** [comment]
> > Ah, I understood what are you talking about. Yes, empty language events can be used. But i'm not sure about work conditions of vietnamese localisation. It should work, but probably there are some restrictions.
> 
> Sadly I wasn't able to get it to work, however the EN sound events work flawlessly...not an ideal situation but it's something.
> Is there any way to get those Vietnamese events to work though? Or any for that matter? : O

I'll check it next week, ok? But it may turn out vt isn't available. Please use another language, if it is possible.

**Comment by Avarik** [comment]
> > > Ah, I understood what are you talking about. Yes, empty language events can be used. But i'm not sure about work conditions of vietnamese localisation. It should work, but probably there are some restrictions.
> > 
> > 
> > Sadly I wasn't able to get it to work, however the EN sound events work flawlessly...not an ideal situation but it's something.
> > Is there any way to get those Vietnamese events to work though? Or any for that matter? : O
> 
> I'll check it next week, ok? But it may turn out vt isn't available. Please use another language, if it is possible.

No rush! I'll check out other ones if it doesn't work, thank you very much!

**Comment by CCCPDriver** [comment]
> "Here, i'm sure there's more issues, but these that came to mind first." - thank you, I'll check what it can be. We can't reproduce this bug, it is definitely not normal situation.

Hello. At close range, sometimes the shots of other players from some tank guns are not played. All priorities are at a high value. What might be the problem?
![image](https://user-images.githubusercontent.com/62462287/79071863-9b6aa000-7ce6-11ea-9141-e82b07bcc1c1.png)

**Comment by 787992** [comment]
> Hello! We unable to reproduce this bug for now ( can you please describe this situation in details? What type of battle (ground, naval, air)?

I'll make deeper research with documented videos, happened in ground battles mostly. After few minor patches can't catch it anymore.
Also here's some bugs that still around:
https://youtu.be/dPa_s6Me1rM (don't really know since what patch it's started, but sound is not properly follows tank, not only engine sounds, but anything that related to player tank sound, if it's not 
in stereo)
It probably affects modding side (not sure if it's the bug case)
https://www.youtube.com/watch?v=57Wc2JR_RV4 - this happens when changing to directional, also ignores 3d distance.
https://youtu.be/pR1EDjGRqzQ - same for bullet_passby, if changing to directional, it stays on left no matter what.

**Comment by Uchuujin01** [comment]
> > "Here, i'm sure there's more issues, but these that came to mind first." - thank you, I'll check what it can be. We can't reproduce this bug, it is definitely not normal situation.
> 
> Hello. At close range, sometimes the shots of other players from some tank guns are not played. All priorities are at a high value. What might be the problem?
> ![image](https://user-images.githubusercontent.com/62462287/79071863-9b6aa000-7ce6-11ea-9141-e82b07bcc1c1.png)

Hello! Maybe you have more than 6 tanks with the same event on the battlefield? And the further tank steals event from the closest one. Or, maybe you may have not set the proper value to multi instruments stealing priorities (Oldest). Does this event work properly in Fmod Studio?

**Comment by Uchuujin01** [comment]
> > Hello! We unable to reproduce this bug for now ( can you please describe this situation in details? What type of battle (ground, naval, air)?
> 
> I'll make deeper research with documented videos, happened in ground battles mostly. After few minor patches can't catch it anymore.

We managed out this problem with machineguns of other players. It seems the bug happened not only with mg sound loop, but with whole tank, it realy shoots in loop after the player was kicked off from the match (due to connection problems maybe).
But, there are still happens the problem with helicopter's mg of player. And it is not easy to reproduce.

> Also here's some bugs that still around:
> https://youtu.be/dPa_s6Me1rM (don't really know since what patch it's started, but sound is not properly follows tank, not only engine sounds, but anything that related to player tank sound, if it's not
> in stereo)
> It probably affects modding side (not sure if it's the bug case)
> https://youtu.be/57Wc2JR_RV4 - this happens when changing to directional, also ignores 3d distance.
> https://youtu.be/pR1EDjGRqzQ - same for bullet_passby, if changing to directional, it stays on same position matter what.
> 
> Everything tested on wip build, engine reset fix works just fine!

I'm not sure what happens on this videos, but I'll check it, thanks for the reports!

**Comment by 787992** [comment]
> We managed out this problem with machineguns of other players.

Cheers!

> I'm not sure what happens on this videos, but I'll check it, thanks for the reports!

Oh, sorry for misunderstanding, first video shows that sound physically doesn't really follows tank movement, if you turn camera sideways, you can note that transmission clunks doesn't always stays in the center of the tank, this also affects engine sounds that is not centered when moving.
I guess this called sound emitter?
That's why i made a supposition regarding reload sounds and projectile passby sounds (in vanilla both reload and passby sounds are made in stereo, by making them in mono or directional, sound becomes non-centered)

**Comment by CCCPDriver** [comment]
Well. I fixed this problem. But there is another question. The sound of artillery firing is interrupted during the battle. for example, if I start shooting with a machine gun. What could be the problem?
![image](https://user-images.githubusercontent.com/62462287/79319337-dc45fd00-7f10-11ea-8a74-7b85c5270665.png)

**Comment by Uchuujin01** [comment]
> > We managed out this problem with machineguns of other players.
> 
> Cheers!
> 
> > I'm not sure what happens on this videos, but I'll check it, thanks for the reports!
> 
> Oh, sorry for misunderstanding, first video shows that sound physically doesn't really follows tank movement, if you turn camera sideways, you can note that transmission clunks doesn't always stays in the center of the tank, this also affects engine sounds that is not centered when moving.

Thank you, understood now ) Strange, I never noticed that, I'll check it.

> I guess this called sound emitter?

Yes, exactly.

> That's why i made a supposition regarding reload sounds and projectile passby sounds (in vanilla both reload and passby sounds are made in stereo, by making them in mono or directional, sound becomes non-centered)

Reloadings andbullet passby sounds do not have a spatialiser, so they don't have a sound emitter in game world. Therefore, they can't be mono or directional.

**Comment by CCCPDriver** [comment]
> > Well. I fixed this problem. But there is another question. The sound of artillery firing is interrupted during the battle. for example, if I start shooting with a machine gun. What could be the problem?
> > ![image](https://user-images.githubusercontent.com/62462287/79319337-dc45fd00-7f10-11ea-8a74-7b85c5270665.png)
> 
> Check your polyphony and spawn interval settings of scatterer instruments. I suppose the sound spawning may take all free channels, so they starting to compete with your machine gun sound channels.

So 
![image](https://user-images.githubusercontent.com/62462287/79345831-4b841700-7f3a-11ea-9d57-9f9ea3ce6ba8.png)
And

![image](https://user-images.githubusercontent.com/62462287/79345866-576fd900-7f3a-11ea-868b-d62dd82414b8.png)


Here.What values are best set here? Thanks.

**Comment by 787992** [comment]
> Reloadings andbullet passby sounds do not have a spatialiser, so they don't have a sound emitter in game world. Therefore, they can't be mono or directional.

I see, so this is not sound emitter thingy, but any ideas how to make them directional? I know this is not a bug, but for modding puposes, would be great to hear reload sounds from turret :)

**Comment by Avarik** [comment]
> > > Ah, I understood what are you talking about. Yes, empty language events can be used. But i'm not sure about work conditions of vietnamese localisation. It should work, but probably there are some restrictions.
> > 
> > 
> > Sadly I wasn't able to get it to work, however the EN sound events work flawlessly...not an ideal situation but it's something.
> > Is there any way to get those Vietnamese events to work though? Or any for that matter? : O
> 
> I'll check it next week, ok? But it may turn out vt isn't available. Please use another language, if it is possible.

Hey again,
I was wondering if there was any major discovery in regards to the Vietnamese voice lines, or a workaround for the problem I'm having. : D
