### ISSUE TITLE
Why does it say ""The archive is corrupt"" when I try to decompress it

### ISSUE THREAD

**Issue by yeapy2** [GaijinEntertainment/fmod_studio_warthunder_for_modders#102]
it say ""The archive is corrupt"" when I try to decompress it
![螢幕擷取畫面 (210)](https://user-images.githubusercontent.com/94912406/143038744-06260d1e-e711-4354-9b06-dacd7da43216.png)
![螢幕擷取畫面 (211)](https://user-images.githubusercontent.com/94912406/143038750-76e4fddf-7fb8-400f-a671-51e78cccb3dc.png)

**Comment by sdfaedsf** [comment]
I have same problem with you but I still don't know how to fix it
