### ISSUE TITLE
Deleted events

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#105]
I tried to move my mod into new project.
I deleted simple events without any parameters and copied equals from old project.
I made same names, same paths, same banks connection and  mixer conditions.
Copied assets.
But game doesn't play those events. Why?
Everything works in fmod.
Build it again from very beginning?

----

Я переезжал в новый проект. Удалил пару простых ивентов, в которых нет параметров, и скопировал аналогичные из старого.
Я выставил те же имена, пути, назначил банки и миксер. Скопировал ассеты.
Но в игре звука нет. А чего? В fmod всё работает.
Сначала опять собирать?

**Comment by Uchuujin01** [comment]
Make sure you didn't make a mistakes in names, and added all the banks in sound/mod folder. That's all I can say by now since I have no more data.
