### ISSUE TITLE
No any project in FMOD when I open 'sounds'

### ISSUE THREAD

**Issue by PenguinLogisticsExia** [GaijinEntertainment/fmod_studio_warthunder_for_modders#108]
I downloaded all the files and FMOD in version 2.01.06 (64bits and 32 bits) but it is empty in the project. No crew dialogs, no hangar music and others. IDK what was wrong, and I hope someone who know how to solve these issues could help me.

**Comment by Uchuujin01** [comment]
Hello! What do you mean exactly? No sound events? Or no sound assets? Can you show your Event Editor screenshots and Project Preferences window screenshots?

**Comment by PenguinLogisticsExia** [comment]
![MSY~DG$2T8`@CX66L6TKXC5](https://user-images.githubusercontent.com/95954726/146174896-badb9035-a74f-4257-9f06-202676754f3d.png)
![image](https://user-images.githubusercontent.com/95954726/146175033-ec295b87-6713-43fc-8c1b-4784fe8e4c35.png)
Yeah it shows like the pictures here.

**Comment by PenguinLogisticsExia** [comment]
> Hello! What do you mean exactly? No sound events? Or no sound assets? Can you show your Event Editor screenshots and Project Preferences window screenshots?
