### ISSUE TITLE
Leclerc sound mod

### ISSUE THREAD

**Issue by MathMilitary** [GaijinEntertainment/fmod_studio_warthunder_for_modders#11]
Hello,
I would like to modify the engine sound for the Leclerc tank. Who does he share with? previously it shared fully with the 2A5.

**Comment by Uchuujin01** [comment]
Hello! Yes, 2A5 shares engine sound with several other tanks, includind Leclerc.

**Comment by MathMilitary** [comment]
is there a difference in sound that is played depending on the tank used. I have the impression that the Leclerc does not play the same way as the 2A5

**Comment by Uchuujin01** [comment]
> why the Leclerc does not sound like a turbine?

Hello! This is because it does not have a turbine engine. Maybe you mean diesel turbine charger sound? Anyway, you right, the charger sound is too low, I'll fix it. Thank you for the report!

**Comment by MathMilitary** [comment]
Hi, no! The leclerc have a turbine with V8 diesel, not a charger. please watch the mode I made with the real Leclerc son. I have the audio file that you can use for the turbine. Let me help you.
https://live.warthunder.com/post/896412/en/

**Comment by Uchuujin01** [comment]
> Hi, no! The leclerc have a turbine with V8 diesel, not a charger. please watch the mod I made with the real Leclerc sound. I have the audio file that you can use for the turbine. Let me help you.
> https://live.warthunder.com/post/896412/en/

I'm not well familiar with all the tank engines construction details ) Anyway, I understand what are you talking about. Not it have the diesel turbine sound, but it's volume too low. I'll fix it, and maybe will make a new sound asset for it. Unfortunately, we have too many vehicles in our game, and it is easy to miss out some details.

**Comment by Uchuujin01** [comment]
> Hi, no! The leclerc have a turbine with V8 diesel, not a charger. please watch the mod I made with the real Leclerc sound. I have the audio file that you can use for the turbine. Let me help you.
> https://live.warthunder.com/post/896412/en/

And thank you for your proposal! I'll keep it in mind.

**Comment by MathMilitary** [comment]
I would be happy to build the sound of this tank for you in Fmod with your tracks and show you how I did it. there is no need to add others are just to build

**Comment by MathMilitary** [comment]
I'm a old driver tank leclerc in french 😉

**Comment by Uchuujin01** [comment]
> I would be happy to build the sound of this tank for you in Fmod with your tracks and show you how I did it. there is no need to add others are just to build

Unfortunately we cannot use community related sounds in game. But you've done a really good job so please continue to improve and enhance your work! Thank you very much, please write me in case of questions.

**Comment by Uchuujin01** [comment]
And I appreciate your experience as a tank driver, of course.

**Comment by MathMilitary** [comment]
I understand it's a shame. just try to put a turbine and not a chargeur.

**Comment by Uchuujin01** [comment]
> I understand it's a shame 😭. just try to put a turbine, not a charger.

Yes, I'll read more about diesel engines. Thank you for your advice!

**Comment by MathMilitary** [comment]
thank you very much for taking the time to chat with me

**Comment by MathMilitary** [comment]
![leclerc  ,moteur   ](https://user-images.githubusercontent.com/63722574/79761724-1dc81500-8322-11ea-92b8-4fd859e45753.jpg)

**Comment by MathMilitary** [comment]
![unnamed (1)](https://user-images.githubusercontent.com/63722574/79761743-27517d00-8322-11ea-8186-ce1a87788f83.jpg)

**Comment by Uchuujin01** [comment]
This is a very valuable notion. I just read about Leclerc engine, did not know about this unique Leclerc engine design detail - additional gas turbine engine. Thanks again!

**Comment by MathMilitary** [comment]
Avec plaisir 💪😉

**Comment by MathMilitary** [comment]
are you in charge of the sounds in WT, or will you give the information to the developers?

**Comment by Uchuujin01** [comment]
> are you in charge of the sounds in WT, or will you give the information to the developers?

I work on WT sound, so your valuable information already reached the destination ) Appreciate that!

**Comment by MathMilitary** [comment]
Wow, I very big thanks for French tankist 🥰

**Comment by Uchuujin01** [comment]
Glad to know our work is valuable ) Feel free to leave feedbacks here. And, keep on working on WT sound mods! I think players and developers should learn from each other.

**Comment by MathMilitary** [comment]
With pleasure 🤙😉 
if i can make a contribution to the building of our favorite game and improve the sound reality, i am a happy man. look forward to seeing the changes you will make to Leclerc.
Best regards

**Comment by MathMilitary** [comment]
Hi, if i am not mistaken you changed it in 1.98?
it is a great happiness for me

**Comment by Uchuujin01** [comment]
> Hi, if i am not mistaken you changed it in 1.98?
> it is a great happiness for me

Hello! Yes, I changed Leclerc engine sound, thanks to your advice. It is still not perfect, but became much closer to real one ) Thank you for help, appreciate it )

**Comment by MathMilitary** [comment]
Hi,
why the Leclerc sound is different when you are in the spectator mod?

**Comment by Uchuujin01** [comment]
> Hi,
> why the Leclerc sound is different when you are in the spectator mod?

Hello! Any in-game tank engine sounds different in spectator mode, because for enemy/allied tanks we have a few generic sound events, to save some RAM memory. In future we’ll try to make unique sounds for every vehicle.

**Comment by MathMilitary** [comment]
ok I understand better thanks for the answer. continue your great work on sound.

**Comment by Uchuujin01** [comment]
> ok I understand better thanks for the answer. continue your great work on sound.

Thank you for your help!
