### ISSUE TITLE
Missing new russia tank main gun sound

### ISSUE THREAD

**Issue by Kimbyeoungjang** [GaijinEntertainment/fmod_studio_warthunder_for_modders#110]
As a title, after new fmod project build, my soviet tank gun sound gone

**Comment by Uchuujin01** [comment]
What tank, exactly?

**Comment by Kimbyeoungjang** [comment]
Like T-80BVM, Top tier soviet tanks main gun sound seems missing.

**Comment by Kimbyeoungjang** [comment]
Yes my build contain them but seems caused by soundbank file.
I fix the problem to create mod folder. thank you for your support :D
