### ISSUE TITLE
Any way to return the old auto-fire system?

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#112]
Hello Mr. Uchuujin01 

I have now started with updating my project to the current version (it's still from the Red Skies version so yeah).

I already noticed ingame that many auto-firing cannons are gone for a long time now.

I presume it's from this changelog
"This update got the new automatic weapon sound system, and new automatic weapon sound events, for all in-game vehicles. In a nutshell, it is a kind of loop mode, but with an element of a granular synthesis." Direct Hit

The Issue now is, i can't get any sounds i always used, working with this. 

![Screenshot (341)](https://user-images.githubusercontent.com/67481432/148668309-52cb727d-f4fb-47cf-920e-3d473f46d344.png)

This is what i always used in the past (for the 40mm_l70_bofors_ai).

![Screenshot (342)](https://user-images.githubusercontent.com/67481432/148668331-8d2a12c1-f1eb-4bcb-b9e4-b2710a094d9f.png)
 
 This is what the yellow event contains 

--------------------------------------------------------------------
![Screenshot (341) - Kopie](https://user-images.githubusercontent.com/67481432/148668350-3e09e0ca-6a2d-4cda-a2f3-4d7537b930e0.png)

And now the same track looks like this. 

First, i tried like the old version with the yellow events but this doesn't work (sound is muted). Then i tried to use the multi instrument that is usally inside the yellow event, in the new loop event. **but the sound is played at the wrong rate**. even after apply the same settings to it like the other multi instruments. 

-------------------------------------------------------------------

I use loop on the MG's and some fast firing guns like the 23mm_2a7. but is there any way to kinda return to oneshot on some events? Or make longer tracks (in seconds) work in the new events?   

Thank you.

**Comment by OXEPU3M** [comment]
Did you tried codes from p.3 of https://wiki.warthunder.com/Sound_modifications

Im not Uchuujin01, but Im interesting too =)

**Comment by RadonSound** [comment]
> Did you tried codes from p.3 of https://wiki.warthunder.com/Sound_modifications
> 
> Im not Uchuujin01, but Im interesting too =)

Oh, this looks interesting. I will try it later . (if thats the solution, then all i can say is dumb me for not reading further..) 
Thanks for replying)

**Comment by Uchuujin01** [comment]
Hello everyone ) Thanks for the tip, @OXEPU3M
