### ISSUE TITLE
Any way to return old RPM / Load system for tanks?

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#114]
Hello),

I currently scratching my head with the new engine events for tanks. well with the [ rpm_result ] module to be exact. For some reason i can't get it to work properly. I always run into the issue that load isn't played properly ingame. Either max Load plays barely at max speed, or i get max load at slow speed. plus load kinda switches around too quick on hilly terrain. when i setup the engine event like before (last picture), load never plays

![Screenshot (380)](https://user-images.githubusercontent.com/67481432/149789272-50d1c7c2-4d97-44fa-a331-1ffa1c64cbc4.png)

---------------------------------------------------------------

This is the system i always used before and kinda miss. I found it a bit easier. Load & RPM played evenly at any speed ingame . 
![Screenshot (379)](https://user-images.githubusercontent.com/67481432/149789809-4e097f43-a4cf-4aa3-9214-7d10ceff5632.png)

Thanks and sorry if its a bit confusing(..

**Comment by Uchuujin01** [comment]
Hello! This is relatively new system, I added it because I wanted an ability to add non-linear dependence of engine sound to actual rpm. So, this means, if you want a linear dependence, just change rpm_result curve to straight line from 0 to 100.
