### ISSUE TITLE
requiest list

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#117]
Hello,
is it possible to get a list of sounds from FMOD (tank) with the matches. 
example :
Chieftain = challenger, roland etc...

Thanks in advance
Good work for M1 abrams sound ;-)

**Comment by Uchuujin01** [comment]
Hello! I think it will take too much time do that kind of list for every in-game model. I can't promise this for now, but I'll try.

**Comment by Uchuujin01** [comment]
> Good work for M1 abrams sound ;-)

Thank you )

**Comment by MathMilitary** [comment]
I can prepare a list (google doc) with the vehicles I need, it will take less time to do.?

**Comment by MathMilitary** [comment]
Hi, is possible liste pls for 

Tank01
Panzer1,2,3,4,6 and tiger diesel.
Thanks in advance
