### ISSUE TITLE
How to make china country mod in "dialogs_radio_chat"

### ISSUE THREAD

**Issue by WisteFinch** [GaijinEntertainment/fmod_studio_warthunder_for_modders#118]
My English is not good. The following contents are translated by translation software, thank you for your patient.
I have successfully made ``dialogs_chat_en.bank`` ``dialogs_chat_ru.bank`` ``dialogs_chat_fr.bank`` etc. However, I can't make this for china country because the game can't recognize it. I think this is because the file name is wrong， but l tried to name it  ``dialogs_chat_zh.bank`` ``dialogs_chat_ch.bank`` ``dialogs_chat_chn.bank`` ``dialogs_chat_cn.bank`` and they all don't work. I hope you can help. Thank you.

**Comment by OXEPU3M** [comment]
Watch original files
![ср](https://user-images.githubusercontent.com/74115508/155595682-45bb66cf-3a82-4274-9c14-d52e1d2c946b.PNG)
I suppose "_hchn" is all you need.

**Comment by WisteFinch** [comment]
It works, thank you.
