### ISSUE TITLE
Сломался звук.

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#120]
Ещё в прошлом мажоре перестали включаться ивенты Slide*, играющие киноплёнку на загрузке миссии.
Через раз включался "пип" загрузки уровня и подключения к игре.
Так же при загрузке того же уровня почему-то на 2-5 секунд играла main theme Великобритании.

Плюс ещё много всякой мелочи, которую я не знаю.
Очень странно, что пропадает то, что работало годами.
К тому же на этих ивентах удобно строить моды с логикой, а теперь даже не знаю, куда обращаться.

**Comment by Uchuujin01** [comment]
Нет ничего странного в том, что элементы, которые не контролируются непрерывно, перестают иногда работать в постоянно меняющемся, живом проекте. Но хорошо что вы доложили о проблеме, я проверю указанные элементы. Правда, "много всякой мелочи" - вот с этим не понятно.
