### ISSUE TITLE
More Tank Crew Events

### ISSUE THREAD

**Issue by YamashiroKai** [GaijinEntertainment/fmod_studio_warthunder_for_modders#121]
Hello,

I would like to request that we get more crew sound events for ground vehicles to better reflect how a crew communicates with one another during battle. I know getting voice actors to speak more lines can be troublesome, but just adding additional events for modders would go a long way.

Ideas include:
-Event for aiming at an enemy vehicle (Gunner yelling "Identify" and Commander yelling "Fire")
-Event for missing a target near the crosshair (Commander yelling "Miss" "Short" "Long", etc)
-Event for losing sight of a target that was identified (Commander yelling "Lost")
-Event for aiming at specific vehicles (Commander telling the loader to load a specific ammunition for target) This one is a bit of a stretch but I'm listing it anyways.
-Event for killing all vehicles visible on the screen (Commander yelling "cease fire")
-Event for telling the gunner to aim at a target on the screen but not on the crosshair (Commander yelling "Traverse left/right" etc)

This idea was inspired by another game that accurately reflects crew commands, here's a video preview: https://youtu.be/8v1_b_ICXK8

**Comment by Uchuujin01** [comment]
Hello! We're about to improve VO for ground crew, I'll keep in mind your suggestions, thank you.
