### ISSUE TITLE
Engine sounds

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#13]
You guys doing good stuff on improving engines for tanks, but what do you think about expanding engine sounds for nearby tanks(or ai tanks)? 
I don't know if it was suggested earlier, but that would nice qol feature, as right now you can't distinguish exact model of heavy tank or medium etc.

**Comment by Uchuujin01** [comment]
> You guys doing good stuff on improving engines for tanks, but what do you think about expanding engine sounds for nearby tanks(or ai tanks)?
> I don't know if it was suggested earlier, but that would nice qol feature, as right now you can't distinguish exact model of heavy tank or medium etc.

Hello! Yes, we think about this feature in future. For some technical reason, we can't add this feature easily.

**Comment by 787992** [comment]
> Hello! Yes, we think about this feature in future. For some technical reason, we can't add this feature easily.

Heck yes! Thanks for answer! I'll be waiting like a little kid ;)
