### ISSUE TITLE
exterior sounds more muted

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#131]
Hi,
why not make all exterior sounds more muted when you pass inside a vehicle? now, when you go indoors, the outside sounds remain the same. also, turret rotation logic indoors should be turned off outdoors.

**Comment by Uchuujin01** [comment]
Hello! Sounds fair enougs, but, some time ago I started to get multiply complains about it, righ after I implemented this mute you talking about. Like, you almost always shooting prom the gunner's view, so, why should you not to hear an environment? So, we decided not to mute environment sounds significantly.
