### ISSUE TITLE
Can this work? 

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#132]
Hello Hello!

While Copy>Paste my older project into the new version, i had an idea to make the work on tank cannons a bit easier. 
Can this work if i add some extra folders into cannons to separate the large amounts of tracks to make it more clearer. 
![Screenshot (216)](https://user-images.githubusercontent.com/67481432/177167248-8246141f-8d58-4a88-8df3-809182ee7167.png)

I always had a hard time to apply settings to a certain type of tracks (for instance all _interior) because of the large and mixed list. What if i put all interior tracks for cannons, into a extra folder and the rest to their extra folders? Can this cause any troubles? Of course with the default mixer settings and assigned banks / groups.

**Comment by Uchuujin01** [comment]
Hello! Unfortunately, this will not work. I think about refactoring like this you thught about, but, it is not easy. I need to rewrite all references to sound events in game configs. This work, of course, can be automated, but, it need to be checked manually anyway. So, I'm afraid, no, not so soon at least.

**Comment by OXEPU3M** [comment]
>  large and mixed list

Use search bar with operators OR AND NOT
Also color markers help a lot.

**Comment by RadonSound** [comment]
> > large and mixed list
> 
> Use search bar with operators OR AND NOT Also color markers help a lot.

![Screenshot (225)](https://user-images.githubusercontent.com/67481432/177720165-f7cd9529-c359-442c-b176-095011a38bd3.png)
Ohhhhhhhh...... That's actually gold 
Thank you!

**Comment by Uchuujin01** [comment]
> > large and mixed list
> 
> Use search bar with operators OR AND NOT Also color markers help a lot.

Great proposal actually, I didn't think to suggest it )
