### ISSUE TITLE
briefing music doesn't play (and some other questions) 

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#136]
Hello, 

I've finally finished my soundproject. But for some reason the music that used to play while loading into a match doesn't play anymore. The other thing is, not sure if that only happens in toptier but sometimes the ingame music (tanks_action_01, tanks_suspense_01 and/or toptier> tank_action   suddenly stops playing entirely.  

Also, i can't find the correct event that plays while flying at higher speeds in aircrafts (the strong wind and metal rattling). 

Lastly, is there a way to give loop events for ground vehicles (like mg or spaa) a hold time like for aircrafts? Issue is, when i do "onetaps" or in other words quickly shoot with a looped ground weapon, the actuall firing sound gets interupted before making any noise, directly follows by the lastshot sound. 
For aircrafts, it works fine when i click pretty fast, you can hear couple of rounds going off before the lastshot sound comes. Is there a way to do the same with tanks?

- This is the loop mechanism i use for ground vehicles 
![Screenshot (250)](https://user-images.githubusercontent.com/67481432/182114120-c768b111-3fe0-483b-baef-94872a1e1edf.png)

- This is the loop mechanism i use for aircrafts ( which has some kind of hold time, that i would like to have for ground vehicles ) 
![Screenshot (251)](https://user-images.githubusercontent.com/67481432/182114335-fd6d3dc7-7b9f-4e8e-9260-c5cde0db2049.png)

I tried to setup the ground loop events similar to aircrafts but it doesn't work unfortunately. 

BTW, i think i found the solution for the issue #116  . I followed the same principle with the cockpit snapshots for weapons, all i did was changing the volume for group turrets in mixer with the field / tank snapshot. 

Thank you for any help)

**Comment by Uchuujin01** [comment]
Hello! I read about music events tanks_action_01 and tanks_suspense_01 constantly switches between each other, but, for now, I'm unable to reproduce this problem, and, I didn't saw them suddenly stop. Maybe, you can describe the situations where it happens? Just in case, check your events, is everything alright with fmod instrument, where soud asset is placed?

Wind and hull noise sounds you are looking for is in aircraft/common/events vibration_camera and aircraft/common/vibration_cockpit_open

Hm, the looping mechainsm for ground automatic weapon is similar to aircraft weapon, there is no difference in terms of sound code implementation.

**Comment by RadonSound** [comment]
> Hello! I read about music events tanks_action_01 and tanks_suspense_01 constantly switches between each other, but, for now, I'm unable to reproduce this problem, and, I didn't saw them suddenly stop. Maybe, you can describe the situations where it happens? Just in case, check your events, is everything alright with fmod instrument, where soud asset is placed?

![Screenshot (254)](https://user-images.githubusercontent.com/67481432/182912538-b3d78c55-88c5-46f7-8460-f79e964a4f3f.png)
This is the way i setup the music event (it is located in the music group in mixer, like all the others) .Issue is that it just stops playing in my case in the middle of the track, then the entire music stays muted until the match ends. And the briefing music (loading screen when joining a battle) doesn't play at all anymore. I don't know which event it was for loading but it wasn't tanks_action_01 and tanks_suspense_01 , so in my case it used to play the old aircraft themes which i kinda miss now. 
Do i need to use something different rather a multi instrument?

-----------------------------------

>Wind and hull noise sounds you are looking for is in aircraft/common/events vibration_camera and aircraft/common/vibration_cockpit_open


https://user-images.githubusercontent.com/67481432/182917605-97b5a565-bd91-427d-9e6e-06ebab80a6c4.mp4

I tested with muting all vibration events but the sound which starts at 1000Kmh still plays very loud 

-----------------------------------

>Hm, the looping mechainsm for ground automatic weapon is similar to aircraft weapon, there is no difference in terms of sound code implementation.

I will play around with this later. Not sure why i didn't work last time but i will try again)

Thank you

**Comment by Uchuujin01** [comment]
"I tested with muting all vibration events but the sound which starts at 1000Kmh still plays very loud" - this is aircraft/engines/engine_dive sound event. It sounds not only at 1000Km/h, but when your aircraft dives down at steep angle.

**Comment by Uchuujin01** [comment]
"This is the way i setup the music event (it is located in the music group in mixer, like all the others) .Issue is that it just stops playing in my case in the middle of the track, then the entire music stays muted until the match ends. And the briefing music (loading screen when joining a battle) doesn't play at all anymore. I don't know which event it was for loading but it wasn't tanks_action_01 and tanks_suspense_01 , so in my case it used to play the old aircraft themes which i kinda miss now.
Do i need to use something different rather a multi instrument?" - I'll check this question tomorrow.

**Comment by RadonSound** [comment]
" this is aircraft/engines/engine_dive sound event."
-How did i not found that) but anyway, thank you) for some reason i was searching for ever for it.. always tought it was under effects/common

**Comment by Uchuujin01** [comment]
I'm still unable to reproduce music issues in game ( What file type of music do you use? If those are not wav - try to encode into wav and try again. Multi instrument should work fine.

**Comment by RadonSound** [comment]
I encoded them into WAV , briefing music still does not play
