### ISSUE TITLE
volume reduction with artillery

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#139]
Hi,

is it possible that too loud a volume on the artillery causes the tank engine volume to drop when there is ground impact?

Thx in advance

IWSM sound mod
math

**Comment by Uchuujin01** [comment]
Hello! Yes, there is an explosion snapshot in every explosion sound event. It should drop down most of nearby sounds.

**Comment by MathMilitary** [comment]
hello, ok thanks. will the next major update break our mods @Uchuujin01
