### ISSUE TITLE
Not all sound events in the project can be modified and/or work (E.G: Vietnamese language events)

### ISSUE THREAD

**Issue by Avarik** [GaijinEntertainment/fmod_studio_warthunder_for_modders#14]
Hello!

A while ago, I mentioned that I was trying to modify some sound events, specifically the Vietnamese language events, but was saddened to find out that they in particular do not work and can also not be modified.

I'm making a sound mod for a single player mission with narrative and voice lines and would like to use less commonly used sound events for that purpose.

Is there any way to bring these sound events online?

**Comment by Uchuujin01** [comment]
Hello! I'm sorry for the late response, was too busy this week (

Yes, I'll try to check it during the work on sound for the new major patch. But I can't promise for sure, because of major patch work high priority.

**Comment by Avarik** [comment]
> Hello! I'm sorry for the late response, was too busy this week (
> 
> Yes, I'll try to check it during the work on sound for the new major patch. But I can't promise for sure, because of major patch work high priority.

No sweat! I can fully understand you. uwu

**Comment by Avarik** [comment]
Hey again,

> Hello! I'm sorry for the late response, was too busy this week (
> 
> Yes, I'll try to check it during the work on sound for the new major patch. But I can't promise for sure, because of major patch work high priority.

I was hoping that now that the major patch is live, that you might have the time to look at it now, you had a lot of work to do and I hope you have some breathing room and hopefully some time to relax. c:

**Comment by Avarik** [comment]
Hey, sorry to bother you again but I'm wondering if the next upcoming update to the sound banks will have anything to remedy this, or if there is a workaround to the problem. :O
