### ISSUE TITLE
MAJ drone age and sound mod

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#141]
Hi,

I realized that the sounds of the SU-25 and drones in particular were missing, is there a solution to simply add these 2 inputs in Fmod without waiting for your project update which I hope will be quick.

**Comment by Uchuujin01** [comment]
Hello! Here's the names:

**Comment by MathMilitary** [comment]
hi, very big thanks. I work now

**Comment by IWSM** [comment]
@Uchuujin01 hi,

just right click and new mixer? with add on aircraft engine bank.
this is the first time i have to create a new entry.
Thanks in advance

**Comment by IWSM** [comment]
https://zupimages.net/up/22/36/tlhw.png

**Comment by Uchuujin01** [comment]
It seems you do it right, are there any problems?

**Comment by IWSM** [comment]
Yes, on test with su-25 premium, not sound

**Comment by Uchuujin01** [comment]
Use your masterbank file, your project is incompatible with my master bank. And, don't forget about masterbank.strings. I'm not sure about your fourth point, what do you mean by "click on new mixer"?

**Comment by IWSM** [comment]
after add in the banks like the previous image, I'm not sure what to do here. (https://www.casimages.com/i/Erreur 1.html)

**Comment by Uchuujin01** [comment]
It seems you did everything right. So, you built the aircraft_engines bank, and put it along with masterbank, masterbank.strings, and aircraft.assets banks to sound/mod/ folder?

**Comment by IWSM** [comment]
Yes that's it. now I have engine sounds but it does not react to acceleration, it stays low. I do not know why :(

**Comment by IWSM** [comment]
@Uchuujin01 Hi, I think I found the problem, initially I duplicated engine05_RM8 it didn't work. I redid with engine05_J79 and it works now. I don't know for what reason

**Comment by Uchuujin01** [comment]
Glad you made it )

"drones uav and mk1 use start and stop event? just use RPM?" - yes they use start and stop, you can switch them off and on.

**Comment by IWSM** [comment]
great, thank you again for your help, it will save me from redoing everything and waiting for your project update

**Comment by IWSM** [comment]
@Uchuujin01 you are change a mirage 2000 sound? new engine?

**Comment by IWSM** [comment]
Thanks
