### ISSUE TITLE
Attack_gau8a (impact)

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#146]
Hi @Uchuujin01 ,
I noticed that attack_gau8a does not play all the time on land and differently depending on surfaces such as buildings. I also noticed that it plays pretty close but it bugs with increasing distance.
Do you have a reason?

Thanks in advance
_IWSM sound mod_

**Comment by Uchuujin01** [comment]
Hello! I haven't noticed such behaviour of attack_gau8a. I will check it, thank you.
