### ISSUE TITLE
tracklink for CV90105?

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#147]
Hello @Uchuujin01 

I have a problem. The tracks used on CV90105 have disappeared and I can't find why or which event is used. Can you help me understand. It's a bug? I test on other STRF and CV without traklink problem, only on CV90105 XC-8 premium model

**Comment by Uchuujin01** [comment]
Hello! CV90105 got its own tracks sound events: tracks_rubber, tracks_rubber_interior, suspension_rubber, surface_rubber

**Comment by Uchuujin01** [comment]
Because this tank has rubber tracks )

**Comment by IWSM** [comment]
ah ok, so I have to add it, exemple tracks_CV90 and tracks_CV90_AI?
