### ISSUE TITLE
Idea to improve the sound

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#153]
Hi @Uchuujin01 ,

Hello my friend, I have 2 suggestions for you to improve the soundscape for tanks.

**1 :** Add inside the turrets, the sound of casings falling. Which also depends on the calibers. I did this on my IWSM mod. It has significantly improved internal sound immersion and is very easy to set up.

**2 :** It is very easy to add an effect of confinement and reverberation inside the turrets. This of course depends on the type of vehicle with an open turret or not. This makes the sound more realistic indoors and it's also very easy to set up. I also realized it on my IWSM mod.

How can I do to reduce the volume of tracks depending on the surface. For example, I would like the sound of the tracks to be reduced when you are in the mud or on the snow.
I have been working on my project for quite some time now. I would love to be able to help you and help improve the game. It's something I love to do.

BUG : I have noticed with several people that the fire extinguisher in the tanks sometimes goes off for no reason without the vehicle being on fire.

Best regard

**Comment by IWSM** [comment]
hi @Uchuujin01 
i'm trying to do something but i'm not sure if it works like this
![Capture d’écran 2022-11-18 084747](https://user-images.githubusercontent.com/63722574/202649269-40f8f50c-a495-4242-841f-8c8ab309f099.png)
![Capture d’écran 2022-11-18 084841](https://user-images.githubusercontent.com/63722574/202649277-4d597ec8-329e-45ac-ba64-564b174f465c.png)

**Comment by Uchuujin01** [comment]
Hello! Yes, it seems you've done it right on the picture.

I understand what you are talking abount (2S6), but, in terma of gameplay those casing fall sounds is not ok if they would be fall ing for too long, for some people they might be annoying. And, dont forget about we have physic detections of case falling on hull and on the ground as well - shell_fall_ events.

**Comment by IWSM** [comment]
Hi @Uchuujin01,
hello Ok, however when I use it it seems that it affects all surfaces and not just "MUD", this way I don't have any volume at all of the caterpillar. I don't understand.

I will continue my tests.

For sockets, I did not know that there are physical detection, I understand better.

**Comment by IWSM** [comment]
unfortunately it works badly when there is a change of surface, the sound stops suddenly and starts again.  like a micro cut at each change of surface. 🤔😰
