### ISSUE TITLE
Change for next update

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#156]
Hi @Uchuujin01 

Are there any major changes or additions in the next update?  I am thinking of jets for example.  Mig-29, F-16, Tornado and has the gun too.
Thanks in advance
Best regards 
Math
Edit: F110=F16, RB199=Tornado, RD-33=Mig-29. _Please, share with me a name event_

**Comment by Uchuujin01** [comment]
engine05_f110_, engine05_rb199_, engine05_rd33_, with corresponding endings, usual collection of events for every engine.

**Comment by IWSM** [comment]
Big thanks my friend. Good job
