### ISSUE TITLE
For Russian and non-English crew chats.

### ISSUE THREAD

**Issue by yukkurisebunn** [GaijinEntertainment/fmod_studio_warthunder_for_modders#16]
When will the non-Russian and non-English crew chats be added?

**Comment by Uchuujin01** [comment]
Hello! I think we add other crew chats in next major update (not the closest one, 1.98).

**Comment by yukkurisebunn** [comment]
Is it that it is not 1.98 that it is added in 2.00?

**Comment by Uchuujin01** [comment]
> Is that an addition at 1.99?

I'm sorry, I wanted to say "not 1.99". It's too close to do that much work in time.

**Comment by yukkurisebunn** [comment]
Does this mean that 1.99 won't add to it?

**Comment by Uchuujin01** [comment]
> Does this mean that 1.99 won't add to it?

Non-English and non-Russian language crew chats will not be added in update 1.99.

**Comment by yukkurisebunn** [comment]
Is it that major updates to be added are yet to be determined?

**Comment by ChoukaiKaiNi** [comment]
Could I make a request for naval sounds? The sound events for depth charges and K-guns should be separated.

Depth charges are rolled off the back of the ship while K-gun depth bombs are fired off the side of the ship with a mortar. 

Also the possibility of a sound event for torpedoes and depth bombs hitting the water?
