### ISSUE TITLE
New project Fmod for update?

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#160]
Hi  @Uchuujin01 

the new update to break a lot of thing. Can you give us the most recent version of the fmod project so that we can redo everything. When is it possible as soon as possible

Thanks in advance
Best regard

**Comment by Uchuujin01** [comment]
Hello! I'm about to release the new fmod project update this week, in a couple of days.

**Comment by IWSM** [comment]
Hi, ok excellent. Thanks you
