### ISSUE TITLE
communicate

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#162]
Hi @Uchuujin01 
Is there another place or way I can communicate with you.

Best regards

**Comment by Uchuujin01** [comment]
I'm afraid I can only support you here. I'm not allowed to have private chats corresponded to work.

**Comment by IWSM** [comment]
I understand, it's a shame, because it's sometimes difficult to have a good discussion about the sound design of war thunder.  I wish I could participate more.  but I understand.
