### ISSUE TITLE
Real RWR add.

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#163]
Hi @Uchuujin01 
is it possible to have unique events for the RWR jet.  for example, the separate altitude alert.  this is lacking for jet aircraft and many people would like to have a real RWR without the events being triggered in other circumstances or by ground radar.  is it possible for you to do this only for JETS alerts?

**Comment by Uchuujin01** [comment]
As far as I know, RWR system works on any irradiation source, including ground sources. But, yes, we have in plans improving of jets sound alert system.

**Comment by IWSM** [comment]
Oh cool this. do you have any plans to add voice alerts like i just added on my mod.  Over-G, Altitude, bingo fuel?
