### ISSUE TITLE
Where goes the dialog_wt_ships assets and its events?

### ISSUE THREAD

**Issue by IShiraiKurokoI** [GaijinEntertainment/fmod_studio_warthunder_for_modders#164]
I have notice that a navl sound change was made after Apex Predators, when I turn here for  a sound project update, I counld't found the dialog_wt_ships nor the sound event of ships in fmod studio.Could I know when will these events be added to the project template?

**Comment by Uchuujin01** [comment]
Hello! Those dialogs are obsolete, we work on new naval dialog system, now it is on production circuit. I'll add new naval dialogs events and assets next major Fmod update.

**Comment by IShiraiKurokoI** [comment]
> Hello! Those dialogs are obsolete, we work on new naval dialog system, now it is on production circuit. I'll add new naval dialogs events and assets next major Fmod update.

Ok, thank you for your work. Those new dialogs are really great! Hope to see the update soon.
