### ISSUE TITLE
Alarm_radar

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#165]
Hello, is it possible to make the alarm_radar only work if they are enemies.  in this way, the triggering will not be done on the air base permanently, it will be less repetitive and less annoying.

Thanks in advance

**Comment by Uchuujin01** [comment]
Hello! Unfortunately, it is not possible, as far as I know this system works on any irradiation source. I already tried to clearify this topic with our designers. But, it is highly possible we'll add a button to cancel the notification from current source.

**Comment by IWSM** [comment]
Isn't it just possible to delete friend alerts?

**Comment by Uchuujin01** [comment]
I'll try to figure out how this system should work in reality, should it respond on friendly radar or not.
