### ISSUE TITLE
Naval sound events

### ISSUE THREAD

**Issue by YamashiroKai** [GaijinEntertainment/fmod_studio_warthunder_for_modders#17]
Could I make a request for naval sounds? The sound events for depth charges and K-guns should be separated.

Depth charges are rolled off the back of the ship while K-gun depth bombs are fired off the side of the ship with a mortar.

Also the possibility of a sound event for torpedoes and depth bombs hitting the water?

**Comment by Uchuujin01** [comment]
Hello! Thank you for this request, I think it makes a sence, we'll fix it, after some research.

**Comment by ChoukaiKaiNi** [comment]
Hello, the sound effect that plays when a torpedo splashes in the water is that of a water explosion rather than the splash effect from the previous patch.

**Comment by ChoukaiKaiNi** [comment]
Additionally, shell explosions from warships on the water will play the ammunition explosion sound from the ground event, rather than the water artillery explosion events.

**Comment by ChoukaiKaiNi** [comment]
Hello, the sound effect that plays when a torpedo splashes in the water is that of a water explosion rather than the splash effect from the previous patch.
