### ISSUE TITLE
Event for impact GAU8a

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#170]
Hi @Uchuujin01 

What needs to be changed on the sound event of attack gau8.  When I change it, now there is no changed effect.  Did you change anything on this event which is used for both A-10 and 2S6?

**Comment by FenixAlfa159** [comment]
Last time I checked, it was a sound event called rapid_fire or somewhat like that. Can't remember if it was on ground or aircraft part tho
