### ISSUE TITLE
VT1-2 wrong sound 

### ISSUE THREAD

**Issue by MOOOOs** [GaijinEntertainment/fmod_studio_warthunder_for_modders#171]
Hey. After some updates i noticed that VT1-2 now has wrong sound from engine_stug40 instead of engine_leo2a5 that KPZ/MBT 70 or Leopard-2s uses. I remember some time ago it had same sound of engine as kpz please fix this. Thanks

**Comment by MOOOOs** [comment]
Anyone?

**Comment by Uchuujin01** [comment]
Hello! Thank you, I need to check this definitely.

**Comment by MOOOOs** [comment]
So it will be fixed?

**Comment by Uchuujin01** [comment]
Yes, after I check how it should sound IRL.

**Comment by MOOOOs** [comment]
Any news?

**Comment by IWSM** [comment]
Patient

**Comment by MOOOOs** [comment]
for some reason even after update today its still same sound

**Comment by Uchuujin01** [comment]
Give it some time ) I did changes today, they just didn't get into patch, will work after the new patch surely.

**Comment by MOOOOs** [comment]
But it was writen in changelog that it was fixed

**Comment by MOOOOs** [comment]
Thanks its now has correct sound
