### ISSUE TITLE
Autoloaders sound events

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#173]
Был слегка шокирован, что машины с автоматами заряжания (танки) за редким исключением используют ивент canon_auto.
В большинстве просто canon или canon_heavy.
С чем связано, и будет ли такое исправлено?

Спасибо.

**Comment by OXEPU3M** [comment]
@Uchuujin01 
AMX-13 и все танки с башней FL-10 и FL-12 (которая ящик с барабанами)
AMX-50, все модели, включая M4, Lorraine 40t и Bat.Chat. 25t
XM-8
Об.906, Об 685.
CV90105, CV90120.
Те, что бегло осмотрел.

Все эти машины обозначены с автоматическим заряжанием в рентгене. И при утрате ответственных членов экипажа или пожаре перезарядка не сбрасывается.
Но используют они разные звуковые ивенты, но только не reload_cannon_auto.

Так же при севшем аккумуляторе, так же играются автоматические ивенты. (Включая перезарядку Т-64 и т.д.)

Хотелось бы прояснить, зачем нужен reload_cannon_manual?

**Comment by Uchuujin01** [comment]
"Так же при севшем аккумуляторе, так же играются автоматические ивенты. (Включая перезарядку Т-64 и т.д.)" - хорошее замечание, на данный момент у нас нет соответствующего механизма озвучения ивентов при пропаже питания. Я себе помечу, доработаем.

Принял, спасибо огромное за помощь! Обязательно поправлю у указанных танков ивенты заряжания. Я бы хотел добавить разные и разнообразные перезарядки, как только на это появится время, обязательно займусь.

"Хотелось бы прояснить, зачем нужен reload_cannon_manual?" - насколько помню, этот ивент почти не используется. Хорошая мысль будет как раз применить его для автоматов заряжания при отсутствии питания.

**Comment by OXEPU3M** [comment]
Спасибо за разъяснения.

Стоит ещё добавить Леклерки. У США же в премиум сегменте много машин с АЗ, Страйкеры и прочие AGS-образные.
Ваша заинтересованность в расширении функциональностей очень радует. Будем с нетерпением ждать.
