### ISSUE TITLE
Are there any new engines?

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#175]
Hi @Uchuujin01 how are you?

are there any new engines? If so, which ones and for which vehicles?

Thank you for your efforts to improve the operation more and more

Best regard
Mathieu

**Comment by Uchuujin01** [comment]
Hello! Sorry for the delay. Unfortunately, I can't say anything about new engines sound events names until those will be released ( I was told not to do this. I'll write their names here right after the update release.

**Comment by IWSM** [comment]
Hello, thank you very much yes I understand perfectly I will wait for your publication.
