### ISSUE TITLE
Музыка при загрузке всё ещё багованная.

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#176]
Мы как-то обсуждали, что музыка ведёт себя странно.
Так вот, на экране загрузки боёв она всё ещё невменяемая, бывает играет action01 и action из top tier, не каждый раз, но достаточно, чтобы обращать внимание.
Были времена, когда такого не было, да и сейчас не нужно, играет 5 секунд без надобности и красоты.

А ещё, если нажать в бой и свернуть игру, эти ивенты играют каждый раз, и не прекращаются по завершении загрузки, независимо от режима игры, что танки, что флот или самолеты. Причём настройки звука  для свёрнутой игры, не играют роли.

**Comment by Uchuujin01** [comment]
По какой-то причине я не смог пока повторить проблему, но уверен, она есть. Я, видимо, потратил не достаточно времени 
 на ее поиск/повторение. Отметил себе эту задачу, надо разбираться серьезнее, спасибо большое.

**Comment by OXEPU3M** [comment]
Спасибо.
