### ISSUE TITLE
Idea to improve

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#177]
Ho @Uchuujin01 
how are you?

Some vehicles like the M16 MGMC are open and therefore should not have internal sounds for Mguns or cannons.
Is it possible for these vehicles to replace the internal sounds and the toggle so that it remains on the external sounds which would be more realistic.

is it possible to link the internal sound trigger to the external sound for these open vehicles

Best regard
Math

**Comment by Uchuujin01** [comment]
Good idea, yes, I thought about it too. I'm about to do so.

**Comment by Uchuujin01** [comment]
Thanks for reminder )
