### ISSUE TITLE
Major issue with loop sounds

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#179]
Hey I found the issue with previous loop system for planes.

If you die simultaneously while shooting, you will hear loop forever, exact same happens for ai events. If you need replays let me know.

**Comment by Uchuujin01** [comment]
Hello! Yes, we fixed this problem already, as far as I know. Is this problem still exist? I'll ask our programmers, why it's still exist.

**Comment by 787992** [comment]
> Hello! Yes, we fixed this problem already, as far as I know. Is this problem still exist? I'll ask our programmers, why it's still exist.

Just came from the game 10-15 mins ago where I had this bug
