### ISSUE TITLE
Bad engine for the 2E challenger

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#180]
Hi @Uchuujin01 

According to the data concerning the challenger 2E, it uses the MTU 883 DIESEL which should be those of the leopard 2, not to remain on the engine of the challenger on Fmod.
I think it would be fairer to pass it on the leo2 engine.

Thanks in advance

Best regard
Math

**Comment by Uchuujin01** [comment]
Hello! Thank you, you right, I'll fix it.

**Comment by IWSM** [comment]
Hi, cool big thanks. Please I need a sound name for new weapons gau19 and ZK453 for VZ 53/59 please.

**Comment by Uchuujin01** [comment]
30mm_zk_453, 30mm_zk_453_ai, 30mm_zk_453_interior. VZ 53/59 has usual M1 engine sound event. About gau 19 I've already answered to you in another topic.

**Comment by IWSM** [comment]
Big thanks,
