### ISSUE TITLE
Remake m1919 and M240 sounds

### ISSUE THREAD

**Issue by FenixAlfa159** [GaijinEntertainment/fmod_studio_warthunder_for_modders#181]
I noticed that the aircraft M1919 Browning sound has a low rate of fire compared to the actual rounds per minute. This also happens with the weapon M240 in ground vehicles, where it uses the ground M1919 sound when they have very different rate of fire. Is there a way we get this changed in the near future?

Thanks you in your work, I keep noticing improvements every update!

**Comment by Uchuujin01** [comment]
Hello! Thank you for noticing that, actually you right, fire rate sound significantly slower than actual fire rate. I've marked it up, will fix.

**Comment by FenixAlfa159** [comment]
> Hello! Thank you for noticing that, actually you right, fire rate sound significantly slower than actual fire rate. I've marked it up, will fix.

Perfect! Thanks for the answer!
