### ISSUE TITLE
Звуки взаимодействий шасси и поверхностей наземной техники

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#185]
Было бы очень здорово, если в оригинальном звуковом проекте все шуршания, плюхи, бульканья и т.п. траков и колёс стали единозависимы с громкостью двигателей.

А то очень странно, когда ставишь свой мотор на минимум, но траки по грунту всё ещё шуршат, что окна в квартире дрожат.
Одно это - уже достаточный повод начать делать моды.
Спасибо.

**Comment by Uchuujin01** [comment]
Привет, уже сделано.
