### ISSUE TITLE
New Mgun sound event M1919 High Fire Rate

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#187]
hi @Uchuujin01 

it is possible to find out the name of the new event for new  machine guns M1919 High Fire Rate aircraft please 🙏 

Thx in advance
Best regards

**Comment by Uchuujin01** [comment]
Hello! Sorry for the delay, the project has been released. In future I'll try to post here all new sound events that has been released on production.
