### ISSUE TITLE
Please update Fmod project

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#188]
Hi @Uchuujin01 

can we get an update on the project soon as there are so many things broken now.

Thanks in advance
Math

**Comment by pixtolero** [comment]
+1 we need it

**Comment by aboutonir** [comment]
+1

**Comment by dac617** [comment]
I completely agree with IWSM. There have been plenty of issues in the modding scene as well as in-game. From various missing sounds to frame rate-related issues causing sounds to overlap and rapidly stutter. They need to be addressed.

**Comment by CoolRusi4** [comment]
Yeah, it's time to update the project already, і already feel that something new from the sounds has been added to War Thunder, so і would like the update to come out as soon as possible...

**Comment by alextro23** [comment]
+1 we need it

**Comment by Uchuujin01** [comment]
Hello everyone! The project has been updated.

I understand everything you wrote here, but, sorry guys, I can release it only when it is ready for the release. In future I can post here all new sound events paths and names, right after they has been released on production circuit. If I'm unable to release the project update in short time.

**Comment by IWSM** [comment]
Hello, thank you for updating. I understand your issues. Thanks again for your excellent work.
