### ISSUE TITLE
Ассеты

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#189]
Здравствуйте.
Баловался с игровыми файлами и пересобирал ивенты. Я хотел сделать максимально унифицированный мод, чтобы во-первых мод не сильно расходился с текущей версией оригинальной звуковой модели, и во-вторых не использовать файлы .assets.bank.
Но с сегодняшним обновлением часть файлов вообще пропала, а часть изменила тональность, громкость и т.п.
Например файлы shot_med_inside* теперь в игре просто не существуют, и часть моих работ потеряла до половины звуков.

Я так понимаю, некоторые (все) вещи теперь не будут архивированы, как, например, двигатели в папках unused? И не стоит даже пытаться пробовать обходиться без своих .assets.bank?
Чего не хотелось бы, ибо придётся ждать обновлений репозитория даже для простейших вещей.
Спасибо.

**Comment by Uchuujin01** [comment]
Добрый день. То, что было в папке unused, не имело ссылок на ассеты в банках .assets.bank (ивенты с тегом Unassigned), так что не очень понимаю, чем эти unused ивенты могли бы пригодиться. Это просто мусор, хранимый некоторое время после изменений, в качестве бэкапа.

Вы довольно спорную штуку задумали, никак нельзя надеяться, что состав асстетов не будет меняться. Все-таки, лучше полагаться на свои собственные .assets.bank и свой набор ассетов.

Но, хорошая новость - с высокой долей вероятности текущие ассеты и ивенты не будут меняться по составу в ближайшем обозримом будущем. "Ближайшее обозримое будущее" оценить количественно не смогу, скажу сразу, но таких планов нет.
