### ISSUE TITLE
question for engine AI tank

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#190]
Hi @Uchuujin01 

If I add a track to the AI tank engine event to play a very distant sound, can it work? Do I absolutely have to increase the distance from 300 to 600m for example?

Tanks in advance
Mathieu

**Comment by Uchuujin01** [comment]
Hello! No, you can't change the max distance, it's in game general sound config.

**Comment by IWSM** [comment]
OK thx
