### ISSUE TITLE
Idea for MBT engine very far sound

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#191]
Hi, 

I think it is possible to create an event [MBT_AI_engine_far] for example.  the idea is to use a common sound for long distance MBTs common to all, not recognizable but a very distant engine hum.  as it approaches, the sounds will switch to the single tank event.  in this way it would be possible to increase the perception distance of tanks to more than 300m without impacting performance.  when do you think?

Best regard
Mathieu (IWSM sound mod)

**Comment by Uchuujin01** [comment]
Hello! I don't understand, why do you need to hear tanks that far? Also, I saw many reference videos of mbts and, you can barely hear mbt's engine farther than 300 m. They almost silent if you have some background noise or significant wind speed.

**Comment by Uchuujin01** [comment]
Also, we don't need our entire map buzzing with engines all around us.

**Comment by IWSM** [comment]
Indeed it also depends on the direction of the wind, but having been in the French army in AMX10Rc, during exercise we could easily hear the AMX 30 at more than 300m. I would say it was loud until about 500m. And I'm not talking about turbine engines like the T80s or the M1 abrams. Additionally, ranged tanks are much louder when their rear and facing you. But I understand the fact of not polluting bordering, my idea was to bring more sound realism

**Comment by Uchuujin01** [comment]
I agree with you in every point. I'd prefer realism in sound too, but, we have quite complex game with many game modes, and we need only one sound model for all those game modes. Also, we have an opposite problem - we need get rid of unwanted sounds that unnecessary for player. For example there are many complains from some players about aircraft engines, some tankers don't want them to buzzing around at all, until they attack them. Also, there are many complains "why should I hear tanks far away if I unable to hear tank nearby". It's quite complicated thing.

**Comment by IWSM** [comment]
I understand. I will continue to make proposals and give you ideas.  Maybe we will manage to improve over time.

**Comment by OXEPU3M** [comment]
It makes cheating abilities. And very easy.
