### ISSUE TITLE
 make a unique sound for tanks engine

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#192]
Hi @Uchuujin01 

Is there a way by script or something else to reassign a new event to a particular tanks.
Example: I want to for the PUMA or the HSTVL, I will create an new event with the engine but how can I signal that the puma must use it from now on?
This would be a great novelty for modders and would bring new possibilities

Another modder managed to do this, so I guess it's doable

Thx in advance
mathieu

**Comment by Uchuujin01** [comment]
Hello! For now, you can't create a sound event with unique name that doesn't registered in game configs.

**Comment by IWSM** [comment]
Yet another modder managed to do it, so it is possible. ^^

**Comment by Uchuujin01** [comment]
No, it is impossible, I assure you. It is definitely fake, if someone claims he managed that.

**Comment by IWSM** [comment]
That's what I thought, thanks for confirming.
