### ISSUE TITLE
Problem RMP on event

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#197]
Hi @Uchuujin01 

![Capture d’écran 2023-05-21 185428](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/63722574/962628f1-08f1-49b8-896f-44a15b72dc8f)

Why when I add audio tracks does it prevent the engine from revving up?
This happens to me on the BMP and the external A-10.
As soon as I add tracks, the engine no longer reacts and stays idle.

Are we limited with a number of possible parameters?. for example on the PT-76 engine, if I add 2 parameters, the engine no longer revs up. same for BMP and A-10 engine

Best regards
Math

**Comment by Uchuujin01** [comment]
Hello! Yes, the limit on engine sound event parameters is 12. Also, check if you have proper rpm parameter, maybe you have several rpm parameters, in this case rpm parameter you need can no longer get values from the game.

**Comment by IWSM** [comment]
That's what I thought, thanks for the confirmation
