### ISSUE TITLE
Перестали работать ивенты из банок в ВТ 1.99

### ISSUE THREAD

**Issue by 3DeshNIK** [GaijinEntertainment/fmod_studio_warthunder_for_modders#20]
В моих модах основанных на последнем исходнике перестали работать банки crew_dialogs_common.bank, и часть ивентов из банки  crew_dialogs_ground.bank пока только обнаружил что не работают выбор снарядов на ББ.

**Comment by Uchuujin01** [comment]
Вообще по части диалогов ничего не изменилось в новой версии, ни в коде, ни в банках, так что на вскидку не могу сказать в чем проблема. Постараюсь изучить вопрос.

**Comment by 3DeshNIK** [comment]
> Вообще по части диалогов ничего не изменилось в новой версии, ни в коде, ни в банках, так что на вскидку не могу сказать в чем проблема. Постараюсь изучить вопрос.

Могу уверенно сказать что модифицированные ивенты в dialogs_crew_aircraft (voice1, voice2, voice3, voice4) перестали работать

**Comment by 3DeshNIK** [comment]
Все само починилось, можно удалить тему.
