### ISSUE TITLE
Crew voices aren't working with custom .masterbank

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#202]
Tested with edited .masterbank and default one that comes with 2.25 update, this is kinda critical as crew voices are completely absent.

Unless it's something in mixer tab and can be done with tweaks there.

**Comment by Uchuujin01** [comment]
Hello! What crew voices do you mean? Because now we got completely new tank crew VO system, the old crew sound events will not work anymore. I'm sorry, but, we need to improve tank crew voice system. As soon as we consider the new system completely working as intended, I release a project update with new tank crew sound events. It will give to sound modders much wider list of events to voice over.

**Comment by 787992** [comment]
> Hello! What crew voices do you mean? Because now we got completely new tank crew VO system, the old crew sound events will not work anymore. I'm sorry, but, we need to improve tank crew voice system. As soon as we consider the new system completely working as intended, I release a project update with new tank crew sound events. It will give to sound modders much wider list of events to voice over.

Hey, I'm not touching anything crew related, only ground/air effects and if you compile the 2.25 project and put your masterbank in mod folder, crew voices will be absent.
But if you remove masterbank, everything goes back to normal

Hence, my conclusion something going on with mixer/and/or new snapshots

**Comment by apachethepyro** [comment]
> As soon as we consider the new system completely working as intended, I release a project update with new tank crew sound events.

Any idea on a time estimate for release of the updated project?

**Comment by Uchuujin01** [comment]
> > As soon as we consider the new system completely working as intended, I release a project update with new tank crew sound events.
> 
> Any idea on a time estimate for release of the updated project?

I'll release new fmod project in the beginning of the next week. Like, 12-14.
