### ISSUE TITLE
Some gun sound is not replaced with custom one.

### ISSUE THREAD

**Issue by NukprachTH** [GaijinEntertainment/fmod_studio_warthunder_for_modders#204]
Hello, I've found issue that after I replaced all gun sounds (exclude All MG.) in the files to my sound. There are still have tanks playing default sound. Like Soviet 85mm, some German long 88mm, etc.

Here's link to my mod: https://live.warthunder.com/post/1075289/en/

*this issue appear before La Royale update.

**Comment by Uchuujin01** [comment]
What do you mean by "sounds"? Is it sound events or wav files? If you have tanks with default sounds, You might not updated some sound events.

**Comment by NukprachTH** [comment]
I think it's sound event problem, I've tested it in editor, it works fine with my custom sound file. But when I test in game it just change to default one. And yes there are no any default cannon sound files remain in the edit program.

**Comment by Uchuujin01** [comment]
This means your sound bank doesn't recognized in sound/mod folder, I guess. Did you build bank? Did you use your build master banks? If not, the game can't see your sound bank withoud proper master bank.

**Comment by NukprachTH** [comment]
Yes, I use it.

**Comment by NukprachTH** [comment]
never mind, I'll use new update one and I'll tell if the problem is still appear or not.
