### ISSUE TITLE
How to change guid for event

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#206]
Good morning @Uchuujin01 

to facilitate the addition of new events and for them to be compatible with your masterbanks, I must be able to modify and assign the guid corresponding to your project. I assume events are called by guids in WT?

I can copy the event guid easily, but there is no option in Fmod studio to rename the guid.
Do you know a trick to do it?

If this were possible, each modder wouldn't have to redo everything every time, we would just have to copy the new events and assign them the correct guids.

exemple : 
<img width="402" alt="Capture d’écran 2023-06-20 142716" src="https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/63722574/b445e76a-3944-4732-8429-e1f1f7fc4a35">

Thanks in advance
Mathieu

**Comment by IWSM** [comment]
@Uchuujin01 It work perfectly. Edit XML and change the guids work. full compatible with your masterbank.

**Comment by Uchuujin01** [comment]
> @Uchuujin01 It work perfectly. Edit XML and change the guids work. full compatible with your masterbank.

Good news for modders ) Thanks for the research
