### ISSUE TITLE
Просьба добавить новые реплики.

### ISSUE THREAD

**Issue by 3DeshNIK** [GaijinEntertainment/fmod_studio_warthunder_for_modders#21]
Добрый день! Я часто нахожу в озвучке игры не использованные реплики или отключенные со временем. У меня большая к вам просьба, если можно ввести новые рабочие ивенты чисто для создателей модификаций, то я очень вас прошу, если можно добавьте ивент на уничтожение танка игрока. Можно даже продублировать реплики с ивента бросить технику. Это очень важно и играет на атмосферу. Так же хочется увидеть в ближайшем будущем новые ивенты такие как:

- Ивент на рикошет, если дамаг система их понимает. Это будет информативно в бою и не нужно отвлекатся взглядом на дамаг модель. 
- Ивент на пожар противника. Так же для информативности, и для атмосферы.
- Ивент в начало матча, что бы можно было добавить воодушевляющею реплику в начале сражения
- Ивент на помощь в уничтожении.

**Comment by Uchuujin01** [comment]
Добрый день! Боюсь, только для модификаций добавить уникальные звуковые события не представляется возможным. Суть модификаций в том, чтобы переделывать существующий игровой контент, а не создавать специально для модификаций новые игровые механики, которые, в лучшем случае, могут не пойти на пользу игре. Но, есть вероятность что в недалеком будущем диалоговая система игры будет дополнена новыми репликами. Спасибо что работаете над модификациями, и помогаете делать игру лучше!
