### ISSUE TITLE
M61 aircraft interior

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#214]
Hi,

why the interior M61 (aircraft) is no longer used? (without desktop) how the internal sounds are played now?

Thx in advance @Uchuujin01 

Best regards

**Comment by Uchuujin01** [comment]
Hello! Sorry for the delay in answer. I'm not sure I understand, what are you talking about?

**Comment by IWSM** [comment]
> 

<img width="911" alt="Capture d'écran 2023-07-20 160449" src="https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/63722574/66be55f4-e481-419c-b000-e6e9b43b9942">

**Comment by IWSM** [comment]
UP
