### ISSUE TITLE
Way to check what tank use which sound event.

### ISSUE THREAD

**Issue by NukprachTH** [GaijinEntertainment/fmod_studio_warthunder_for_modders#216]
Hello, I have a (small) problem that there are some gun that missing in event player (like 183mm). I need some help about How I can make sure that which sound event that tank was using. Thanks.

*I know that there are guns name, but some guns are not there, so I just need other way to make sure which sound event that tank are using.

Thanks.

and sorry if my English are weird, because it's not my main language but I'm still try to improving it. Thanks.

**Comment by NukprachTH** [comment]
Yes, I always do that. But I just need to know are there any other ways to do that.

**Comment by IWSM** [comment]
no

**Comment by IWSM** [comment]
use the referentiel google

**Comment by NukprachTH** [comment]
ok, thanks.
