### ISSUE TITLE
Issue with USSR 85mm (All) and USSR 152mm (All) gun sound

### ISSUE THREAD

**Issue by NukprachTH** [GaijinEntertainment/fmod_studio_warthunder_for_modders#217]
Hello, I've found a problem that some tanks doesn't play their gun sound, instead it play other tank's gun sound.

some gun that I found it have this problem:
-37mm kwk36 --> play 50mm kwk39's sound while in game.

there will more, I think. But this is what I already found for now.

**Comment by IWSM** [comment]
normal, check this for your help https://docs.google.com/spreadsheets/d/1haXooK6mBpU4m_2s9ahRfGTqCPBOPMaLxn5fvMtRt-I/edit?usp=sharing

**Comment by NukprachTH** [comment]
Thank you! but where do you find that?

**Comment by NukprachTH** [comment]
Can I ask other question?

I have a problem with all 85mm
![image](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/111956181/11f00f85-bd40-47b5-af4a-ab98b5fc55a8)

I have changed it's .wav . In editor it work fine, but it's not working in game. how do I fix that since that's only 1 sound that's not working.

**Comment by IWSM** [comment]
you use wich build Fmod studio?

**Comment by NukprachTH** [comment]
2.1.6

**Comment by IWSM** [comment]
you use ingame 2 files? ( tank_weapons_asset.bank and tank_weapon.bank ?

**Comment by NukprachTH** [comment]
yes

**Comment by NukprachTH** [comment]
ok, I've changed article for not build too much unnecessary article.

So as you can see I have problem about ussr 85mm and ussr 152mm

The problem is I have changed the wav file to mine one, but it's still play default one when in game. While it's working fine in editor.

and look like this is only problem I found since other guns sound are working perfectly fine.
