### ISSUE TITLE
I now modify the weapon sound of the aircraft into the game. There is no sound when firing. Is the weapon sound file too old？

### ISSUE THREAD

**Issue by wzyc123456** [GaijinEntertainment/fmod_studio_warthunder_for_modders#22]
I now modify the weapon sound of the aircraft into the game. There is no sound when firing. Is the weapon sound file too old？

**Comment by Uchuujin01** [comment]
Hello! What sound exactly you trying to modify?

**Comment by wzyc123456** [comment]
> 你好！您到底想修改什么声音？

I want to change air guns

**Comment by wzyc123456** [comment]
> 你好！您到底想修改什么声音？

After the modification, all the planes, including the helicopter, are silent

**Comment by Uchuujin01** [comment]
> > 你好！您到底想修改什么声音？
> 
> I want to change air guns

What exactly gun? Are you sure your events added to sound banks? Does your sound events sounds in fmod studio?

**Comment by wzyc123456** [comment]
> > > 你好！您到底想修改什么声音？
> > 
> > 
> > 我想换气枪
> 
> 究竟是什么枪？您确定将事件添加到声音库中吗？您的声音事件会在fmod studio中听起来吗？

It's the aircraft weapon. I put it in the mod folder created by sound and changed the Notepad, but when I entered the game, the aircraft shot without any sound

**Comment by wzyc123456** [comment]
> > > 你好！您到底想修改什么声音？
> > 
> > 
> > 我想换气枪
> 
> 究竟是什么枪？您确定将事件添加到声音库中吗？您的声音事件会在fmod studio中听起来吗？

It's the aircraft weapon. I put it in the mod folder created by sound and changed the Notepad, but when I entered the game, the aircraft shot without any sound

**Comment by Uchuujin01** [comment]
> It's the aircraft weapon. I put it in the mod folder created by sound and changed the Notepad, but when I entered the game, the aircraft shot without any sound

I'm already understood that it's an aircraft weapon. You mentioned it in the very first message ) What exactly weapon do you try to modify (sound event name)? Does it sounds in fmod studio? What version of fmod studio do you use? What exactly do you put in sound/mod folder?

**Comment by wzyc123456** [comment]
> > 这是飞机武器。我将其放在声音创建的mod文件夹中，并更改了记事本，但是当我进入游戏时，飞机射击时没有任何声音
> 
> 我已经知道这是飞机武器。您在第一条消息中提到了它）您到底尝试修改什么武器（声音事件名称）？在fmod studio中听起来吗？您使用什么版本的fmod studio？您究竟在sound / mod文件夹中放了什么？

I used 1.10.17 version of studio, Put in the webons file package downloaded here, and modify it according to the tutorial. I tried to modify mg151 and mg131. After the modification, I put them into the mod folder created by sound. Then I opened the game for testing and found that there was no sound when the aircraft fired, not only the two I modified, but also all the air weapons, fixed wing aircraft and helicopter weapons fired without sound

**Comment by Uchuujin01** [comment]
> > > 这是飞机武器。我将其放在声音创建的mod文件夹中，并更改了记事本，但是当我进入游戏时，飞机射击时没有任何声音
> > 
> > 
> > 我已经知道这是飞机武器。您在第一条消息中提到了它）您到底尝试修改什么武器（声音事件名称）？在fmod studio中听起来吗？您使用什么版本的fmod studio？您究竟在sound / mod文件夹中放了什么？
> 
> I used 1.10.17 version of studio, Put in the webons file package downloaded here, and modify it according to the tutorial. I tried to modify mg151 and mg131. After the modification, I put them into the mod folder created by sound. Then I opened the game for testing and found that there was no sound when the aircraft fired, not only the two I modified, but also all the air weapons, fixed wing aircraft and helicopter weapons fired without sound

Try to remove masterbank.bank and masterbank.strings.bank from your sound/mod/ folder. It is your custom fmod mixer settings, so if you remove it, the game will load this settings from sound/ folder. I assume the support of this mechanism is broken somehow. We'll check it and will release fix soon, if it will be necessary.

Please write here, if this will help or not.

**Comment by Uchuujin01** [comment]
Update, I just checked masterbank.bank and masterbank.strings.bank - it works well, so, hardly this is the cause of your issue.

**Comment by Uchuujin01** [comment]
Hello! We found that something works wrong in mod sound banks loading. I hope today we'll find out what's wrong, and will fix it asap.

**Comment by Uchuujin01** [comment]
The problem in outdated version of this project. Some events now have different GUIDs. We loading events by GUID, not by string names. So, that's why some sounds not found. We can fix this problem for you only with actualisation of this project repo. I'll do this asap! The problem is - we just moved on new Fmod Studio version - 2.00.09 (on develop version of client), so it pointless, to publish this project in 1.10.17 version. But now on production version still 1.10.17.

**Comment by wzyc123456** [comment]
> 您可以使用mod，但不能在声音/ mod中使用.masterbanks。这意味着-没有您自定义的混音器设置。



> 您可以使用mod，但不能在声音/ mod中使用.masterbanks。这意味着-没有您自定义的混音器设置。

Can 1.10.17 studio still be used？

**Comment by Uchuujin01** [comment]
> > 您可以使用mod，但不能在声音/ mod中使用.masterbanks。这意味着-没有您自定义的混音器设置。
> 
> > 您可以使用mod，但不能在声音/ mod中使用.masterbanks。这意味着-没有您自定义的混音器设置。
> 
> Can 1.10.17 studio still be used？

After the transition to 2.00.09? No, sound form 1.10.17 will be banks incompatible. But now on production still 1.10.17.
