### ISSUE TITLE
need a korean crew and radio sound file

### ISSUE THREAD

**Issue by RustyFinger00** [GaijinEntertainment/fmod_studio_warthunder_for_modders#221]
Can I get the Korean version of the crew voice and radio voice?

and

Can you tell me how to adjust crew voice volume?

**Comment by Uchuujin01** [comment]
For now you can't get Korean version because we still working on it, but you can create your own Korean sound banks with your own content. We'll add Korean files later, when we get a final versions.

You can adjust volume or in sound events or in Mixer View (ctrl+2)
