### ISSUE TITLE
update for Tank_effects pls

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#226]
Hi @Uchuujin01 
can you tell us about the new sound events in tank-effects? Because all the mods are broken on the effects.bank.
RICO
BOUNCE
HIT

all are broken with all mod

Thanks in advance
math

**Comment by Sweggymanjenson** [comment]
Can confirm that these are broken for me as well.

**Comment by Uchuujin01** [comment]
Hello! I suppose the problem is gone? Because we've rolled back effects for ricos, hits and so on.

**Comment by IWSM** [comment]
@Uchuujin01 No, all ricochet/bounc/hit effects no longer work

**Comment by FenixAlfa159** [comment]
I agree with @IWSM . Right now bullet passbys and sound effects related to shell impacts/ricochets, and so on aren't working.

**Comment by Uchuujin01** [comment]
This is weird... I have no idea what got broken, will try to figure out. As far as I see we have usual sound events for ricochet/bounc/hit effects.

**Comment by IWSM** [comment]
Thanks

**Comment by Uchuujin01** [comment]
> @Uchuujin01 No, all ricochet/bounc/hit effects no longer work. Not work with latest Fmod projects. something must have stayed in your bank that no longer works with the Fmod projects we have

Did you place masterbank from the project to /mod folder?

**Comment by IWSM** [comment]
yes, Do not change anything

**Comment by Uchuujin01** [comment]
> yes, Do not change anything, it's as if the events were no longer called by the game code

I can 100 assure you, we still call the same sound events, nothing changed ( This problem needs investigation, weird bug.

**Comment by IWSM** [comment]
something happened between your Fmod project and ours :)

**Comment by Uchuujin01** [comment]
> something happened between your Fmod project and ours :)

Do you have those sounds in vanilla version?

**Comment by IWSM** [comment]
Yes I test with latest fmod project without modif

**Comment by IWSM** [comment]
If use a latest fmod project and build tank_effects, not work for hit, rico, bounce
