### ISSUE TITLE
BUG with new MG system

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#229]
Hi @Uchuujin01 

I understand that recently you have put in place the same system as for the weapons of the planes on the tanks. The external sounds and doubled with the internal. However, I have tried many things (snapshot, command) but nothing works correctly.
If you fire a MG in external view and hold down while switching to internal view, then the external sound continues to play for 2 seconds and overlaps. With this change, I had no such thing. even if I use a snapshot "tank" or "tank_open" and if I lower the external volumes in the mixer, the bug remains. you just have to test the MG42 on a leopard 2 for example, the bug gets along very well.

My solution, return to the system before which worked very well.

ps: I see that you are currently suffering from the same bug, can you check why the external sounds continue to play 2 or 3 seconds after switching to internal view? only if you stay pressed on the MG shot while changing your view

best regard
mathieu

**Comment by Uchuujin01** [comment]
Hello! This because tank and tank_open snapshots switches on with 1 second delay. As for me, not a big problem, but I'll mark it up, will adjust delay time.

**Comment by IWSM** [comment]
Ok, I understand. thanks for response
