### ISSUE TITLE
Distintive Helicoter sounds

### ISSUE THREAD

**Issue by FenixAlfa159** [GaijinEntertainment/fmod_studio_warthunder_for_modders#230]
I wanted to suggest some changes to how helicopter sounds are worked. May be it adding more AI variants (be it based on helicopter model, or the amount of blades it has).
Also wanted to do the same with player sounds. Right now, for example, the UH-1 "Huey" only has the same sound event as the AH-1/AH-64 helicopters that has more blades compared to the UH-1 (this one has only 2 rotor blades, sounding pretty distintive.

Hopefully it's possible! I'd love to have a more distintive way of identifying helicopters. Right now there's a generic AI rotor event for all helis.

**Comment by Uchuujin01** [comment]
Yes, this work already in progress, thank you for the suggestion )

**Comment by FenixAlfa159** [comment]
Glad to read this! Thanks you!
