### ISSUE TITLE
Is there a way to disable the radio jarring noise in the crew voice?

### ISSUE THREAD

**Issue by sawamuraeriri96** [GaijinEntertainment/fmod_studio_warthunder_for_modders#231]
im trying to make voice mod, but new radio jarring noise and echo effect which added recent upadate makes difficult to hear the voice.
is there a way to disable the radio jarring noise and echo effect?

**Comment by sawamuraeriri96** [comment]
> You can replace this radio noise by whatever you want. dialogs_crew_ground/background_noises/, there are noise sound events.

Even if I mute layer00 of background_noises or remove layer00, the noise still occurs as usual, what should I do? The inserted audio is playing fine, so I don't think there is anything wrong with the build, but maybe I need to build a different file from dialogs_common and crew_dialogs_ground_new?

best regards,

**Comment by Uchuujin01** [comment]
Take a look at noise sound events, what bank they are belong? As far as I remember, they're in tanks_effects, try to move them to masterbank and rebuild tanks_effects and masterbank.

**Comment by OXEPU3M** [comment]
> Take a look at noise sound events, what bank they are belong? As far as I remember, they're in tanks_effects, try to move them to masterbank and rebuild tanks_effects and masterbank.

I already told you. Even if we do that it doesn't work.
And deleting all post effects in events and buses do no effect.
https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/issues/211

**Comment by TooCoolDude** [comment]
And there is distortion effect in mixer on crew members. Next if I build master bank, there is no radio noise in game, but also no tank gun audio in 3rd person mod.

**Comment by sawamuraeriri96** [comment]
https://live.warthunder.com/post/1086055/en/
solved

**Comment by sawamuraeriri96** [comment]
solved
