### ISSUE TITLE
RWR and jet alert

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#235]
Hi,

Now we are arriving on very recent jets equipped with advanced RWR and alert systems in the cockpit.

Altitude alerts are needed, only for this.
you need a fuel alert
a breakdown alert is required (example of hydrolic breakdown) linked to a red visual alert in the cockpit
there is a great need for an RWR missile firing alert.

Have you already started working on these events?
When will they arrive?

you also need a different missile seeker depending on the type of missile used. AIM currently uses the same as ground anti air.

Thanks in advance @Uchuujin01 
Best regard

**Comment by IWSM** [comment]
LMAO, I check the new trailer. 

GG @Uchuujin01 

New Fmod project date?

**Comment by Uchuujin01** [comment]
Hello! Thank you for the notes, I agree with you. We haven't worked on RWR still, but this work is in future plans for sure.

**Comment by IWSM** [comment]
Thanks for response
