### ISSUE TITLE
NEED FMOD "sons of attila" UPDATE

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#236]
Hi @Uchuujin01 

A lot of things sound broken on the last version of the project (tank_effect for exemple) and there will be a lot of new RWR events and others. Can we get the update up and running soon enough so we can redo all our work again.

Thanks in advance

Math (IWSM sound mod
Best regards

**Comment by Uchuujin01** [comment]
Hello! Sure, right after we release Sons of Atilla, I can't release FMOD project before the official release. Also, we need several days for bug fixes.
