### ISSUE TITLE
Проблемы на этапе сборки.

### ISSUE THREAD

**Issue by CCCPDriver** [GaijinEntertainment/fmod_studio_warthunder_for_modders#24]
И снова добрый день) Не знаю почему, но при каждом обновление проекта, при сборке банков всегда появляются какие-то ошибки.  В тот раз я вылечил заменой файлов некоторых, сейчас же, таких файлов, а иногда даже и папок нет. Из-за такой одной ошибки, полностью не работают звуки из этого банка.
На скрине пример, там множество таких ошибок.
![image](https://user-images.githubusercontent.com/62462287/87685108-b1777900-c78b-11ea-8342-592916e38215.png)

**Comment by CCCPDriver** [comment]
![image](https://user-images.githubusercontent.com/62462287/87685956-a244fb00-c78c-11ea-8105-1c55c053fb6a.png)

**Comment by CCCPDriver** [comment]
![image](https://user-images.githubusercontent.com/62462287/87686002-ae30bd00-c78c-11ea-835d-ec340f02aa22.png)

![image](https://user-images.githubusercontent.com/62462287/87686030-b7ba2500-c78c-11ea-9ce1-8a39526bce6e.png)
![image](https://user-images.githubusercontent.com/62462287/87686077-c56faa80-c78c-11ea-98c4-ae74e62154bb.png)
![image](https://user-images.githubusercontent.com/62462287/87686119-d0c2d600-c78c-11ea-9cd9-e29d7de28f80.png)

**Comment by Uchuujin01** [comment]
Привет! Часть файлов отсутствует намеренно, но часть я недосмотрел, сейчас донесу.

**Comment by CCCPDriver** [comment]
> Привет! Часть файлов отсутствует намеренно, но часть я недосмотрел, сейчас донесу.

Главное, что бы на этапе сборки основных файлов, не было проблем. Банки hangar, weapon, effects и тд. И спасибо за быстрый ответ. Жду обновления.

**Comment by Uchuujin01** [comment]
> > Привет! Часть файлов отсутствует намеренно, но часть я недосмотрел, сейчас донесу.
> 
> Главное, что бы на этапе сборки основных файлов, не было проблем. Банки hangar, weapon, effects и тд. И спасибо за быстрый ответ. Жду обновления.

Готово!

**Comment by CCCPDriver** [comment]
Большое спасибо, Сейчас протестирую. Кст, небольшой баг репорт. Звуки
попаданий пулемётных пуль по броне, проигрываются даже тогда, когда по
танку не попадают пули. Это не особо заметно, но всё же)

чт, 16 июл. 2020 г. в 19:58, Uchuujin01 <notifications@github.com>:

**Comment by CCCPDriver** [comment]
Тестировал в пробном выезде. Стрелял по броне, прекращал стрелять, но звук попаданий длился еще 1 -1.5с

**Comment by Uchuujin01** [comment]
> Тестировал в пробном выезде. Стрелял по броне, прекращал стрелять, но звук попаданий длился еще 1 -1.5с

А, это не то чтобы баг ) Особенность имплементации звукового события скорее, технологически получается либо так, либо звук будет звучать в три раза реже. Я решил что лучше так.

**Comment by CCCPDriver** [comment]
> > Тестировал в пробном выезде. Стрелял по броне, прекращал стрелять, но звук попаданий длился еще 1 -1.5с
> 
> А, это не то чтобы баг ) Особенность имплементации звукового события скорее, технологически получается либо так, либо звук будет звучать в три раза реже. Я решил что лучше так.

Понял. Спасибо за ответы) Я понимаю, что вы заняты и так очень, но можно ли написать, пару пожеланий по звуку? Они не особо большие.

**Comment by Uchuujin01** [comment]
> > > Тестировал в пробном выезде. Стрелял по броне, прекращал стрелять, но звук попаданий длился еще 1 -1.5с
> > 
> > 
> > А, это не то чтобы баг ) Особенность имплементации звукового события скорее, технологически получается либо так, либо звук будет звучать в три раза реже. Я решил что лучше так.
> 
> Понял. Спасибо за ответы) Я понимаю, что вы заняты и так очень, но можно ли написать, пару пожеланий по звуку? Они не особо большие.

Конечно, конструктивный фидбек всегда кстати )

**Comment by CCCPDriver** [comment]
Отлично. Так как, я лютый танкист, все пожелания будут именно оттуда. 
1. Хотелось бы сделать отдельные ассеты на звук рикошета. А именно, сначала звук попадания снаряда, а уже потом тот самый свист, который уже будет привязан к снаряду, который отрикошетил. Сейчас бывает так, что происходит рикошет, например влево от танка, а звук просто по прямой.
2. Не так давно была добавлена физика для отлетающих танковых башен, но вот звука ее падения нет. Она просто падает. Бывает, что она даже на свой танк падает, но никакого звука) Башни у нас в игре, очень часто отлетают, особенно, когда подрывается БК.
3. Есть ли возможность звук запуска артиллерии сделать объемным и привязать его к респавну той команды, откуда был произведён залп, хотя бы сделать имитацию этого? В Enlisted уже реализована эта система. Это не сложно.
4. И последнее. Игрокам нужен "эпик". Мы все насмотрелись фильмов по типу "Ярость". Теперь нам нужен тот самый свист после рикошета)
А так, вы молодцы. Спасибо за вашу работу. Отдельное спасибо за новые звуки попаданий по танку. Они отличные,

**Comment by Uchuujin01** [comment]
> Отлично. Так как, я лютый танкист, все пожелания будут именно оттуда.
> 
> 1. Хотелось бы сделать отдельные ассеты на звук рикошета. А именно, сначала звук попадания снаряда, а уже потом тот самый свист, который уже будет привязан к снаряду, который отрикошетил. Сейчас бывает так, что происходит рикошет, например влево от танка, а звук просто по прямой.

Возьму на заметку, можно будет попробовать.

> 2. Не так давно была добавлена физика для отлетающих танковых башен, но вот звука ее падения нет. Она просто падает. Бывает, что она даже на свой танк падает, но никакого звука) Башни у нас в игре, очень часто отлетают, особенно, когда подрывается БК.

Отличное замечание, сделаем обязательно.

> 3. Есть ли возможность звук запуска артиллерии сделать объемным и привязать его к респавну той команды, откуда был произведён залп, хотя бы сделать имитацию этого? В Enlisted уже реализована эта система. Это не сложно.

Подгляжу как там в Энлистеде, хорошая мысль.

> 4. И последнее. Игрокам нужен "эпик". Мы все насмотрелись фильмов по типу "Ярость". Теперь нам нужен тот самый свист после рикошета)

Я к, своему стыду, не смотрел Ярость, посмотрю ) 

>    А так, вы молодцы. Спасибо за вашу работу. Отдельное спасибо за новые звуки попаданий по танку. Они отличные,

Спасибо большое, очень рад )

**Comment by CCCPDriver** [comment]
А.. Еще. Звук подрыва БК не привязан к источнику. Тогда взорвал БК у м1
Абрамс, он поехал, а звук так и остался на том месте, где я в него попал.

чт, 16 июл. 2020 г. в 21:15, Uchuujin01 <notifications@github.com>:

**Comment by Uchuujin01** [comment]
> А.. Еще. Звук подрыва БК не привязан к источнику. Тогда взорвал БК у м1 Абрамс, он поехал, а звук так и остался на том месте, где я в него попал. чт, 16 июл. 2020 г. в 21:15, Uchuujin01 <notifications@github.com>:

Это да, все взрывы у нас one shot, и стало быть, не имеют апдейта позиции, это сделано намеренно, чтобы облегчить жизнь процессору )

**Comment by CCCPDriver** [comment]
> > А.. Еще. Звук подрыва БК не привязан к источнику. Тогда взорвал БК у м1 Абрамс, он поехал, а звук так и остался на том месте, где я в него попал. чт, 16 июл. 2020 г. в 21:15, Uchuujin01 [notifications@github.com](mailto:notifications@github.com):
> 
> Это да, все взрывы у нас one shot, и стало быть, не имеют апдейта позиции, это сделано намеренно, чтобы облегчить жизнь процессору )

Всё таки есть одна не большая проблема. С модом попросту перестают работать звуки быстрых голосовых команд. Раньше, если я не кидал банки команд, они работали по умолчанию. А сейчас же нет.

**Comment by Uchuujin01** [comment]
> Всё таки есть одна не большая проблема. С модом попросту перестают работать звуки быстрых голосовых команд. Раньше, если я не кидал банки команд, они работали по умолчанию. А сейчас же нет.

Точно последняя версия проекта стянута? Я сегодня сделал несколько коммитов, в частности, тот что правит аудио-таблицы. Проверил сейчас - все ок с голосовыми командами, вроде бы.

**Comment by CCCPDriver** [comment]
Да. Версия 2.0.0.9. Там на этапе сборки голосовых банков вылезают ошибки
такие же

пт, 17 июл. 2020 г., 0:24 Uchuujin01 <notifications@github.com>:

**Comment by Uchuujin01** [comment]
> Да. Версия 2.0.0.9. Там на этапе сборки голосовых банков вылезают ошибки такие же пт, 17 июл. 2020 г., 0:24 Uchuujin01 <notifications@github.com>:


Я имею ввиду, последняя ли версия этого репозитория стянута? Я ведь весь день вчера коммиты делал. На этапе сборки голосовых банков естественно будут ошибки, если ассетов нет. Проверяй пожалуйста, есть ли ассеты, если их нет - ясное дело, не надо их компилировать просто, пока они не появятся. Сейчас ассеты есть для всех танковых, а для самолетных - только русская и английская локализации.

**Comment by CCCPDriver** [comment]
Вот например. Раньше я мог кинуть в папку мод tank_weapon.bank  и
заменялись только звуки стрельбы, а все остальное было стандартным. Сейчас
же, эти самые переговоры попросту не будут работать если не кинуть нужные
банки в папку мод. Это такая особенность новой версии?

чт, 16 июл. 2020 г., 17:52 Uchuujin01 <notifications@github.com>:

**Comment by Uchuujin01** [comment]
> Вот например. Раньше я мог кинуть в папку мод tank_weapon.bank и заменялись только звуки стрельбы, а все остальное было стандартным. Сейчас же, эти самые переговоры попросту не будут работать если не кинуть нужные банки в папку мод. Это такая особенность новой версии? чт, 16 июл. 2020 г., 17:52 Uchuujin01 <notifications@github.com>:

А скомпиленные тобой мастер-банки в папке с модами? Что ты делаешь, последовательно, напиши пожалуйста.

**Comment by CCCPDriver** [comment]
Ну как. Собираю банки, потом кидаю их в папку mod. И все.

пт, 17 июл. 2020 г., 11:22 Uchuujin01 <notifications@github.com>:

**Comment by Uchuujin01** [comment]
> Это такая особенность новой версии?

Я пока не смог повторить твоей проблемы, у меня все работает четко. По всей видимости, есть еще какие-то условия, или просто диалоги, которые ты ожидаешь услышать, отсутствуют в репозитории в принципе. Повторюсь, сейчас есть только русская и английская локализации.

**Comment by CCCPDriver** [comment]
Ну да. У меня о умолчанию в клиенте игры стоит русская озвучка. Пробовал
быстрые команды ( num 1, num 3) например. И ничего. Сегодня вечером все
перепроверю ещё раз. Спасибо.

пт, 17 июл. 2020 г., 11:42 Uchuujin01 <notifications@github.com>:

**Comment by CCCPDriver** [comment]
> > Это такая особенность новой версии?
> 
> Я пока не смог повторить твоей проблемы, у меня все работает четко. По всей видимости, есть еще какие-то условия, или просто диалоги, которые ты ожидаешь услышать, отсутствуют в репозитории в принципе. Повторюсь, сейчас есть только русская и английская локализации.

Привет. Действительно, мой косяк. Появилось два вопроса. Я сейчас занимаюсь только танковой частью, нужно ли кидать банки, связанные с авиацией в мод:? Раньше не нужно было.  И второй вопрос, какой банк отвечает за радиопереговоры экипажа танка? Ну там, как командир говорит, " следующий подкалиберный" и тд?

**Comment by Uchuujin01** [comment]
> Привет. Действительно, мой косяк. Появилось два вопроса. Я сейчас занимаюсь только танковой частью, нужно ли кидать банки, связанные с авиацией в мод:? Раньше не нужно было. И второй вопрос, какой банк отвечает за радиопереговоры экипажа танка? Ну там, как командир говорит, " следующий подкалиберный" и тд?

Привет! первый вопрос - нет, не нужно, ничего не изменилось, кроме версии fmod studio. Второй вопрос - это банки crew_dialogs_ground. Только обрати внимание не особенности работы с локализациями в fmod. Банки языков содержат аудио-таблицы со списками ассетов, тогда как основной банк, в данном случае crew_dialogs_ground, содержит звуковые ивенты.

**Comment by CCCPDriver** [comment]
> > Привет. Действительно, мой косяк. Появилось два вопроса. Я сейчас занимаюсь только танковой частью, нужно ли кидать банки, связанные с авиацией в мод:? Раньше не нужно было. И второй вопрос, какой банк отвечает за радиопереговоры экипажа танка? Ну там, как командир говорит, " следующий подкалиберный" и тд?
> 
> Привет! первый вопрос - нет, не нужно, ничего не изменилось, кроме версии fmod studio. Второй вопрос - это банки crew_dialogs_ground. Только обрати внимание не особенности работы с локализациями в fmod. Банки языков содержат аудио-таблицы со списками ассетов, тогда как основной банк, в данном случае crew_dialogs_ground, содержит звуковые ивенты.

**Comment by CCCPDriver** [comment]
Добрый день. Ты сказал, что ничего не поменялось. Продолжу всю ту же тему. В прошлой версии мне не нужно было кидать папки связанные с радиопереговорами и тд, они работали по умолчанию. В свою очередь, это сильно влияло на размер мода. Сейчас же, более или менее стабильная сборка у меня весит около 350мб... Вообще не как не сделать так, что бы звуки из банков, которые ты накидаешь в папку mod, работали работали из стандартной директории, т.е из папки sound?
