### ISSUE TITLE
[Question] Where to access uncompressed crew voices

### ISSUE THREAD

**Issue by d2dyno1** [GaijinEntertainment/fmod_studio_warthunder_for_modders#240]
Hi! I've been recently going through the files and wanted to get the Hebrew crew voices. Unfortunately, however, I've noticed that (unlike other older crew voices) the Hebrew ones are strongly compressed drastically decreasing their audio quality. Where can I grab the uncompressed voice lines from?

Some even appear to be broken with the current compression level - you can hear a buzz while playing the sound file. Examples include:
`voice_message_art_command_oneself_v1_3`
`voice_message_art_reloading_v3_3`
`voice_message_charged_v1_1`

Thanks 🙂 
@Uchuujin01

**Comment by Uchuujin01** [comment]
Hello! There is no Hebrew voices for the new version of tank crew voices, but we're about to add them in the game soon. And also I'm about to add them here in the project too.

**Comment by Uchuujin01** [comment]
I see, you want the old ones, I'll add them here today, okay.

**Comment by Uchuujin01** [comment]
Done

**Comment by d2dyno1** [comment]
Thank you so much!
