### ISSUE TITLE
Thanks for the work

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#243]
Hi  @Uchuujin01 
 I wanted to congratulate you on your work, especially on the helicopters. We must continue the good communication between us (modders) and you. I would like it to be faster but I think you did it as quickly as possible.

Is it possible to see you come here every week to answer us? because currently the average response time is less than 3 or 4 weeks. It would be great for us if we could get answers faster to fix or understand our mods.
Thanks in advance

Math (IWSM) sound mod

**Comment by Uchuujin01** [comment]
Hello @IWSM! Thank you for your kind words ) I'll try to come here more often, once a week at least. It's not so easy because of amount of work I have to do. But, I agree, there is no excuses.
