### ISSUE TITLE
How do you properly update to the newest repository version without erasing your progress? -HELP needed-

### ISSUE THREAD

**Issue by Sweggymanjenson** [GaijinEntertainment/fmod_studio_warthunder_for_modders#244]
Sorry I'm not sure where to post this to get a proper answer. 

I fetched the newest version of the repository to update the version I was currently working on.

While updating through the Github desktop app, it said I would need to store my changes and then I could re-apply them after it updated my version of the repository, so that's what I did.

After it updated I launched the FMOD project file (with version 2.02.14) and a TON of events are missing that I had made changes to while others that I had also changed are unaffected.

The events that are missing are primarily aircraft engine events that I modified( engine01, engine02, ect.) as well as some MG sound events and other misc events that are no longer there. Everything else that I have changed has remained mostly un-effected. (music, cannon sounds, explosions, ect.)

![image](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/134158027/bc3c9aaf-0429-4147-9a10-36ebbe539148)

I have noticed that in the events that are missing, when opening their GUIDs .xml file I would find this
"Updated upstream XXXX Stashed changes"

![image_2023-09-25_142033305](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/134158027/42a3b41a-be1e-4883-9b27-ca853a02531f)
  
So with that said how do you properly update the repository? Is there any way I could fix this issue?  

Any help would be appreciated. Thanks!

**Comment by Uchuujin01** [comment]
Hello! Your previous Fmod project version was 2.01.06, so it is incompatible with version 2.02.14, so, you can't stash your changes and then merge. First, you need to open your project with 2.02.14 and convert it from 2.01.6 to 2.02.14. Then, you need to open both projects, your local and new Sons of Atilla, and manually copy your events. Or, you can verify the difference between your project and new updated, and copy changed events, and new events, to your project.

**Comment by 1095368180** [comment]
For Porting events into new project, you need to copy following contents to the new project.
All modified files from "Metadata\Event"
All modified files from "Metadata\AudioFile"

**Comment by Sweggymanjenson** [comment]
Alright, thanks for the help. I'll have to rebuild from an older version of the mod I am working on as it seems my current mod files are almost completely unusable now. Now that I know how to properly update I will not make the same mistake again. (hopefully) :)
