### ISSUE TITLE
Canon sound ext/int

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#247]
Hi @Uchuujin01 

the internal cannon shots always receive the external sounds at the same time, which means that there is no longer any real difference in sounds. In the turret, the sound should be metallic and muffled, not dry with an echo like outside. Is it possible to no longer play the external sounds during an internal shot (all tank guns)

Thanks in advance
math

**Comment by Uchuujin01** [comment]
What's the problem with this? I don't understand. Can't you use snapshots to adjust the amount of exterior sounds you want?

**Comment by Uchuujin01** [comment]
> > Quel est le problème avec cela? Je ne comprends pas. Ne pouvez-vous pas utiliser des instantanés pour ajuster la quantité de sons extérieurs que vous souhaitez?
> 
> Yes I already modified it, but what is the reason to use the external sounds in the internal view with the vanilla sounds?

It is for camera view switch purpose, when you switch it, you can hear prolonged exterior or interior sounds, this is impossible if you use only interior or exterior sound at a time. Also, not all players agree with you, most want to hear exterior boom inside, and less metallic sounds inside. Players usually shoot from the gunner view most of the time.

**Comment by IWSM** [comment]
> > > Quel est le problème avec cela? Je ne comprends pas. Ne pouvez-vous pas utiliser des instantanés pour ajuster la quantité de sons extérieurs que vous souhaitez?
> > 
> > 
> > Yes I already modified it, but what is the reason to use the external sounds in the internal view with the vanilla sounds?
> 
> C’est pour le but de l’interrupteur de vue de la caméra, lorsque vous le changez, vous pouvez entendre des sons extérieurs ou intérieurs prolongés, ce qui est impossible si vous utilisez uniquement le son intérieur ou extérieur à la fois. De plus, tous les joueurs ne sont pas d’accord avec vous, la plupart veulent entendre le boom extérieur à l’intérieur et moins de sons métalliques à l’intérieur. Les joueurs tirent généralement depuis la vue du tireur la plupart du temps.

OK, even though I don't understand this personally, I understand why you did it. But found a way to separate internal and external sounds to completely eliminate external sounds in internal view. Thank you for the answer.
