### ISSUE TITLE
[QUESTION] Разделение звуков озвучки на Low, Med, High

### ISSUE THREAD

**Issue by ValbertonHere** [GaijinEntertainment/fmod_studio_warthunder_for_modders#249]
Каким образом игра понимает, что надо использовать определенный вариант озвучки экипажа? Изучить самому сейчас нет возможности, а по геймплейным видео слышу, что всегда воспроизводятся фразы из варианта "High".

**Comment by Uchuujin01** [comment]
Сейчас используются варианты med и high, по отзывам игрокам не понравились варианты Low. Варианты high звучат в подавляющем количестве случаев потому что бои интенсивные и почти со старта сессий. В РБ и СБ конечно med звучит чаще.

**Comment by ValbertonHere** [comment]
> Сейчас используются варианты med и high, по отзывам игрокам не понравились варианты Low. Варианты high звучат в подавляющем количестве случаев потому что бои интенсивные и почти со старта сессий. В РБ и СБ конечно med звучит чаще.

Так, хорошо, а какое условие того, какой вариант должен использоваться в данный момент?

**Comment by Uchuujin01** [comment]
Условия довольно сложные, в целом это зависимость от активности противников и союзников.

**Comment by ValbertonHere** [comment]
> Условия довольно сложные, в целом это зависимость от активности противников и союзников.

Понял, благодарю за ответы.
