### ISSUE TITLE
2.00.09 tons off issues now

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#25]
i was happy that the new files droped today an the new fmod version aswell 
but unfortunately.. nothing is working really.. 
because my soundmod is very small i was able to setup everything pretty fast.
but there are some bugs now like:
many effect sounds like the impact sounds are missing
i dont know if its a problem with the bank files but i cant lower the cannon sounds in the game or the ingame music, everything in the game (like cannon or engine volume) is controlled by the main volume now.
i use costum hangar music and now i dont have the default battle music anymore.
is it possible to use the older fmod version 1.10.17 ? because that one worked perfectly except that 1 or 2 engine sounds are missing
i do not want to blame anyone for this, i can imagine how long this takes to create these soundmod files

**Comment by Uchuujin01** [comment]
I'm not sure what are you talking about. What doesn't work exactly? The project is in stable stage, every bank can be compiled without errors. I think you need more time to figure out what's changed and how the project works, maybe?
Be sure, I compiled and tested all banks as sound mods - everything works fine

> is it possible to use the older fmod version 1.10.17 ? because that one worked perfectly except that 1 or 2 engine sounds are missing

No, it is impossible, but, be sure, this 2.00.09 version works fine too. We can hear it in game, for example

**Comment by RadonSound** [comment]
im sorry for some misunderstanding,
The main problem i have is, when i for example turn the Gunfire Volume in game to 0 i still hear gunfires and the same thing is with "Music Volume in Menu" and "Music and Internet Radio Volume" in game. 
The next thing is when i add some costum hangar themes like in the previous version 1.10.17 , i can hear the costum theme in game ( with the circumstances from the first problem ) but i dont have the default battle music in game or the Win and Lose themes anymore like in the previous version. 
I tried the 1.10.17 version out and these problems are gone (except the missing engine sound) . im not sure what i am doing wrong here

**Comment by RadonSound** [comment]
ok.. i just noticed why the 1.10.17 version doesnt work anymore =D
well then..i guess to take some more time for the new project

**Comment by Uchuujin01** [comment]
Just a tip: if you don't hear something, for example music, try to find out in what bank it is placed. Then, ensure you placed this bank in mod/ folder. And event contains the sound asset (music events are empty by default).

Gun fie can be heard because of the reverb bus, maybe. I'm unable to repeat your problem with volumes for now (
