### ISSUE TITLE
New event on Kings Of Battle Update

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#251]
Hi @Uchuujin01 

Are there any new engines or weapons in the next update? Artillery?

Thanks in advance
Math

**Comment by Uchuujin01** [comment]
Hello! New sound events has been created only for UH-60 Black Hawk helicopter, they called like other helis but have uh_60 suffix, instead of, for example, uh_1.

**Comment by IWSM** [comment]
> Hello! New sound events has been created only for UH-60 Black Hawk helicopter, they called like other helis but have uh_60 suffix, instead of, for example, uh_1.

Hi, ok thanks. No new weapons for this?

**Comment by Uchuujin01** [comment]
> > Hello! New sound events has been created only for UH-60 Black Hawk helicopter, they called like other helis but have uh_60 suffix, instead of, for example, uh_1.
> 
> Hi, ok thanks. No new weapons for this?

Yes, no new weapon sound events.
