### ISSUE TITLE
Custom Radio Clicks Not Triggering

### ISSUE THREAD

**Issue by Yunguy1** [GaijinEntertainment/fmod_studio_warthunder_for_modders#254]
Good day.

Radio clicks event appears to be connected to the masterbank files rather than aircraft_gui now, resulting in sound mods unable to isolate/utilize custom radio clicks UNLESS the masterbank file is utilized.

**Comment by Uchuujin01** [comment]
Hello! For now, in vanilla radio noises moved to tanks_effects_radio.bank, tanks_effects_radio.assets.bank banks.
