### ISSUE TITLE
When is the kings of battle file updated? kings of battle?

### ISSUE THREAD

**Issue by RustyFinger00** [GaijinEntertainment/fmod_studio_warthunder_for_modders#256]
Previously created crew voices do not work after the Kings of Battle update. When is the kings of battle file updated?

**Comment by Uchuujin01** [comment]
Hello! There are almost no changes in project in Kings of Battle update. Only one change regarding to crew voices, I moved radio noise sounds to the separate bank, tanks_effects_radio.bank, tanks_effects_radio.assets.bank.

**Comment by Uchuujin01** [comment]
Do you use your own masterbank files?

**Comment by RustyFinger00** [comment]
Thank you for your hard work and reply.

This is a mod I created. It worked fine until the previous version.
https://live.warthunder.com/post/1084521/en/
But it doesn't work now.

The master bank file uses the War Thunder default master bank and does not use the master bank created while building crew voices. This is because different sounds are not output properly when using a newly built master bank.

The crew work was also produced while preserving the sound file and name format without folder conversion, and the previously created builds worked normally in each version or had no problems in later versions.

If only the bank for radio noise was fixed, the crew should sound normally, but I am curious as to why it does not. It appears that I am not the only one experiencing this problem, and other crew mod makers are also experiencing this problem. This can be predicted by looking at the fact that Crew Sound has not been updated in War Thunder Live since Kings of Battle.

Quite a few people are waiting for my mod and want to use it, so I want to solve this problem quickly.

i need your help.

**Comment by RustyFinger00** [comment]
> Do you use your own masterbank files?

It may be difficult, but I would appreciate it if you updated it with the King of Battle file. I would like to ask because I think it will work normally if I build it with a new version.

**Comment by RustyFinger00** [comment]
> Do you use your own masterbank files?

Thank you for your hard work and reply.

This is a mod I created. It worked fine until the previous version.
https://live.warthunder.com/post/1084521/en/
But it doesn't work now.

The master bank file uses the War Thunder default master bank and does not use the master bank created while building crew voices. This is because different sounds are not output properly when using a newly built master bank.

The crew work was also produced while preserving the sound file and name format without folder conversion, and the previously created builds worked normally in each version or had no problems in later versions.

If only the bank for radio noise was fixed, the crew should sound normally, but I am curious as to why it does not. It appears that I am not the only one experiencing this problem, and other crew mod makers are also experiencing this problem. This can be predicted by looking at the fact that Crew Sound has not been updated in War Thunder Live since Kings of Battle.

Quite a few people are waiting for my mod and want to use it, so I want to solve this problem quickly.

i need your help.

**Comment by godhand2** [comment]
> > Do you use your own masterbank files?
> 
> Thank you for your hard work and reply.
> 
> This is a mod I created. It worked fine until the previous version. https://live.warthunder.com/post/1084521/en/ But it doesn't work now.
> 
> The master bank file uses the War Thunder default master bank and does not use the master bank created while building crew voices. This is because different sounds are not output properly when using a newly built master bank.
> 
> The crew work was also produced while preserving the sound file and name format without folder conversion, and the previously created builds worked normally in each version or had no problems in later versions.
> 
> If only the bank for radio noise was fixed, the crew should sound normally, but I am curious as to why it does not. It appears that I am not the only one experiencing this problem, and other crew mod makers are also experiencing this problem. This can be predicted by looking at the fact that Crew Sound has not been updated in War Thunder Live since Kings of Battle.
> 
> Quite a few people are waiting for my mod and want to use it, so I want to solve this problem quickly.
> 
> i need your help.

Hey @RustyFinger00 

I'm also a mod author. After the update we found that something just broke and refuses to load the mod files. At this moment our workaround is to let the users OVERWRITE the assets in the Warthunder sounds folder, then the game loads it properly.

However do be warned replacing assets... I'm not sure if that's going to be a problem on its own.

**Comment by RustyFinger00** [comment]
> > > Do you use your own masterbank files?
> > 
> > 
> > Thank you for your hard work and reply.
> > This is a mod I created. It worked fine until the previous version. https://live.warthunder.com/post/1084521/en/ But it doesn't work now.
> > The master bank file uses the War Thunder default master bank and does not use the master bank created while building crew voices. This is because different sounds are not output properly when using a newly built master bank.
> > The crew work was also produced while preserving the sound file and name format without folder conversion, and the previously created builds worked normally in each version or had no problems in later versions.
> > If only the bank for radio noise was fixed, the crew should sound normally, but I am curious as to why it does not. It appears that I am not the only one experiencing this problem, and other crew mod makers are also experiencing this problem. This can be predicted by looking at the fact that Crew Sound has not been updated in War Thunder Live since Kings of Battle.
> > Quite a few people are waiting for my mod and want to use it, so I want to solve this problem quickly.
> > i need your help.
> 
> Hey @RustyFinger00
> 
> I'm also a mod author. After the update we found that something just broke and refuses to load the mod files. At this moment our workaround is to let the users OVERWRITE the assets in the Warthunder sounds folder, then the game loads it properly.
> 
> However do be warned replacing assets... I'm not sure if that's going to be a problem on its own.

thanks for talking
I think the best option is to just receive the King of Battle update.

I've been waiting for an answer to this for over 2 weeks and now I'm feeling exhausted and unmotivated.

I want faster feedback, but this doesn't seem to be the case, so it's hard to wait.

**Comment by aWolf1x** [comment]
Hi, I was looking into the voice mod creation process and I couldn't quite make the mods work. Like, I've got all the bank files in the mod folder, but then the game doens't use them. Is there some kind of fix or do we just have to wait?

**Comment by godhand2** [comment]
> Hi, I was looking into the voice mod creation process and I couldn't quite make the mods work. Like, I've got all the bank files in the mod folder, but then the game doens't use them. Is there some kind of fix or do we just have to wait?

@aWolf1x Bandage fix is to overwrite the asset in steamapps\common\War Thunder\sound directly and don't care about the "Mod" folder approach. This way the game reads the file normally as it thinks it's a regular game file.

I feel something broke the ability to read mod files in this update and there seems to be no fix?

Do be warned about overwriting the game's asset as we don't know the consequences.

**Comment by RustyFinger00** [comment]
> 자신의 마스터뱅크 파일 사용권?

기본 마스터 뱅크를 사용하든, 제가 생성한 마스터 뱅크를 사용하든 상관없이 크루 보이스가 작동하지 않습니다.
Regardless of whether I use the default master bank or the master bank I created, the crew voice does not work.

**Comment by RustyFinger00** [comment]
> 자신의 마스터뱅크 파일 사용권?

Just upload a new file of yours and the modders will start working with it. That's the fastest way to solve the current problem.

**Comment by KiraboshiKarura** [comment]
I agree. I am creating a mod by just renaming and replacing files, but using a vanilla Master Bank because it will not work if a built Master Bank exists. The mod no longer works because the radio noise file in the Master Bank was changed in this update.
The binocular voice, which is not affected by radio noise, is fully functional, so this radio noise file change is certainly the cause.
Is this a Skill Issue for the Modder?
Not a single voice mod has been upload since Kings of Battle.
I don't understand why they stubbornly refuse to update their files when this problem should be recognized.

**Comment by RustyFinger00** [comment]
I've been waiting so long for your reply.
If you had given me a concise answer sooner, I wouldn't have had to wait for a reply every day.

Still, thank you for telling me.
