### ISSUE TITLE
Sidechain snapshot usage?

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#26]
Hi,
i would like to know what the sidechain-snapshot in explosions, cannon sounds , ... do or what the usage is. 
i still have some trouble to find the option that kinda lowers for example an explosion sound when impact
or like when the shell_whiz in game appears, it lowers the volume of the surroundings. i know it is a bit hard to understand, sorry.
but i really want to disable this because this makes it hard to hear the sounds i added.

**Comment by Uchuujin01** [comment]
> Hi,
> i would like to know what the sidechain-snapshot in explosions, cannon sounds , ... do or what the usage is.
> i still have some trouble to find the option that kinda lowers for example an explosion sound when impact
> or like when the shell_whiz in game appears, it lowers the volume of the surroundings. i know it is a bit hard to understand, sorry.
> but i really want to disable this because this makes it hard to hear the sounds i added.

Hello! If I understand you right, you can just disable or delete snapshot layers (red coloured media containers) in weapon sound events.

**Comment by RadonSound** [comment]
Ok i will try . So these snapshot layers do causing these effects i mentioned in the last few sentences?

**Comment by Uchuujin01** [comment]
> Ok i will try . So these snapshot layers do causing these effects i mentioned in the last few sentences?

You can check it by yourself, just look at snapshot, it affects on some VCA groups, containing some sound events.

**Comment by RadonSound** [comment]
yep.. seems like the snapshot layers are causing this effect.. i disabled them and the result is perfect now! thank you :)
