### ISSUE TITLE
HSTVL engine

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#260]
Hi @Uchuujin01 

after some research, it turns out that the gas turbine used on the HSTVL will look more like the T-80 but absolutely not the M1 Abrams. is it possible in the next update to switch the engine sound of the HST VL to the sound of the T-80 instead of the Abrams. which would make it more coherent and more realistic and would make the Abrams unique as it should be.

Thanks in advance
Mathieu

**Comment by Uchuujin01** [comment]
Hello! I'll investigate this question, maybe we need a separate sound events if this vehicle should sound unique and it's popular.

**Comment by IWSM** [comment]
> Hello! I'll investigate this question, maybe we need a separate sound events if this vehicle should sound unique and it's popular.

Hi, Ok thanks
