### ISSUE TITLE
Rip Air stuttering

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#266]
Hi @Uchuujin01 sorry for ping,

You have fix this? https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/issues/238

**Comment by Uchuujin01** [comment]
Hello, yes, this issue was fixed quite long ago, and since then, no problem was noticed by me or players.

**Comment by FenixAlfa159** [comment]
https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/59125336/ae19e4f9-aa68-4f9a-9e87-86e6726e2595

This is a video of today, my mod folder is empty. Yet, there are some situations where you hear some problems with jet engines stuttering quite a bit

**Comment by Uchuujin01** [comment]
> War.Thunder.2023.12.20.-.17.27.11.04_H.264.mp4 
> This is a video of today, my mod folder is empty. Yet, there are some situations where you hear some problems with jet engines stuttering quite a bit
This is normal, it is not that kind of stuttering we are talking about. You are flying behind enemy and its engine is jumping right in front of you. This is intended.

**Comment by FenixAlfa159** [comment]
> > War.Thunder.2023.12.20.-.17.27.11.04_H.264.mp4
> > This is a video of today, my mod folder is empty. Yet, there are some situations where you hear some problems with jet engines stuttering quite a bit
> 
> This is normal, it is not that kind of stuttering we are talking about. You are flying behind enemy and its engine is jumping right in front of you. This is intended.

Understood! Thanks for the answer.

**Comment by RCSMOD** [comment]
> > War.Thunder.2023.12.20.-.17.27.11.04_H.264.mp4
> > This is a video of today, my mod folder is empty. Yet, there are some situations where you hear some problems with jet engines stuttering quite a bit
> 
> This is normal, it is not that kind of stuttering we are talking about. You are flying behind enemy and its engine is jumping right in front of you. This is intended.

In the end it's still very unpleasant to listen to.
