### ISSUE TITLE
Steam Audio

### ISSUE THREAD

**Issue by RCSMOD** [GaijinEntertainment/fmod_studio_warthunder_for_modders#269]
![image_2023-12-21_125520685](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/136203781/65fbfd84-02bf-4021-ae1f-a233d5dfc713)

Any possibilities to add this plugin to Fmod for better spacialization?
It's a free plugin, @Uchuujin01

**Comment by Uchuujin01** [comment]
No, it is impossible. Mainly because WT is a multiplatform game. And, there are too many issues because many players use specific spatializers with their multichannel headphones.

**Comment by RCSMOD** [comment]
> No, it is impossible. Mainly because WT is a multiplatform game. And, there are too many issues because many players use specific spatializers with their multichannel headphones.

Ok, thanks for the answer! I thought about it too, but I just wanted to confirm with you.
