### ISSUE TITLE
BUG (rocket passby) with flare trigger

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#270]
Hi @Uchuujin01 

I found a bug when you launch the flare very close, it triggers the **rocket_passby event** for 4 or 5 loop .

I record for you.

https://youtu.be/_6W5UgdvY40

**Comment by OXEPU3M** [comment]
Now some _ai smoke grenades do same effect.
It is extremely weird when Chally's smokes whistle like rocket.

**Comment by Uchuujin01** [comment]
This issue was already fixed some weeks ago.

**Comment by IWSM** [comment]
ok
