### ISSUE TITLE
[QUESTION] Разница звуков перезарядки в проекте и в игре.

### ISSUE THREAD

**Issue by ValbertonHere** [GaijinEntertainment/fmod_studio_warthunder_for_modders#271]
Собственно, вопрос в заголовке.
Может, какой-то снапшот/другая хренотень отвечает за подмешивание доп. эффектов в ивент?

**Comment by OXEPU3M** [comment]
В чём, собственно, разница?

**Comment by ValbertonHere** [comment]
> В чём, собственно, разница?

[Показываю наглядно.](https://youtu.be/WBpUHTuTjW4?si=AxpFeXDAiWihQtx6)

**Comment by OXEPU3M** [comment]
Этот танк использует другой ивент.

**Comment by ValbertonHere** [comment]
Какой же, ни один из ивентов не соответствует по звучанию.

**Comment by Uchuujin01** [comment]
> Собственно, вопрос в заголовке. Может, какой-то снапшот/другая хренотень отвечает за подмешивание доп. эффектов в ивент?
Нет ниакой разницы в ивентах перезарядки в игре и в проекте, это 100%.

**Comment by ValbertonHere** [comment]
> Нет ниакой разницы в ивентах перезарядки в игре и в проекте, это 100%.

Тогда какой ивент теперь отвечает за перезарядку, если не этот?

**Comment by ValbertonHere** [comment]
> Каково точное наименование танка?

Т-43, вроде.

**Comment by Uchuujin01** [comment]
> > Каково точное наименование танка?
> 
> Т-43, вроде.

Такого танка в игре нет. Но в любом случае, это ивент reload_cannon_heavy. Вообще, не так уж и велик выбор перезарядок.

**Comment by ValbertonHere** [comment]
> Но в любом случае, это ивент reload_cannon_heavy. Вообще, не так уж и велик выбор перезарядок.

Слышу сходства, но туда еще что-то подмешивается. В конце особенно слышно. А что именно?

**Comment by Uchuujin01** [comment]
Нет, там более ничего нет, вероятно что то постороннее накладывается и создает такой эффект.

**Comment by ValbertonHere** [comment]
> > Собственно, вопрос в заголовке. Может, какой-то снапшот/другая хренотень отвечает за подмешивание доп. эффектов в ивент?
> 
> Нет ниакой разницы в ивентах перезарядки в игре и в проекте, это 100%.

Антон, кажется вы заврались. Разница [на лицо](https://drive.google.com/drive/folders/1IOv4SzohbCbKrQa8eNAnM7-aZri8nW3N?usp=sharing).
