### ISSUE TITLE
"dialogs_radio_chat" use build file & sound options problem

### ISSUE THREAD

**Issue by RustyFinger00** [GaijinEntertainment/fmod_studio_warthunder_for_modders#273]
hello~ I need your help.

dialogs_chat_ko.assets & dialogs_chat_ko Applying the build file
It doesn't work in game options, but works in the crew country.

Other crew sounds and radio voices are output according to the game options, but only the radiochat voice comes out in the crew country settings. I am curious how to change the route.

I want is for the RadioChat voice to be played when a game option is selected.

![shot 2024 01 14 10 49 58](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/137658955/556b8927-c13e-44b4-a2e6-70cc99263fae)

**Comment by Uchuujin01** [comment]
How do you test it, describe please? I just checked, radio chat working as intended, it depends on game options or crew country setting.

**Comment by RustyFinger00** [comment]
> 어떻게 테스트하나요? 설명해주세요. 방금 확인해 보니 라디오 채팅이 의도한 대로 작동하고 있습니다. 게임 옵션이나 승무원 국가 설정에 따라 다릅니다.

I changed the English audio to Korean audio and changed the file name after building.

English files with only the audio changed work fine, but if you change the file name to match the Korean settings, it will not work properly.
