### ISSUE TITLE
problem on modding "action music"

### ISSUE THREAD

**Issue by yeapy2** [GaijinEntertainment/fmod_studio_warthunder_for_modders#275]
i was making sound mod for action music in Fmod,but i got a problem
i did the same thing on “aircraft/music/top_tier/aircraft_action”
“aircraft/music/top_tier/tank_action” and other file like “action_01” and “tanks_action_01…etc”
top tier are prefect working,but those non top tier file just dont work(they dont play anything)
and,"action_cs" working too

**Comment by OXEPU3M** [comment]
Top tier is for 8.0+ br
