### ISSUE TITLE
Why inverted challenger/chieftain engine??

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#276]
@Uchuujin01 

On your latest update, you have inverted challenger event and chieftain.

Now, challenger use chieftain event and chieftain use challenger event. WHY? 
I don't understand

this makes no sense yet broken our mod😢

**Comment by RCSMOD** [comment]
Yeah, I agree. I don't understand the thought process behind this decision. It makes no sense to me.

**Comment by Uchuujin01** [comment]
Hello! It makes sense, because it turned out I make Challenger sounds on Chieftain references, so, Challenger actually is a Chieftain. So I made new Challenger sounds and moved it's old sounds to Chieftain.

**Comment by Uchuujin01** [comment]
> this makes no sense yet broken our mod

Unfortunately, almost every change in sound project brakes sound mods. But this shouldn't stop game sound evolving.
