### ISSUE TITLE
Requiest

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#277]
Good morning,

Gaijin has decided to open up the possibility of sound modding and it is a real opportunity. Today you have several real big, very complex mods that take a lot of time and which have a large, ever more demanding fan base. 

There are many bugs or questions that we post here and which remain unanswered for several weeks as at the moment, it has been 1 month since you have not responded. We therefore find ourselves without being able to provide a solution to our mods or without being able to update them when they are broken again because you have released an update like now with the changing recents.

Can we find a faster and more efficient way to communicate with each other? This would be beneficial for everyone because we regularly provide you with very precise bug reports as well, this helps you in a certain way.

We know that we have to redo our entire work with each major update because the system is poorly designed, but we can certainly find a solution to communicate without waiting 1 month between each response.

Thanks in advance
Best regard
Matthieu (IWSM sound mod)

**Comment by Uchuujin01** [comment]
It is a reasonable proposition, I discuss it with my management now.

**Comment by Uchuujin01** [comment]
@IWSM do you have an access to WT Sound Mods discord server?

**Comment by IWSM** [comment]
> @IWSM do you have an access to WT Sound Mods discord server?

NO

**Comment by Uchuujin01** [comment]
We decided me to join this server. Can you join it too? There are quite many modders already, so I will be able to answer some questions there.

**Comment by IWSM** [comment]
> Nous avons décidé que je rejoignais ce serveur. Pouvez-vous vous y joindre vous ? Il y a déjà pas mal de moddeurs, donc je vais pouvoir répondre à quelques questions là-bas.

I'm going to try, but I don't get along very well with some other modders unfortunately, I have my own community discord for IWSM. I send you a private message

**Comment by IWSM** [comment]
I join the discord, just need a moddeur role
