### ISSUE TITLE
objet 292 canon

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#278]
@Uchuujin01 

Hi,  what event name does the new canon have please?

Are there any other new events?

Thx
Matthieu

**Comment by Uchuujin01** [comment]
152mm_lp83, 152mm_lp83_interior, 152mm_lp83_ai
There will be some more sound events but later, for example bmd4 engine (ground/engines/bmd4), and 2a70 cannon (bmp2, bmp3, bmd4), 100mm_2a70 100mm_2a70_interior, 100mm_2a70_ai.
