### ISSUE TITLE
Nation parameter

### ISSUE THREAD

**Issue by IWSM** [GaijinEntertainment/fmod_studio_warthunder_for_modders#279]
@Uchuujin01 

HI, is it possible to get a nation parameter on Fmod?
I search to put a condition on an event depending on the nation used on exemple T90a engine. this engine is used by RU and by bishma on UK. 
this would allow a lot of possibilities in the design of mods very easily

Thanks in advance
Matthieu

**Comment by Uchuujin01** [comment]
I don't understand how it would be useful, sounds quite odd.

**Comment by IWSM** [comment]
> I don't understand how it would be useful, sounds quite odd.

for example, I want to add radio communication lines internally to the turret. But for example on the t90, t72 or leopard 2, the engine events are used on several nations, so I cannot use Russian voices in the t72 which will also be used in Swedish. Do you understand? The problem is identical on planes. I could also separate the sound of RH120 cannon firing between the Leclerc and the Abrams which are radically different. These are only examples. Is it complicated for you to create such a parameter?
