### ISSUE TITLE
New Changelog Sounds

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#28]
A new Changelog dropped with some new sounds with some new shellwhiz effects that bypasses my tanks_effects.bank file , i guess that means that the latest project is outdated. Do i have to do everything i did again when the new project drop? As far as i got it, only the tanks_effects are affected, so can i just drag'ndrop the rest i did so far (guns, aircraft,...) ? or can i just combine the new tanks_effects.bank in the mod folder with the other banks i did so far?

Thanks for any help or info    o7

**Comment by Uchuujin01** [comment]
> A new Changelog dropped with some new sounds with some new shellwhiz effects that bypasses my tanks_effects.bank file , i guess that means that the latest project is outdated. Do i have to do everything i did again when the new project drop? As far as i got it, only the tanks_effects are affected, so can i just drag'ndrop the rest i did so far (guns, aircraft,...) ? or can i just combine the new tanks_effects.bank in the mod folder with the other banks i did so far?
> 
> Thanks for any help or info o7

Hello! I'm sorry for the late answer ( Actually, there is no new sound events added, only sound assets changed for cound event aircraft/effects/bullets_passby. This is the only event for all bypasses, please, check it.

**Comment by RadonSound** [comment]
Oh so the soundevent aircraft/effects/bullets_passby is for groundforces (tanks shellwhiz) aswell?

**Comment by Uchuujin01** [comment]
> Oh so the soundevent aircraft/effects/bullets_passby is for groundforces (tanks shellwhiz) aswell?

Sure, and for the naval forces too.

**Comment by RadonSound** [comment]
Ok 👍i will try it soon this day

**Comment by RadonSound** [comment]
![Screenshot (195)](https://user-images.githubusercontent.com/67481432/89164103-eb5fc200-d576-11ea-9b59-158b8f946e67.png)

Do i have to check this (Assign to Bank > aircraft > aircraft_effects ) ? because without i doesnt show up in the aircraft_effects bank.
If yes, it wasnt checked in default

**Comment by Uchuujin01** [comment]
> ![Screenshot (195)](https://user-images.githubusercontent.com/67481432/89164103-eb5fc200-d576-11ea-9b59-158b8f946e67.png)
> 
> Do i have to check this (Assign to Bank > aircraft > aircraft_effects ) ? because without i doesnt show up in the aircraft_effects bank.
> If yes, it wasnt checked in default

No, it's already checked in hangar.bank.

**Comment by RadonSound** [comment]
Ok thanks i seems working now with the ingame shellwhiz effects but i need to look on the hangar.bank because as soon as i use it i dont have ingame battle music anymore. is there a reason for that?

**Comment by RadonSound** [comment]
Ok i found the solution 👍
Thank you, you saved my day or month!
