### ISSUE TITLE
can we create obj.292's LP83 sound event currently?

### ISSUE THREAD

**Issue by YatogamiMai** [GaijinEntertainment/fmod_studio_warthunder_for_modders#281]
many people don't want wait too long for next update of the pack, can we create it use current Fmod project?
if can, how to do it

**Comment by IWSM** [comment]
> many people don't want wait too long for next update of the pack, can we create it use current Fmod project?
> 
> if can, how to do it

yes you can, I have already done it

**Comment by Uchuujin01** [comment]
You can create cannon sound events 152mm_lp83 with corresponding suffixes (_ai, _interior).

**Comment by YatogamiMai** [comment]
> You can create cannon sound events 152mm_lp83 with corresponding suffixes (_ai, _interior).
done,I copy-paste the ml20 events rename 152mm_lp83 ,but it shows me unassigned
![20240219224333](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/137425848/08012c47-28db-491f-adc1-8a5b733948d4)
anything I should do to let the game identify the new events I created?

**Comment by Uchuujin01** [comment]
Sure, you need to assign them in tanks_weapons sound bank.

**Comment by YatogamiMai** [comment]
> Sure, you need to assign them in tanks_weapons sound bank.

how to complete this step? or it need another tool?

**Comment by Uchuujin01** [comment]
Just press the right mouse button on those sound events and pick "Assign to Bank" option.

**Comment by YatogamiMai** [comment]
> Just press the right mouse button on those sound events and pick "Assign to Bank" option.

been solved！very thanks your help!
