### ISSUE TITLE
Есть ли возможность посмотреть какие звуковые ивенты используются техникой?

### ISSUE THREAD

**Issue by dldev32** [GaijinEntertainment/fmod_studio_warthunder_for_modders#282]
Давно интересовал данный вопрос, так как, к примеру, орудия используют не только сам звуковой ивент выстрела, но также и доп. эффекты, но нюанс заключается в том, что неизвестно какие именно звуковые ивенты доп. эффектов отвечают за конкретную технику.

**Comment by Uchuujin01** [comment]
Я не очень понял, что имеется ввиду по "доп. эффектами"? Когда происходит выстрел, звучит только один звуковой ивент выстрела.

**Comment by dldev32** [comment]
Не верю. Достаточно проверить как звучит выстрел в игре и в студии.

**Comment by Uchuujin01** [comment]
Ваше право ) В таком случае, вам не имеет смысла задавать тут вопросы.
