### ISSUE TITLE
Create mode/ need help (#unassigned problem)

### ISSUE THREAD

**Issue by Jazzsskier** [GaijinEntertainment/fmod_studio_warthunder_for_modders#283]
Greetings to all, there was a problem with the sounds, the fact is that I do not know why events such as voice_message_armor_not_pierce_v3 are not assigned to the corresponding banks(#unassigned), as a result of which my sounds cannot be saved in them. I tried to link them to crew_dialogs_ground_new (bank), but it turned out to be to no avail, while the sounds from med, high, low work perfectly. The translation is done through Google Translator, I apologize for the crooked English. Thank you in advance for your help.
![GTYs5VRpjWI](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/161159624/087baf60-7fa0-41bb-b7d0-ec6c8393bd71)

**Comment by OXEPU3M** [comment]
Because there are legacy of ancient times, or better say, useless garbage now.

**Comment by Jazzsskier** [comment]
> Because there are legacy of ancient times, or better say, useless garbage now.

I get it, thanks for the answer. But then what events are responsible for damage, destruction, and failure to hit the target? Everything is too confusing in this version, and the guides on this topic are 3 years old.

**Comment by OXEPU3M** [comment]
Find _hit events.
And ''failure'' is no more

**Comment by Jazzsskier** [comment]
> Найдите _hit события. И «неудачи» больше нет

Thank you
