### ISSUE TITLE
how to create bank? dialogs_chat_ko ?

### ISSUE THREAD

**Issue by RustyFinger00** [GaijinEntertainment/fmod_studio_warthunder_for_modders#284]
I want to build in Korean, but the items do not contain Korean.

So, I am working on the English file in Korean and changing the file name.

It seems that the radio part does not work properly because of this method.

I would like to know how to officially create and add Korean.

![스크린샷 2024-02-27 195537](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/137658955/e2883b57-0680-45e6-88b0-84d4b0522daf)

**Comment by Uchuujin01** [comment]
You need to create a bank named dialogs_chat_ko, and place your Korean events in it.
