### ISSUE TITLE
help me~ I need a bank 

### ISSUE THREAD

**Issue by RustyFinger00** [GaijinEntertainment/fmod_studio_warthunder_for_modders#290]
![스크린샷 2024-05-07 085620](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/assets/137658955/9e11b387-2c4d-4b93-99b3-f76c76bb5331)
Hello, thank you for your hard work~

I came to ask you a favor.
I tried to create a Radiochet bank file, but I'm not good at making it and I'm not good at understanding the structure, so...

Could it be possible to add radiochat bank files from other countries as before?

I didn't touch anything else and only worked on the sound file, so I think the mod will work smoothly as long as I have the Korean bank file.

Please~

**Comment by IWSM** [comment]
Need you create. Copy/paste US bank and rename. Change with your korean files.

**Comment by RustyFinger00** [comment]
> Need you create. Copy/paste dialogs_chat_US bank and rename. Change with your korean files.

Thanks for the reply
Copy and paste doesn't work on that screen?
Could you please tell me how to copy and paste?

**Comment by RustyFinger00** [comment]
> Need you create. Copy/paste dialogs_chat_US bank and rename. Change with your korean files.

Thanks for the reply
Copy and paste doesn't work on that screen?
Could you please tell me how to copy and paste?

**Comment by IWSM** [comment]
> T

Clic on dialogs_us and diplicate. Rename the duplicate for your usage. After, recreate folder on asset folder
