### ISSUE TITLE
Seek and Destroy mod folder recognition problem.

### ISSUE THREAD

**Issue by RustyFinger00** [GaijinEntertainment/fmod_studio_warthunder_for_modders#294]
Hello~

I received this update file and applied the crew voices.

However, it does not work as before because there is a folder recognition problem.

When I apply the sound file created with the mod to the original sound folder, the sound changes.

I think there may be a folder recognition problem like before.

Please confirm.

**Comment by RustyFinger00** [comment]
I received a new update, but it still doesn't seem to be able to read the mod folder.

**Comment by Uchuujin01** [comment]
Hello! Sounds mods temporarily disabled, they will work again soon, sorry for the inconvenience.

**Comment by RustyFinger00** [comment]
ok thx
