### ISSUE TITLE
More info about current issue with all sound mods 

### ISSUE THREAD

**Issue by Collin146** [GaijinEntertainment/fmod_studio_warthunder_for_modders#296]
Hello, I hope all is well. I have some questions regarding the current situation with sound mods.

As it currently stands, sound mods are still disabled by default due to the issues that came with the latest major update that caused some players to crash. I understand that you guys are still working on resolving this issue, however, I was hoping to be able to get some more info here. 

When a fix gets inevitably found and pushed, will this also include another update to this project? Or am I able to use this current project version to update my mod without having to update it again later?

**Comment by AlealactaEst** [comment]
same here, i wasted a whole day bc of it :<
probably not fault by fmod modder idk i just hope its gonna be fixed soon

**Comment by siriphong065** [comment]
same, I can't see a build folder when I build crew dialogs ground.

**Comment by Uchuujin01** [comment]
@Collin146 Hello! Sound mods will work again very soon, no worries. I can't say more but you don't have to worry.

**Comment by Collin146** [comment]
Thanks for the hard work @Uchuujin01! Does this mean I can use this current version of this project or will there be another update to this when sound mods are enabled again?

**Comment by pixtolero** [comment]
> Thanks for the hard work @Uchuujin01! Does this mean I can use this current version of this project or will there be another update to this when sound mods are enabled again?

AFAIK sound mods are disabled directly in game code, no relation with fmod project

**Comment by Collin146** [comment]
> AFAIK sound mods are disabled directly in game code, no relation with fmod project see here [gszabi99/War-Thunder-Datamine@88db306](https://github.com/gszabi99/War-Thunder-Datamine/commit/88db306a4d48da2c116d39bd94342488846d45bd)
I did see that. Though, my question is more related to the actual issue. The mods were disabled due to players crashing and experiencing other issues from my understanding. I'm trying to see if the fix that Gaijin is going to implement will also reflect onto this project and cause it to be updated again. 

I wanted to know this since I'd rather wait with updating my mod instead of having to update it twice.

**Comment by Collin146** [comment]
Answered by Anton, current FMOD project update can be used to update mods in the meantime until sound mods are enabled again. Marking as solved.
