### ISSUE TITLE
Update 1.101

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#30]
Hello!
The new Update 1.101 "Raining Fire" is coming soon™
According to the Changelogs from the Devserver there a new sound effects etc.
will this affect my recent soundmod? i've done so much now and i dont really want to do everything all over again.

**Comment by Uchuujin01** [comment]
Hello! There are no major changes in the project, your mod will work fine with new 1.101. The only thing that you could add - new reverb snapshots, and new Return buses with reverbs. I'll update project asap so you will see.
