### ISSUE TITLE
Questions about explosions

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#32]
Hello, I kinda got stuck there, digging through plane explosions sub-folder and a little bit confused by event names and it's purposes.
![image](https://user-images.githubusercontent.com/63158562/92320307-28f9b400-f029-11ea-956e-62441ee9b837.png)
While bomb explosion pretty obvious, the rest of this list puzzling me.
Does explosion_ground uses rockets and small explosive arms? (There's also identical event in tank sub-folder hmm)
What type of bomb/missile heavy_explosion uses?
"_ground" and "_water" pretty obvious too, but what does "building" means? Is it working in game?
Events with "..._unit"  probably meant to use of explosion of ground targets in air rb/ab?
Would be great to see better event names to match correct types of ammunition (like bomb_500lb_explosion, small_rocket_explosion etc.) Because not really sure if half of it working in-game.

I also tried to edit plane explosions/damage effects and there's questions too.
![image](https://user-images.githubusercontent.com/63158562/92320698-087f2900-f02c-11ea-8501-a605249b15d9.png)
Most of this list is working for only player driven aircraft? Tried to edit, so enemy/ally aircraft will fall with couple of sounds, but discovered that only plane_wreck_explosion only works here, but one thing though, it shares with ATGM tank hit sound 🤔 

Most of these sound i never heard in game, so i could be wrong if same good half part of this list is not working.
Like plane_broken intended for frame destruction sounds? Or what's the difference between plane_explosion and wreck_explosion? Same with witch just plane_wreck. Most of it works for player-only aircraft, so there's no way to check it for ai/enemy/allies

Thanks in advance! :)

**Comment by Uchuujin01** [comment]
Hello!

> Does explosion_ground uses rockets and small explosive arms?

Yes, but only small explosive arms, not rockets (they uses art_explosion_ground)

> What type of bomb/missile heavy_explosion uses

I'm not sure about all weapon, but some naval rockets and bomb guns uses it.

> "_ground" and "_water" pretty obvious too, but what does "building" means? Is it working in game?

Yes, it works when building takes a hit.

> Events with "..._unit" probably meant to use of explosion of ground targets in air rb/ab?

Yes )

> Would be great to see better event names to match correct types of ammunition (like bomb_500lb_explosion, small_rocket_explosion etc.) Because not really sure if half of it working in-game.

Agree, but it's not so easy job, unfortunately. I hope we'll do it someday.

>  plane_wreck_explosion only works here, but one thing though, it shares with ATGM tank hit sound 

I'm pretty sure that ATGM explosion uses "wreck_explosion" sound event. "plane_wreck_explosion" - we don't have such sound event.

> Most of these sound i never heard in game, so i could be wrong if same good half part of this list is not working.

I'm not sure what is on your screenshot, but we dont have most of it's names in project. I just opene it, and, here

![image](https://user-images.githubusercontent.com/26138230/92385346-668a3a00-f11a-11ea-8c5d-245e677c0e80.png)

**Comment by 787992** [comment]
Ok thanks for clarifying with bomb
> I'm not sure what is on your screenshot, but we dont have most of it's names in project. I just opene it, and, here

AAAA, that's just me being dumb, i opened old project where i did re-organization with names for better understanding.
![image](https://user-images.githubusercontent.com/63158562/92390127-faf89a80-f122-11ea-9ea7-513f924c9d34.png)
Here's grouped same events mentioned earlier. But still no idea why ATGM explosion uses same event as plane crash, while everything is great about player driver ariraft explosions/impacts, enemy/ally airraft feels underpowered here in terms of sounds.

Because of many new explosion sounds, my version has outdated ones, so i can't compare it with actual in-game sounds. Probably there's more events regarding damage/explosion in current state? Or some sneaky way?

**Comment by Uchuujin01** [comment]
> Here's grouped same events mentioned earlier. But still no idea why ATGM explosion uses same event as plane crash, while everything is great about player driver ariraft explosions/impacts, enemy/ally airraft feels underpowered here in terms of sounds.
> 
> Because of many new explosion sounds, my version has outdated ones, so i can't compare it with actual in-game sounds. Probably there's more events regarding damage/explosion in current state? Or some sneaky way?

It's in our plans to improve an aircraft sounds in near future. Agree, it is not always clear how sounds work and arranged in project. I hope we'll fix it. There is always not enough time for refactoring )

**Comment by 787992** [comment]
> It's in our plans to improve an aircraft sounds in near future. Agree, it is not always clear how sounds work and arranged in project. I hope we'll fix it. There is always not enough time for refactoring )

Ah, true. Completely understandable, that you constantly imroving things. but I mean these sounds could use also other planes not only player after crash, I can totally deal with compromise of having just one sound, but it shares with different action that requires much sharper and shorter explosion sound.

**Comment by Uchuujin01** [comment]
> but it shares with different action that requires much sharper and shorter explosion sound.

True. There is another point to share some sounds between several actions - a very restricted amount of memory. But I think we'll rework it someday.
