### ISSUE TITLE
Aircraft Hit sounds are missing 

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#33]
Hello,

I've started to work on Plane sounds ( only changed some engine and gun sounds so far ) 
and i noticed that the Hit sounds (when you getting hit in a plane in third person view and cockpit view)
are completely muted. The sounds who should played there are these so far as i remember:
bullet_hit_outside_03_01
bullet_hit_outside_03_02
bullet_hit_outside_03_03
bullet_hit_outside_03_04
bullet_hit_outside_03_05
bullet_hit_outside_03_06

after searching for a while, i guessing the effects i mean are these 
![Screenshot (268)](https://user-images.githubusercontent.com/67481432/92341234-5c861e00-f0bd-11ea-8158-9509c810bacf.png)
![Screenshot (269)](https://user-images.githubusercontent.com/67481432/92341236-5d1eb480-f0bd-11ea-90fc-ae55b330338d.png)

but no matter how loud i set them i cant hear them when i getting hit by other planes. they only appear when im on fire.

![Screenshot (270)](https://user-images.githubusercontent.com/67481432/92341404-e1713780-f0bd-11ea-80e5-13c6fbc2dd56.png)
i only build up these banks. do i miss something that the hit sounds are not there?

thanks for any help,

**Comment by Uchuujin01** [comment]
Hello! I'll check it in game, maybe something is broken. Do you hear hit sounds without your mod?

**Comment by RadonSound** [comment]
I removed my banks and removed the command in the config.blk (enable_mod:b=yes) . And i still dont hear the hit sounds. i put all volumes in game to maximum but when i getting hit, there is no sound playing for that

**Comment by Uchuujin01** [comment]
Thank you for the report, it seems something broken, we'll fix it.

**Comment by RadonSound** [comment]
Saw the Changelog today so i tested with the mod right away.. its all working now! thank you for fixing ❤

**Comment by Uchuujin01** [comment]
It's because of your report, thank you for help )
