### ISSUE TITLE
1.101 ground sounds

### ISSUE THREAD

**Issue by YamashiroKai** [GaijinEntertainment/fmod_studio_warthunder_for_modders#34]
Hello, 

Were the sound event names changed for the 20mm Vulcan (M163) and Japanese 120s? They no longer work with the last version of the project since the new patch.

**Comment by Uchuujin01** [comment]
Hello! Here are actual weapon names: 20mm_m61, 120mm_jspg. We didn't changed them, as I remember.

**Comment by ChoukaiKaiNi** [comment]
I see. 120mm_jspg seems to be a new event because it doesn't exist in my sound project at all.

I'd also like to know if any of the 20mm naval events were changed as well? As some (not all) no longer play in battle yet they are identical to others that do work.

**Comment by ChoukaiKaiNi** [comment]
I did some testing. I added the 120mm_jspg and it didn't work until I included masterbank.bank and masterbank.strings.bank. This also fixed missing Vulcan and naval 20mm sounds.

Usually us modders removed the masterbank files as it allowed compatibility and the ability to mix various mods together. However when these files are added, mods that change music and voices stop working, for example.

**Comment by Uchuujin01** [comment]
Sure, it is necessary to update project repository. I'll do asap. Unfortunately, sometimes we must slightly change project routing (in fmod mixer window).
