### ISSUE TITLE
Airbattle Kill soundeffect

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#36]
Hello,

with the last patch, a new soundeffect has been added to Airbattles when i shot down another aircraft.
it kinda sound like the effect from naval battles when you press [W] to increase the speed (some sort of "BING")

like here 
https://www.youtube.com/watch?v=-CHZfwxSlsE&feature=youtu.be

Is there any way to mute this effect in the current version? I dont really like this effect 😢

**Comment by Fishy420** [comment]
I don't like the new aircraft kill sound either, gives me naval flashbacks.

**Comment by Uchuujin01** [comment]
Hello! This effect now separated from naval effect (will be in release this week). Naval effect: aircraft/gui/enemy_destr_by_ship. Aircraft effect: aircraft/gui/enemy_destr_by_plane
