### ISSUE TITLE
Track sound modern tank

### ISSUE THREAD

**Issue by MathMilitary** [GaijinEntertainment/fmod_studio_warthunder_for_modders#39]
Hi,
I see the lines sound of the M1A2 and looks a lot like the real modern line. Why not put the same on all modern tanks? It would be much more realistic.

**Comment by Uchuujin01** [comment]
Hello! If I understood you right, we should add new tracks sound events for modern tanks? That makes sence, I agree. Will add it to my to-do list.

**Comment by MathMilitary** [comment]
yes that's the idea! But if it is already possible to assign the sounds of the M1A2 lines to all 10.3 / 10.7 that would be excellent.
I take this opportunity to tell you that you are doing a wonderful job on the sound of the game, so thank you.

**Comment by MathMilitary** [comment]
have you had time to look at these topics. ?
