### ISSUE TITLE
Will this repo add crew chats and music in the future?

### ISSUE THREAD

**Issue by Harinlen** [GaijinEntertainment/fmod_studio_warthunder_for_modders#4]
Hi Gaijin,

Will add or consider to add crew chats and background music to this repo in the future?

Cheers.

P.S.: this is the only online game that I am currently playing. Your team does a really great job!

**Comment by Uchuujin01** [comment]
> Hi Gaijin,
> 
> Will add or consider to add crew chats and background music to this repo in the future?
> 
> Cheers.
> 
> P.S.: this is the only online game that I am currently playing. Your team does a really great job!

Hello! We'll add crew chats eventually. We want to be sure sfx works properly now )
We can't add music, but, it is highly possible we'll add empty music events. So, you will be able to add yours )

PS: Thanks for the kind words! )

**Comment by Vargavinter** [comment]
Yeah, I was downloading and preparing everything to start creating a mod only to read later that crew voices are not included yet.. I just hope it won't take too long :) Glad the ability is here now

**Comment by Harinlen** [comment]
> 
> 
> > Hi Gaijin,
> > Will add or consider to add crew chats and background music to this repo in the future?
> > Cheers.
> > P.S.: this is the only online game that I am currently playing. Your team does a really great job!
> 
> Hello! We'll add crew chats eventually. We want to be sure sfx works properly now )
> We can't add music, but, it is highly possible we'll add empty music events. So, you will be able to add yours )
> 
> PS: Thanks for the kind words! )

That's awesome! Looking forward to close this issue asap.

Cheers! :)
