### ISSUE TITLE
Порядок воспроизведения.

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#41]
Здравствуйте.
•I•
В игре порядок боевого чата строго последователен. Можно ли как-то заставить команды чата звучать одновременно?
Например, команды: "Атакуйте точку *", "Нужна помощь", "Внимание на карту" Будут озвучены в строгом порядке их появления, не перекрываясь. Бывают случаи, когда несколько команд вызываются почти одновременно, и, к примеру, последняя "Внимание на карту."
В таком случае маркер на карте уже перестаёт мигать, а звук только начинается. Критично для некоторых игровых ситуаций.
Можно ли как-то заставить команды чата звучать одновременно?

•II•
Как задаётся приоритет и порядок одновременных событий? (в частности повреждений)
Например, при взрыве фугаса в танке, желательно, чтобы первым говорилось о наводчике, а не о случайном событии.
Спасибо.

**Comment by Uchuujin01** [comment]
Добрый день! Одновременное воспроизведение звуковых ивентов не возможно, к сожалению. Это не вопрос непосредственно звука, а вопрос геймплея, тут я не властен что то менять.

Касательно приоритетов, строго говоря вероятность одновременности событий (до микросекунд) стремится к нулю, всегда есть очередь в порядке поступления. Так что, и воспроизводится все в порядке живой очереди.
