### ISSUE TITLE
Не рабочие ивенты

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#42]
Здравствуйте.
В игре нет озвучания события ранения членов экипажа. (адрес ивента подобно voice_message_commander_contused_v2).
Но в этом наборе их ивенты есть. Более того, есть их рабочие звуковые файлы, и всё это связано вместе. Но оно как и в оригинальной игре не работает.

Также целый набор разных анонсёров направления попаданий типа voice_message_shot_back_v1
Но ни с родными ассетами, ни со своими этот ивент в игре не запускается.
Часа два потратил, чтобы понять, что он просто не рабочий. Зачем в дереве ивентов неактивные разделы?

**Comment by VLBRTN** [comment]
> Здравствуйте.
> В игре нет озвучания события ранения членов экипажа. (адрес ивента подобно voice_message_commander_contused_v2).
> Но в этом наборе их ивенты есть. Более того, есть их рабочие звуковые файлы, и всё это связано вместе. Но оно как и в оригинальной игре не работает.
> 
> Также целый набор разных анонсёров направления попаданий типа voice_message_shot_back_v1
> Но ни с родными ассетами, ни со своими этот ивент в игре не запускается.
> Часа два потратил, чтобы понять, что он просто не рабочий. Зачем в дереве ивентов неактивные раздел?

Кстати, у меня такая же проблема: В бою ивенты некоторые не проигрываются, а именно повреждение некоторых модулей и контузия экипажа, а в повторе это все работает. В чем проблема, @Uchuujin01?

**Comment by VLBRTN** [comment]
В основном, это ивенты у которых был Programmer Instrument и, насколько я помню, в самом свежем апдейте репозитория ссылку на ассеты в ивентах вырезали, верно?

**Comment by Uchuujin01** [comment]
Добрый день! Часть ивентов в игре и правда не используются, она отключена по тем или иным причинам, в зависимости от ситуации.
Но, по поводу контузии экипажа, должно работать, это странно. Вы не могли бы прислать мне clog файл (можно в мою ветку на официальном форуме "обратная связь с разработчиками - вопросы касательно звука", или официальным репортом), созданный после боя в котором есть эта проблема? Навскидку, я слышу время от времени сообщения о контузиях экипажа, да и пользователи не рапортовали об этой проблеме.
