### ISSUE TITLE
Track/wheel sounds depended on surface feature

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#46]
Hello,

Some patche ago you added this neat feature, I want expand it a bit, but faced little problems:

It's about transition between two sound layers concrete/dirt, suppose this is more map related as it works as intended in most cases (transition wise), but lacks of material setups sound wise.
Like most maps made of dirt and sound will ignore road that was placed on dirt.

Let's say Normandy it has diverse materials, with sharp transitions between dirt and concrete.

![image](https://user-images.githubusercontent.com/63158562/100206970-143a0780-2f18-11eb-9b91-32fba10417da.png)

Or Eastern Europe

![image](https://user-images.githubusercontent.com/63158562/100207423-9cb8a800-2f18-11eb-8cc0-a9edaae1727f.png)

Also sometimes transition from concrete to dirt is not working, it just stays on concrete layer (you need to reset sound by looking in sight and back to exterior view)

**Comment by Uchuujin01** [comment]
Hello! Thanks for the information, I'll check this material sound mechanism. Regarding a maps, yes, not all they contain correct meta-data. Hope we'll fix it soon.
