### ISSUE TITLE
Issue maj 26/11 for leclerc sound

### ISSUE THREAD

**Issue by MathMilitary** [GaijinEntertainment/fmod_studio_warthunder_for_modders#47]
hello, following the Leclerc engine update, it has become less realistic. there is now a turbo whistle, but the Leclerc does not have a turbo. the turbine blows regularly with a rather serious sound and does not fluctuate according to the engine speed.
the diesel engine is almost inaudible on the leclerc, only the running gear and the gas turbine can be heard. again, the turbine rattles regularly and does not fluctuate with diesel engine speed. think you can rectify that?

**Comment by Uchuujin01** [comment]
Hello! I'll try to fix it, and add more turbine and less diesel.

**Comment by MathMilitary** [comment]
For your help 😉
https://youtu.be/bEnHqZSf2yg

**Comment by MathMilitary** [comment]
Hi, very nice update today. Is good now.
Big thanks

**Comment by Uchuujin01** [comment]
Thanks to you, for pointing to this issue with Leclerc )
