### ISSUE TITLE
Предложение по отдельному банку для саундтреков

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#48]
Иногда возникают интересные конфузы. Например надо переозвучить некоторые пищалки и сигналы тревоги (например, ракет), но ивенты формируются в банк hangar.
В нём же прячутся саундтреки, что безусловно проблема, так как их в репозитории нет. Пользователи ругаются и всячески негодуют.
А, как вы говорили, существуют трудности с общедоступностью музыки.
Возможно ли как-то в не слишком далеком будущем развести банки саундтреков отдельно, как в ангаре, так и в бою?

**Comment by Uchuujin01** [comment]
Да, обязательно, уже наметил себе, надо бы разделить, и вообще банк hangar хорошо бы растащить по тематическим банкам, а то там сейчас свалка получается.

**Comment by CCCPDriver** [comment]
> Да, обязательно, уже наметил себе, надо бы разделить, и вообще банк hangar хорошо бы растащить по тематическим банкам, а то там сейчас свалка получается.

Полностью поддерживаю. Сам хотел предложить
