### ISSUE TITLE
For leclerc engine real

### ISSUE THREAD

**Issue by MathMilitary** [GaijinEntertainment/fmod_studio_warthunder_for_modders#50]
Hi, for my mod, I use IKV1 engine (load and not load) rpm menu. Is most real compar to STRV121 engine.
Just for your information. 
Stay tuned 💪😎

**Comment by Uchuujin01** [comment]
Hello! Really? My swedish colleagues, who recorded all tanks for us, said that STRV121 is a closest clone of leopard 2.

**Comment by MathMilitary** [comment]
I drive with leclerc in french army, for me the Ikv1 is better

**Comment by Uchuujin01** [comment]
I'm sure your opinion on this question is important, I'll try IKV1 sound assets for Leclerc. Thank you!

**Comment by MathMilitary** [comment]
If you can take the time to listen to the rendering of my mod which is 95% identical to reality here.
https://live.warthunder.com/post/945675/en/

**Comment by Uchuujin01** [comment]
Sure, I will. I must say, recently I was forced to change all diesel turbo charger sounds and turbine sounds, make it more smoother and less realistic. Because of complains on hearing fatigue.

**Comment by MathMilitary** [comment]
I understand 😕🤔
