### ISSUE TITLE
ATGM explosion sounds

### ISSUE THREAD

**Issue by YamashiroKai** [GaijinEntertainment/fmod_studio_warthunder_for_modders#51]
Currently, the sound the ATGM makes when striking any object is the same as that of the wreck_explosion sound in the Aircraft section. These two should be separated.

**Comment by RadonSound** [comment]
Im not sure if this has been already forwarded in this topic https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/issues/49#issuecomment-736375468
(last line in comment)

**Comment by Uchuujin01** [comment]
Hello! Yes, we already discussed this issue. I'll fix it soon.
