### ISSUE TITLE
Ранения экипажа/Crew wounds

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#52]
Если, например, выбивают наводчика:

1.система уведомляет "Наводчик контужен"
2.инициируется скрипт замены "живыми" членами.
3.после замены, скажем, заряжающий берёт на себя полномочия, система выдаёт: "Заряжающий ранен" или и вовсе "Заряжающий потерял сознание".
Это дезориентирует, и кажется, что получил второе попадание.
Возможно ли с помощью данного репозитория убрать ивенты озвучки после замены членов экипажа?

••••
И чтоб два раза не вставать:
Например, ивенты contused или wound имеют версии v1/v2 На что завязана их логика?

**Comment by Uchuujin01** [comment]
Добрый день еще раз ) Я уже ответил развернуто на этот комментарий на форуме, так что тут наверно не имеет смысла дублировать.
