### ISSUE TITLE
How to play the sound

### ISSUE THREAD

**Issue by MathMilitary** [GaijinEntertainment/fmod_studio_warthunder_for_modders#54]
Hi,
I would like to know if it is possible to play the sound only when **load** goes up but not when **load** goes down?

Thanks in advance

**Comment by Uchuujin01** [comment]
Hello! I understand what you trying to do, and, I'm afraid, no, you can't do that. But, I don't think it is necessary, because in our settings WS default keys called "acceleration", so when you press S, it is actually not a brake, it is acceleration.
