### ISSUE TITLE
aircraft_music_ events/bank in old project

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#55]
Hello!
I have a short question.
In the new project there are 2 new music banks [aircraft_music_2.bank] & [aircraft_music_3.bank] . these contains the new music events added in the update "new power" .
However in the older project there is only the main [aircraft_music.bank]

![Screenshot (490)](https://user-images.githubusercontent.com/67481432/102040254-8fcafe00-3dcc-11eb-9bdb-d32829294282.png)                                            🡼
So what i did is created or copy and pasted the new events like  "menu_new"   and  "top_tier\aircraft_action & tank_action"
into the old project events 

![Screenshot (488)](https://user-images.githubusercontent.com/67481432/102040479-30b9b900-3dcd-11eb-89d0-4f73eab00bfe.png)
And of course added them to the correct group (like in the new project) 🡹

![Screenshot (486)](https://user-images.githubusercontent.com/67481432/102041237-2c8e9b00-3dcf-11eb-9601-31c08fa8fe4d.png)                                              🡼
So lastly what i did, was assigned the new events to [aircraft_music.bank] 
At first, i thought this doesn't work because there aren't the 2 extra music banks  [aircraft_music_2.bank] & [aircraft_music_3.bank] 

but after testing it, it actually worked ingame
So my question is does this work properly (aswell in the future), or can this lead into problems because the 2 extra music banks aren't there?

**Comment by RadonSound** [comment]
Ok for some reason or maybe i didnt noticed it but the top_tier\tank_action event doesnt play in toptier is there a way to fix this? 
so only the menu_new event is working

**Comment by Uchuujin01** [comment]
Hello! It is does not matter wherever you place your music, it should work. I made a separate banks because it is better to update smaller ones, when we will be ready to add more music.

Regarding to top_tier\tank_action, we have a bug with it, it only plays in first battle. We'll fix it soon.

**Comment by RadonSound** [comment]
👍 Alright , Thank you for the info
