### ISSUE TITLE
356mm Naval gun sounds

### ISSUE THREAD

**Issue by YamashiroKai** [GaijinEntertainment/fmod_studio_warthunder_for_modders#57]
Hello,

One of my mod users reported that the 356mm naval gun sounds were missing. Were there new events added for these guns, and could I have the names of the events if so?

**Comment by Uchuujin01** [comment]
Hello! Yesterday fmod project was updated, you can check it for new sound events details.

**Comment by YamashiroKai** [comment]
Is there a way to check the new event names for the 356mm gun without downloading the entire new project?

**Comment by Uchuujin01** [comment]
You need to download the entire project in any case, soon or late, just to keep up. But, here is the new sound name: 356mm_45_mk8. Don't forget about _ai event too.

**Comment by YamashiroKai** [comment]
Alright thank you
