### ISSUE TITLE
Tail and Scatter tracks for AI are not included

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#58]
Hello!
After played a bit with the new updated project, i noticed that every AI (other player) tail sound wasn't played in Ground Forces.
First i thought the Distance module for the tail tracks where a bit quite. But even with set them to max, no tail sound was played ingame.
After just looking on the 4 tracks ( shot , scatter , bump , tail ) i saw that scatter and tail where not included and where not played even in FMOD with adjust the distance 
(Project used in videos was fresh downloaded and was not changed by me before)

https://user-images.githubusercontent.com/67481432/103453027-fd848e80-4cd5-11eb-9e4e-9f1dc96c4c8c.mp4

____________________________________________________________________________________________________________________________

https://user-images.githubusercontent.com/67481432/103453124-fc079600-4cd6-11eb-922d-450024cdf3ca.mp4

For better example i muted everything except the tail track. sorry if its a bit quite :(
should this be normal?

**Comment by Uchuujin01** [comment]
Hello! Scatter and tail components are not included for performance reasons. And, because sometimes they add unnecessary background noise, in high dencity battle. Of course, you can add it if you want.
