### ISSUE TITLE
Limitations on length of sound asset

### ISSUE THREAD

**Issue by diVineProportion** [GaijinEntertainment/fmod_studio_warthunder_for_modders#6]
So I tried changing so GUI like 'mission fail', 'mission complete' and 'mission done loading' sounds. If I recall correctly, they are all very short sounds, or at least the missions done loading is very short. I put 30 second clips and they didn't seem to play. On the other hand, I was able to get longer clips playing when I changed the ambient hangar sounds.

Is there something I'm missing?

**Comment by Uchuujin01** [comment]
Hello!
Of course, it is possible to meet some limitations on sound system form code. If you find this limitations, you can let us know, so we'll keep it in mind during developing process.

**Comment by diVineProportion** [comment]
So my 'mission finished loaded' (sorry i'll find the exact FMOD studio_path id when I get back home) sounds seem to work for random battles missions but not my custom single player made missions. Probably missing something in the mission.blk file I'd imagine
