### ISSUE TITLE
Question about return buses in mixer

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#60]
Hello,
sorry about this little issue,
while i was working on the mg loops something came to my mind, i setup jet engines in the new project. after testing it ingame, the interior engine sound had some strong reverberation effect. pretty much the same i've mention more than a month ago 

_,,I actually tried to start with the new updated project, but the way how events like the "100mm_d10t_interior" are now played, doesnt really matchup anymore with the sounds i use. It feels like it has a stronger "Surroundsound" effect''_

The effect that causes this are the new return buses with their reverb modules. i played a bit with reverb_cockpit but whatever i did, the reverberation was still ingame, so the last thing i tried was just delete reverb_cockpit from the left list
![Screenshot (572)](https://user-images.githubusercontent.com/67481432/104471769-8693a380-55bb-11eb-9d24-cc833db0c9cf.png)
after this, the strong reverberation effect was gone and sounds fine now 
and here is the question, can deleting those return buses (like on the picture) leading into any ingame conflict? 
I didnt find any other solution to make this effect a bit less noticable. i have 2 video's where this effect is hearable clearly.

**Comment by Uchuujin01** [comment]
This reverberstion effects controlled by corresponding snapshots, so, you can delete this return buses if you want to use another reverberation methods.

**Comment by RadonSound** [comment]
Ok so i can also delete the other (blue) return buses like on the picture above? sorry if i ask twice, just want to be double sure i dont destroy my project or lead into a ingame conflict.

**Comment by RadonSound** [comment]
And im also asking this becaues i dont have much knowledge in mixer, corresponding snapshots, buses, etc.  Im really afraid by doing some changes in mixer because the readme also says " _Also, do not change the structure of the mixer buses._ "

But there is something odd with these new return buses (picture) its hard to describe. even if they are empty they make the tank gun sounds some sort of "scratchy" and dry (like the cockpit from jets) . i would like to make a video but its hard to get this on tape. 

I tried my best to get a comparison in a video https://www.youtube.com/watch?v=7kJXMiO3jxo (might be a bit quiet sorry)
But i hope you can hear that the second clip (without the reverb_cockpit) sounds much smoother . And the same thing is with the tank guns in interior 

So yeah, this is why i would like to ask if i can delete (without fear) some or even all of those here:
![Screenshot (572)](https://user-images.githubusercontent.com/67481432/104854742-c5ea2900-5908-11eb-8d5d-fb7c3fb9cdb1.png)

like i said im do this reluctantly and im really afraid to make changes in mixer view 😟 hope you understand
