### ISSUE TITLE
Banned Sound Mods?

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#63]
Preliminary changelog says:
"A mechanism for limiting the use of custom sound modifications has been implemented. At the moment, when trying to start tank simulator or tank realistic battles by using custom sound mods you will see a dialog box with the message: “Sound mods are prohibited in the selected game mode. To turn off mods you need to restart the game. Restart the game?”

I hope this is some kind of mistake, i kinda don't get it.

**Comment by RadonSound** [comment]
hopefully this only affects the dev-server 
otherswhise what would be the point of soundmods then?

**Comment by Uchuujin01** [comment]
I'm afraid this is the new rule. Recently there was an accident during an official competition. One team got an significant advantage with self-made sound mod. They spotted enemies with their engine sounds, and won the match. That was showed on streams, so we got several complains about it. It is a serious issue, we forced to do something about it. Me made some research, how can we made a sound mods anti-cheat control. We failed with this, so, we decided to forbid sound mods in game mods without markers. I'm sorry, this is a very difficult situation.

**Comment by Uchuujin01** [comment]
At least, our game is a kind of competitive, and sound cheats obviously give an advantage.

**Comment by YamashiroKai** [comment]
Most people play Realistic Battles, including me, and if I and my supporters cannot use sound mods anymore then I'm quitting the game and discontinuing my mod.

Thank you for your response, but this situation is ridiculous.

**Comment by RadonSound** [comment]
this hits me now.. 
even tho i can fully understand the situation because i was kinda sure there where some people. making use of this for their own advantage . 
its really sad that there are some people take advantage of the **hard and honest** work of gaijin's sound staff just to ruin all of this and the work of other modders who doing legit soundmods 
I hope you understand, soundmodding was a real funny fulltime hobby for me after years doing nothing (im handicapped)

Wouldnt be that an option to create a small group of trusted modders who can provide legit soundmods?

**Comment by Uchuujin01** [comment]
I'm agree, this situation is overwhelming for us too. We truly appreciate your work, and your help is very important fo us. I'm very dissapointed that some people ruined our work (I mean your and our to support you). But, this mechanism is adjustable, and the conditions of sound mod restrictions can be changed.

"Wouldnt be that an option to create a small group of trusted modders who can provide legit soundmods?" - This is the possible solution. We need some time to figure out how we can approve sound mods.

**Comment by KOMMyHuCT** [comment]
Is there any hope that maybe UI, music, crew and other fundamentally harmless sound mods could be allowed by default? They're stored in separate files from cannon and engine sounds.

**Comment by Komrade-Yanouchka** [comment]
at least make the difference between tank engine and everything else, i don't want my jet sound removed or my ricochet and loading sound removed

**Comment by Ingmar-van-Busschbach** [comment]
> 
> 
> I'm afraid this is the new rule. Recently there was an accident during an official competition. One team got an significant advantage with self-made sound mod. They spotted enemies with their engine sounds, and won the match. That was showed on streams, so we got several complains about it. It is a serious issue, we forced to do something about it. So, we decided to forbid sound mods in game mods without markers. I'm sorry, this is a very difficult situation.

why not just ban sound mods in competitive matches, in that case?
As it stands, ULQ, user sights, and engine volume sliders already provide massive advantages to these "cheaters", on top of the existence of actual ESP cheats that get past Easy Anti Cheat, for these sound mods to contribute any significant ammount to the "cheating issue".

**Comment by Komrade-Yanouchka** [comment]
> > I'm afraid this is the new rule. Recently there was an accident during an official competition. One team got an significant advantage with self-made sound mod. They spotted enemies with their engine sounds, and won the match. That was showed on streams, so we got several complains about it. It is a serious issue, we forced to do something about it. So, we decided to forbid sound mods in game mods without markers. I'm sorry, this is a very difficult situation.
> 
> why not just ban sound mods in competitive matches, in that case?
> As it stands, ULQ, user sights, and engine volume sliders already provide massive advantages to these "cheaters", on top of the existence of actual ESP cheats that get past Easy Anti Cheat, for these sound mods to contribute any significant ammount to the "cheating issue".

exactly this is a perfect answer to be honest. nothing else should be done otherwise it will ruin the experiance

**Comment by Rafmaninoff** [comment]
Please only ban the sound mods in actual competitive matches that have monetary gains to be made, not on standard random battles that are played with a more light-hearted atmosphere.

**Comment by 787992** [comment]
>One team got an significant advantage with self-made sound mod. They spotted enemies with their engine sounds, and won the match.

Why not just restrict sound mods in tournaments only? Like scanning config file if there's working sound mod.

I spent thousands hours into sound moding and this is really confusing situation

**Comment by Uchuujin01** [comment]
We're about to discuss all your suggestions next week, thank you guys! We understand that your contribution in our game is priceless, and we don't want to loose you in our community. We'll do our best to minimise the impact on your work.

**Comment by Uchuujin01** [comment]
We can't leave the situation like before, for sure, but we'll try to figure out how can we forbid sound mods partly, according to your suggestions.

**Comment by AndyTheFighter** [comment]
There should be only acknowledged modders who have official access to the Fmod encryption registered in Gaijin site, before a mod is being released it goes through manual testing if it has obvious advantages like really audible beeping noises for enemy tank engines or stuff like that and then the mod MUST be posted on Gaijin site only, every other website openly offering WT mods are considered "illegal" and not true to competition and eSports regulations. Probably also implement a "premium" service for mods so your favourite official modders may get more financial love. I just cannot see my favourite Sound Modder just get dropped by mod banning who has dedicated his life to recording and thousands of thousands of hours to creating a masterpiece of audio experience for War Thunder. Just like a Mod Store, you can "buy" your favourite mod and get a license to use it. sure some now and then there will be crackers and hackers that get access to every possible Fmod Library and "illegally" create mods then, but thats EVERYWHERE there will be cheating EVERYWHERE and then consider using unofficial soundmods as reason to get banned when used in Competitive eSports gameplay. Easy is that. --- Open to suggestions

**Comment by AndyTheFighter** [comment]
> Preliminary changelog says:
> "A mechanism for limiting the use of custom sound modifications has been implemented. At the moment, when trying to start tank simulator or tank realistic battles by using custom sound mods you will see a dialog box with the message: “Sound mods are prohibited in the selected game mode. To turn off mods you need to restart the game. Restart the game?”
> 
> I hope this is some kind of mistake, i kinda don't get it.

I can see that this will be very much perfect as you can controll if the game draws mod data or vanilla data and its really easy to controll

**Comment by WhereMyBiasAt** [comment]
> There should be only acknowledged modders who have official access to the Fmod encryption registered in Gaijin site, before a mod is being released it goes through manual testing if it has obvious advantages like really audible beeping noises for enemy tank engines or stuff like that and then the mod MUST be posted on Gaijin site only, every other website openly offering WT mods are considered "illegal" and not true to competition and eSports regulations. Probably also implement a "premium" service for mods so your favourite official modders may get more financial love. I just cannot see my favourite Sound Modder just get dropped by mod banning who has dedicated his life to recording and thousands of thousands of hours to creating a masterpiece of audio experience for War Thunder. Just like a Mod Store, you can "buy" your favourite mod and get a license to use it. sure some now and then there will be crackers and hackers that get access to every possible Fmod Library and "illegally" create mods then, but thats EVERYWHERE there will be cheating EVERYWHERE and then consider using unofficial soundmods as reason to get banned when used in Competitive eSports gameplay. Easy is that. --- Open to suggestions

I personally don't think making sound mods unavailable for some people because they cost money. A lot of sound mod creators already have ways of making money from sound mods such as donations and early access test build memberships, however I do see how that could give Gaijin an incentive to change their opinion on it.

**Comment by The-Scout** [comment]
This decision was reversed
