### ISSUE TITLE
Перенаправление command inst

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#65]
Делаю мод для экипажа. Столкнулся с трудностями.
Если с помощью command instrument включить другой ивент, в нём работают только семплы. Multi или single instrument, не важно. Если в них .wav работает на 100%.
Но если в вызываемом ивенте присутствуют  programm instrument, он не отрабатывает.
Если в ивенте есть и то и другое, то слышно так же только семплы. В общем ивент вызывается корректно, но programm instrument'ы молчат.
Все пути, значения и форматы десять раз перепроверены.

**Comment by Uchuujin01** [comment]
Я еще не использовал command instruments, так что тут ничего не могу посоветовать, кроме как написать на форум или в официальную поддержку fmod.
