### ISSUE TITLE
Some sounds remained standard despite changes.

### ISSUE THREAD

**Issue by Soapface93** [GaijinEntertainment/fmod_studio_warthunder_for_modders#7]
I changed air-to-air missiles lock-on sound (alarm_con_scan) and rockets start sound (rocket_start) in their events but sounds have not changed in game and remained standard.

**Comment by Uchuujin01** [comment]
Hello! Are you sure you check exactly alarm_con_scan? Because there is another similar sound, alarm_spin_scan.

**Comment by Soapface93** [comment]
Yes. I changed alarm_spin_scan too and it works fine.

**Comment by diVineProportion** [comment]
> Yes. I changed alarm_spin_scan too and it works fine. But alram_con_scan still standard.

How are you modifying your sounds? Are you replacing the original .wav files with your own (overwriting the assets) or are you working in the Event Editor?

Each one of the events you listed has two layers each consisting of a scatterer instrument so there are 4 sounds for the two events.


You have to replace all instruments in 'scatterer instrument' (likewise with multi-instrument) or else you might miss your event happening. 

con_scan_capture-[001..008].wav
con_scan_track-[001..008].wav

spin_scan_capture-[001..008].wav
spin_scan_track-[001..008].wav

you replaced all 32 assets / instruments in the 4 layers of the 2 events?

**Comment by Soapface93** [comment]
Yes, just replacing sound files. At first, I replaced sound files in scatterer instruments, alarm_spin_scan changed, alarm_con_scan still plays standard sounds in game. alarm_spin_scan works fine even after changing layer from scatterer to single sound instrument. Second layer of both events are muted by standard so I don't touch them.
