### ISSUE TITLE
Where are the non-english language files at?

### ISSUE THREAD

**Issue by gungurbuz** [GaijinEntertainment/fmod_studio_warthunder_for_modders#70]
On one issue you said it was going to be added in a major update. It has been almost 6 months yet no non-english language files are in the project. Where are they?
![image](https://user-images.githubusercontent.com/50180396/112652861-ed0c2c00-8e5e-11eb-9d7f-920b88e481e5.png)

**Comment by Uchuujin01** [comment]
Hello! I haven't got time for it, sorry. But, you can made your dialogs sound mod, with your recorded files with same names.

**Comment by gungurbuz** [comment]
aight thanks for replying
