### ISSUE TITLE
Aircraft_guns.bank and Aircraft_gui.bank

### ISSUE THREAD

**Issue by p01fp01f** [GaijinEntertainment/fmod_studio_warthunder_for_modders#71]
Hello.
Thank you for the update.
I have one question.

The version of FMOD Studio is 2.1.6, the version of WarThunder (windows)is the latest as of 3/27 15:00(GMT), and the repository is after Ixwa Strike update.

I put Aircraft_guns.bank, masterbank.bank, and masterbank.strings.bank in the mod file and added useLoopsForGunSound:b=yes
in the config file.
When I start the game in this state, the machine gun sound is replaced correctly, but the bomb bursting sound, seeker startup sound, etc., which should be untouched, disappear.
As far as I can tell from FMODstudio, the bomb sounds are controlled by aircraft_gui.bank.
I thought so and output the aircraft_gui.bank file in the latest version, but when I put it in the mod file, those sounds are not coming out.
However, the click sound, shoot-down confirmation sound, bullet hit sound, etc., which are supposed to be controlled by the aircraft_gui, are playing normally.

Is there any procedure to fix the problem?

**Comment by YamashiroKai** [comment]
I also have useLoopsForGunSound:b=yes, but I don't hear any aircraft gun sounds at all. It's quiet even though I have a looping sound set for the guns I'm testing.

**Comment by Uchuujin01** [comment]
I'm not sure I get it right, but bomb explosion soundsplaced in hangar.bank. Also, now we got three bomb explosion sound events, for small, medium amd big explosion sounds.

**Comment by p01fp01f** [comment]
> I'm not sure I get it right, but bomb explosion sounds placed in hangar.bank. Also, now we got three bomb explosion sound events, for small, medium amd big explosion sounds.

I'm sorry. I was wrong about the sound of the bomb exploding. It's playing fine.

Let me clarify the problem.
In the environment I described above, the missile seeker sound does not play.
This is despite the fact that the only files in my mod folder are Aircraft_guns.bank, masterbank.bank, and masterbank.strings.bank.
As far as I can tell from FMODstudio, the seeker sound seems to be controlled by aircraft_gui.bank.

**Comment by Uchuujin01** [comment]
Yes, it should play, strange... Does messile seeker GUI sound plays without sound mod for you? Also, try to copy aircraft_gui.bank to mod folder.

**Comment by p01fp01f** [comment]
Yes, I tried that and it did not work.

I'm using aircraft_guns.bank and masterbank.strings from the previous version of the repository to enable useLoopsForGunSound:b=yes, but masterbank.strings.bank seems to cause inconsistency with the current version of the repository. It seems that masterbank.strings.bank is causing a conflict with the current version of the repository.

Is it possible that when I enable useLoopsForGunSound:b=yes, I also need to output from the current repository?
After reading the Patch notes and some trial and error, the sound is replaced correctly when I enable useLoopsForGunSound:b=yes and install the previous version of aircraft_guns.bank.
Is this behavior a bug?

**Comment by Uchuujin01** [comment]
I't quite hard to understand, sorry. But I definitely must say that you have to use all bakn files from the same project. useLoopsForGunSound:b=yes - I don't get it, what are you trying to do with that string, exactly?

**Comment by Damgam** [comment]
Do not copy Masterbank to your mod folder.
