### ISSUE TITLE
Request: Auto cannon ground impacts

### ISSUE THREAD

**Issue by YamashiroKai** [GaijinEntertainment/fmod_studio_warthunder_for_modders#73]
Could you add a new event (or change the existing ones) for shell explosions from auto-cannons that suit their higher rate of fire? If you watch videos of the A-10 Warthog, you can yeah hundreds of rounds exploding on the ground, which doesn't seem to be possible currently.

https://www.youtube.com/watch?v=D_GIeJAr2Lk

Right now the existing events will play about once a second, even if you set event instances to play more than 4 or more times.

**Comment by Uchuujin01** [comment]
I'm not sure what are you talking about, now there is no restrictions for explosion sound spawning time periods. Check stealing settings for your explosion sound event. Also there may be cooldown timer in event settings.

**Comment by YamashiroKai** [comment]
I've experimented with this many times, using the M163 and an aircraft with cannons and firing at the ground 300-500 meters away. No matter what setting I change, I only hear an impact every 0.5-1 second.

**Comment by Uchuujin01** [comment]
Try to experiment with stealing methods. And don't forget about stealing on buses. I've just tried with small explosions - they work with no time restrictions. But It definitely needs stealing method tweaking.

**Comment by YamashiroKai** [comment]
I think I figured it out, thank you.
