### ISSUE TITLE
Old loop method seem to be not working for planes

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#74]
Hello, as title says yeah, checked on my build & clean built, both shows same behaviour

Event starts like oneshot without sustain point (unlike other event with on_shot parameter where it stays idle on sustain point)
Well and on_shot parameter is not triggered at all. 
Not sure if i did something wrong, the system is copypaste from tank part.

In FMOD:

https://user-images.githubusercontent.com/63158562/113017890-9d906d80-9188-11eb-8c42-acaacaf58067.mp4

In game:

https://user-images.githubusercontent.com/63158562/113017915-a4b77b80-9188-11eb-873d-eab10a603897.mp4

Note, that sustain point is ignored as well as on_shot param.

**Comment by Uchuujin01** [comment]
Hello! I checked it multiple times, it definitely works. You don't need on_shot for it, btw.

**Comment by 787992** [comment]
>Hello! I checked it multiple times, it definitely works. You don't need on_shot for it, btw.

Ooh, makes sense then. Yes it works
