### ISSUE TITLE
Explosion events and few issues

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#75]
Greetings,

The new build is solid as rock, but after playtests and debugging found little issues here and there.

I'll start with old bug, didn't really bother to mention it earlier, uniti now. 
- The game ignores Load (seek speed) values from fmod, it's been fixed many patches ago, but now back since 2.3 patch. As always tested on modded and clear builds; if you setup load to instant it will be pretty slow in game as you stop your tank, even if you set it to super slow it will use same in-game values.
- Flares and Chaffs uses rocket flyby sounds, not sure if that's intended but definitely out of place.

As for debugged explosion i've found some interesting stuff, that also may reduce CPU usage, as some explosion events layered with other events having exact same sound.

I do believe, and you confirmed that _unit events should be used only for NPC vehicles, however it's widely used across many explosion events for ground and air parts.

- Earlier when tank exploded after ammo rack we could hear Destroy and *after* explosion_unit (when respawns)
Now Destroy and Explosion_unit layered together after explosion of ammo rack and when player respawns (2 events at same time for 2 different actions)
- All NPC and Playable vehicles also layered with events such as hit_small fron tank part and explosion_metal_small from air part. For low caliber actions this might be acceptable for player vehicles, but those events layered together for NPC vehices when you shooting them from plane.
- All APFSDS uses hit_small events, this might be subjective, but i think such fast shell rod won't sound as 37mm and other low-tier calibers
- Starting from 105mm (and all APFSDS shells) uses art_explosion_ events no matter of shell type, while calibers that are lower uses proper explosion_ground etc. Not sure if this one important, but just in case it makes inconsistency
- ATGM hit events are completely not used, explosion_unit and heavy_explosion_unit widely used for ATGM tank hits, Anti-Air rocket hit for planes and heavy_explosion_ground when ATGM hits object, only explosion_ground left when hits ground
Also noticed if ATGM hits friendly teammate misl_explosion_mid will be played, while i don't mind those events, but constintency makes it really messy and confusing. 
I'd revert back ATGM hits for player side and Ai side and misl_explosion_mid for all hits objects/ground

And yeah one last thingy

This is extremely old case and not an issue, but Rh202 (20mm gun) that installed on all Leopards uses 20mm Oerlikon sounds, thing is Oerlikon is around 450rpm, while rh202 is around 800.

**Comment by Uchuujin01** [comment]
Hello! Sorry for late answer, I've been on vacation.

Thanks for the report, it's very valuable since recently we worked on VFX and SFX for explosions. There are could be some issues.

Regarding the last question, Oerlikon, now all weapon sound doesn't have fixed rpm, it depends on speciefic weapon model. So, Oerlikon event may sound with any rpm.

**Comment by 787992** [comment]
>Hello! Sorry for late answer, I've been on vacation.

Thanks for the report, it's very valuable since recently we worked on VFX and SFX for explosions. There are could be some issues.

Regarding the last question, Oerlikon, now all weapon sound doesn't have fixed rpm, it depends on speciefic weapon model. So, Oerlikon event may sound with any rpm.

Hey! Welcome back! 

Yeah, i figured out regarding Oerlikon, pretty impressive.

Almost forgot to mention, HE, HEAT, HEATFS (anything explosive(?)) uses wreck_explosion for Ai tank hits, i think it's layered with normal hits, but just in case. Could be more stuff in this regard, didn't debugged yet.
