### ISSUE TITLE
Missing File?

### ISSUE THREAD

**Issue by Xenoblivion53** [GaijinEntertainment/fmod_studio_warthunder_for_modders#77]
![Untitled](https://user-images.githubusercontent.com/82923762/115494053-b3d69a00-a219-11eb-8723-e0be6e4dc717.png)

https://user-images.githubusercontent.com/82923762/115494310-3fe8c180-a21a-11eb-9885-b694bf049d42.mp4

I am currently having issues while trying to change the "enemy_destr_by_aircraft" | "enemy_destroyed" | "enemy_destr_by_ship" | audio files to a custom WAV file. I attached a image to this with what it says is missing & the custom WAV (I converted it to MP4 so It could be attached), file I am trying to use as a replacement. I'm unsure what to do in anyway, could somebody help me get past this?

Things I have tried:

1. Ignoring the message (Not even the stock or custom sound plays when killing an enemy with any vehicle).
2. Using the right version (2.6.1). No luck.
3. Using the wrong version. Still no luck.

Thanks!

**Comment by RadonSound** [comment]
Hello!

Sorry for the late answer 

Please make sure the event in the error message is **empty** like in the picture
![Screenshot (91)](https://user-images.githubusercontent.com/67481432/115591665-a3362a80-a2d2-11eb-995e-305316ea0342.png)
they sometimes contain missing music instruments. If a new error message shows up, search the event and delete the instrument so the event is empty

**Comment by Xenoblivion53** [comment]
Thanks for the reply! However even after making the event empty, it is still providing me with the same message and problem. It keeps on saying there is a missing file for the US Guadalcanal 4.wav thing. I attached a small video with me having already cleared the event and trying to build my respective bank (Hangar is what contains the enemy destroyed files).

https://user-images.githubusercontent.com/82923762/115597749-76602400-a28e-11eb-8afa-2dfec142e401.mp4

P.S. I'm really not that smart when it comes to messing with files. So hopefully I did what you said correctly.

**Comment by RadonSound** [comment]
The enemy_destr.. event has nothing really to do with the error about the missing guadalcanal . let me check the newest version quick

**Comment by RadonSound** [comment]
got the fix i think. let me make a little video real quik

**Comment by Xenoblivion53** [comment]
Alright

**Comment by RadonSound** [comment]
https://user-images.githubusercontent.com/67481432/115602090-d41c5c80-a2de-11eb-8f63-cfc91824fa36.mp4

Hope this should help

**Comment by Xenoblivion53** [comment]
Eurka! It works!

Thanks so much!

**Comment by Xenoblivion53** [comment]
I'll close the discussion now since it works for me!
