### ISSUE TITLE
Aircraft weapons weapons outside can be heard inside & few questions

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#80]
As title says it can be heard inside too with loop swith ON. Happens with any cannon/MG.

Other thing that bothering me, any chance to glue up sound emitters related to player tank? (engine, reload, cannon)
Right now all sounds related to player have slight delay when following tank, it's very noticeable on fast small tanks - engine can be heard almost behind.
I also noted in files, reload sounds for exterior and interior, i'd really like to use it, but sound emitter is just moving away once my tank moves forward.
Same for cannon sounds, huge field to improve it but gets stuck with same problem.

I know this is probably due to optimization, but still any chance? (not mentioning auto-cannons or MGs that would be big pain to update every sound's position)

**Comment by Uchuujin01** [comment]
> As title says it can be heard inside too with loop swith ON. Happens with any cannon/MG.

Hello! Yes, it's partly hearable, with or without loops switched ON. You can tweak it by yourself, take a look at "cockpit" snapshot.



> Other thing that bothering me, any chance to glue up sound emitters related to player tank? (engine, reload, cannon)
> Right now all sounds related to player have slight delay when following tank, it's very noticeable on fast small tanks - engine can be heard almost behind.
> I also noted in files, reload sounds for exterior and interior, i'd really like to use it, but sound emitter is just moving away once my tank moves forward.
> Same for cannon sounds, huge field to improve it but gets stuck with same problem.
> 
> I know this is probably due to optimization, but still any chance? (not mentioning auto-cannons or MGs that would be big pain to update every sound's position)

Yes, some tank related sounds now work oneshot-like, due to optimisation. But, sounds fair enough, some of them should be reworked to tracked mode, I've put it on my todo list, thank you!

**Comment by 787992** [comment]
> Hello! Yes, it's partly hearable, with or without loops switched ON. You can tweak it by yourself, take a look at "cockpit" snapshot.

Got it, thanks!

>Yes, some tank related sounds now work oneshot-like, due to optimisation. But, sounds fair enough, some of them should be reworked to tracked mode, I've put it on my todo list, thank you!

Ooh, looking forward for that! Hope that won't cost too much in terms of performance

Unrelated, any ETA on project files?

**Comment by Uchuujin01** [comment]
> Unrelated, any ETA on project files?

Red Sky fmod project update will be released in the beginning of the next week, I'll try my best, at least.
