### ISSUE TITLE
Need help for new reverb/surround effects

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#81]
Hello,

I have a problem that is probably hard to describe, so uhm, i had to reset my windows the other day and i set the windows installer in that way so it keeps my data on my second harddrive where everything important, including my older project is, safe from being deleted. This actually worked couple years ago so i expected nothing bad. but then after everything was done i checked my harddrive to see if everthing is there and my pc was like 
![thumb_←-→-clǜ-secure-l-https-ico-savedroid-com-aannnd-ts-gone-mining-48756983](https://user-images.githubusercontent.com/67481432/123573089-96035380-d7cd-11eb-9d14-d9307ebe5431.png)

..... well .. yeah.. the problem here is, i wanted to use my older project as some sort of template for the new project (like copy my goog settings and properties) and now it's all gone. everything i set up and tested all the week's is gone.. 
So the only thing i have now is my memory from like 4 months ago.

So today i startet with the Red Skies project. After i setup the 100mm d10t cannon (AI,inside) , i noticed that the sounds have a.. well it's hard to describe, they sound like they are playing in front of me, instead of stereo what i used to hear. I already disabled the Return buses in mixer like on my older project (which fixed it there) but it still sounds different. Is there maybe a new effect that i overlooked? im still not really familiar with VCA's and Snapshots

I'm sorry if i may sound unclear.. i'm still really upset that all my important stuff got deleted..

**Comment by Uchuujin01** [comment]
Hello! I'm sorry for your important data, it is hard to restore, for sure.

You right, now cannons sound a bit different, in terms of sound distribution. They were in stereo, but it sounds a bit weird in 5.1, only through frontal speakers. Now they distributed through all 6 channels, so in stereo setup it sounds quite different. Because 5.1 -> stereo downmix happening. You may change it as you wish, take a look at sounds/outside/guns/cannon/ground bus, "In" section, change it to "stereo"

**Comment by RadonSound** [comment]
Ok so i changed it as i think you said. But for some reason, it still sounds the same after the change 
![Screenshot (37)](https://user-images.githubusercontent.com/67481432/123915890-41a0d500-d981-11eb-9ad7-04319306710c.png)
I changed the "In" section to stereo (red) for the interior gun sounds but ingame it still plays like front speakers instead of older stereo as i remember. Do i have to change anything else maybe, like [Grp] cannons , [Grp] guns ,...? Also, what does the Out section do (blue)?

**Comment by Uchuujin01** [comment]
Try to play with this bus in and out sections, you definitely will find your "stereo" mode. Remember that there are many buses over the lower one.

**Comment by RadonSound** [comment]
Got it. setting [Grp] guns , [Grp] cannons and [Grp] ground , [In] and [Out] to Automatic, makes it playing it like before (like i wanted) . I tried to set all of the groups only to stereo but then the ingame shot sound was kinda flat (no bass) and was very quiet. But i want to play a bit around with this (to see what stereo does on a specific group like guns and the rest is automatic) , yet thank you so much for this information. alone, i would be never able to find such deep settings.
