### ISSUE TITLE
Old Berezin UB loop sound file 

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#84]
Hello!

I have troubles to find the old Berezin UB gun sound that was used back in 2017 and earlier 
Like this here https://youtu.be/rg3GAfBY_8A?t=99

Does it have a different name? 

Sorry for the odd question, but it is one of the few last gun sounds i need for aircrafts

**Comment by Uchuujin01** [comment]
I haven't found this file too, for now.

**Comment by RadonSound** [comment]
I found it, it was ho103_loop_left (sounds the same as in the video) 
were you on vacation? i was getting worried 😅 hope it was all well

**Comment by Uchuujin01** [comment]
@RadonSound yes, I've been on vacation, sorry for delayed answer ) Glad you found it.
