### ISSUE TITLE
Personnal sample for Leclerc

### ISSUE THREAD

**Issue by MathMilitary** [GaijinEntertainment/fmod_studio_warthunder_for_modders#87]
Hi,
I'm french and I recorded my personnal sample for turbine idle and max. It's possible to use for ingame.

Is very simple application for engine and IA, just 2 sample on load event. nothing else
I can easily give them to you with permission to use it ;-)
![Capture d’écran 2021-08-28 100242](https://user-images.githubusercontent.com/63722574/131211108-b9ae005b-0942-40f2-89dd-feeed059395e.png)

For exemple https://youtu.be/AKAhkYexEfc

**Comment by Uchuujin01** [comment]
Hello! Do you want me to take your samples and add it to official gae sounds? If so, I'm afraid no, we can't use materials that haven't been officially licensed. BUT, I can take your advice and make a turbine sounds for "load" page.

**Comment by MathMilitary** [comment]
Hi, ok I understand. For better realism, just reduce diesel and up turbine sound on high rpm only. Thank for your work
