### ISSUE TITLE
When will the update the audio of the project?

### ISSUE THREAD

**Issue by CCCPDriver** [GaijinEntertainment/fmod_studio_warthunder_for_modders#9]
Hello everyone.
After the release of update 1.97, some sounds stopped working when creating a sound mod. This question is how long to wait for an updated sound project?

**Comment by Uchuujin01** [comment]
Hello! Yes, in update 1.97 weapon sound spawn mechanics reworked, one shot weapon events no longer works. Sound project update will be released soon, in this month I think. We must made some fixes first, sorry for the delay.

**Comment by Uchuujin01** [comment]
You can try to made a proper sound event for one shot weapon by yourself. Just put a sustain point on a Timeline inlay, and add to event a parameter called on_shot (0 .. 1 values range). On sound containers in Trigger behavior section add a parameter trigger for on_shot parametrer with value "1".

**Comment by Uchuujin01** [comment]
For loop weapon sound events almost the same changes - just add on_shot parameter to sound event (0 .. 1 values range), and add a Trigger condition to all sound containers (on_shot parametrer with value "1"). When on_shot reaches "1" value, container triggers - that's how it works now.

**Comment by CCCPDriver** [comment]
> For loop weapon sound events almost the same changes - just add on_shot parameter to sound event (0 .. 1 values range), and add a Trigger condition to all sound containers (on_shot parametrer with value "1"). When on_shot reaches "1" value, container triggers - that's how it works now.

Thanks. I'm not a Pro at working with fmod, but I'll try to figure it out. Some explosion sounds also don't work.

**Comment by CCCPDriver** [comment]
![image](https://user-images.githubusercontent.com/62462287/77224285-31daf400-6b75-11ea-9c23-753d1385a52f.png)
I created the on_shot parameter on the example of the M2 machine gun . But what to do next, I don 't quite understand.

**Comment by CCCPDriver** [comment]
![image](https://user-images.githubusercontent.com/62462287/77224420-8df24800-6b76-11ea-8991-2a89cd53c713.png)
I think we should do this for each machine gun and tank gun)

**Comment by Uchuujin01** [comment]
> ![image](https://user-images.githubusercontent.com/62462287/77224285-31daf400-6b75-11ea-9c23-753d1385a52f.png)
> I created the on_shot parameter on the example of the M2 machine gun . But what to do next, I don 't quite understand.

just click on sound containers below the sustain point, on the left side of the container you will see Trigger conditions section. Add a condition for on_shot parameter (for loops "1", for the rest containers with shot tails - "0").
![2020-03-21 13_17_42-Window](https://user-images.githubusercontent.com/26138230/77224443-bed27d00-6b76-11ea-9e10-be0dd8eb53ad.png)

**Comment by Uchuujin01** [comment]
> ![image](https://user-images.githubusercontent.com/62462287/77224420-8df24800-6b76-11ea-8991-2a89cd53c713.png)
> I think we should do this for each machine gun and tank gun)

Yes, exactly! )

**Comment by CCCPDriver** [comment]
Thank you)

**Comment by Uchuujin01** [comment]
> Thank you)

) I upload new fmod project version soon, it just need some fixes and preparations.
