### ISSUE TITLE
fmod 2.0.6 ?

### ISSUE THREAD

**Issue by MathMilitary** [GaijinEntertainment/fmod_studio_warthunder_for_modders#92]
Hi,
does direct hit still use fmod 2.0.6

**Comment by Uchuujin01** [comment]
Hello. Did you read Readme.md? Please read, there is an actual fmod version.

**Comment by MathMilitary** [comment]
I was wrong, I meant 2.1.6 Fmod.
I ask the question because currently my mod created on 2.1.6 continues to work

**Comment by Uchuujin01** [comment]
Ok, I think Readme.md gave you the answer )
