### ISSUE TITLE
Tracklink sound

### ISSUE THREAD

**Issue by MathMilitary** [GaijinEntertainment/fmod_studio_warthunder_for_modders#93]
hello, there is still a problem with the sound of the tracks.  the tracks go too fast while the speed of the tank is very low.  is it possible to make this point more realistic.

**Comment by Uchuujin01** [comment]
Hello. I see no problem with tracks... If you are making your sound mod, you free to adjust rate of tracks sound whatever you want.

**Comment by MathMilitary** [comment]
I have to adjusted in the "speed" tab ?

**Comment by Uchuujin01** [comment]
Yes, "speed" tab.

**Comment by MathMilitary** [comment]
ok, thanks.
