### ISSUE TITLE
Сторонние банки и отдельные ивенты.

### ISSUE THREAD

**Issue by OXEPU3M** [GaijinEntertainment/fmod_studio_warthunder_for_modders#94]
Верно ли я понимаю, что нет никакой возможности в современной игре изменить отдельный звуковой ивент, не меняя его банк целиком?
Они, что называется, hardcoded?

Так-то игра в состоянии запустить любой ивент из любого банка, даже которых не было в оригинальной sound, но ссылка на него должна всё же лежать в уже существующих банках.
Это значительно ускоряет создание модов, но всё же необходимо каждый раз ожидать обновления.

Было бы весьма полезно иметь возможность подключать новые банки, ивенты в которых при совпадении имён заменяли бы стандартные, либо с помощью конфига (или иначе) дать игре понять, что вместо event X использовать event Y.

Это решило бы 99% моих проблем с наложением и перекрестным воспроизведением, и, вероятно, 90% проблем остальных мододелов, вынужденных ожидать обновления репозитория.
Возможно, и вам это бы помогло обновлять его значительно реже, при смене параметров или решений а-ля loop. А при незначительных изменениях лишь указывать в шапке, какие ивенты добавлены/убраны и т.п.

Или же придётся совершенно весь код перебивать?

**Comment by Uchuujin01** [comment]
> Верно ли я понимаю, что нет никакой возможности в современной игре изменить отдельный звуковой ивент, не меняя его банк целиком?
> Они, что называется, hardcoded?

Я не понимаю, что в данном случае означает hardcoded, но да, чтобы изменения звукового ивента вступили в силу, требуется пересобрать банк, которому принадлежит ивент.



> Так-то игра в состоянии запустить любой ивент из любого банка, даже которых не было в оригинальной sound, но ссылка на него должна всё же лежать в уже существующих банках.
> Это значительно ускоряет создание модов, но всё же необходимо каждый раз ожидать обновления.

Нет, игра не в состоянии запустить звуковой ивент из банка, которого нет в списке банков игры. Но, вам нет нужды ждать обновления, чтобы работать с уже существующими в игре звуковыми ивентами. Состав банков меняется очень редко, за последние два года это было всего раз.



> Было бы весьма полезно иметь возможность подключать новые банки, ивенты в которых при совпадении имён заменяли бы стандартные, либо с помощью конфига (или иначе) дать игре понять, что вместо event X использовать event Y.

Подобное решение неприемлемо. Это существенно усложнит и без того сложную систему контроля ивентов, повысит нестабильность клиента, и даст возможность бесконтрольно делать звуковые читы.



> Это решило бы 99% моих проблем с наложением и перекрестным воспроизведением, и, вероятно, 90% проблем остальных мододелов, вынужденных ожидать обновления репозитория.

Еще раз уточню - ожидать обновления нужно только со сменой версии fmod, и при добавлении новых звуковых ивентов (и то, только, возможно, для того чтоб названия и пути посмотреть).

**Comment by OXEPU3M** [comment]
> что в данном случае означает hardcoded

Я имею в виду, что игра загружает строгий список банков независимо от FMOD. Но проехали, я понял ответ.

> ожидать обновления нужно только со сменой версии fmod, и при добавлении новых звуковых ивентов (и то, только, 

возможно, для того чтоб названия и пути посмотреть).
Вот в том-то и дело, что новые ивенты со старыми модами совершенно беззвучны. Было бы отлично иметь возможность как-то загружать их, но незатронутые (новые) ивенты работали стандартно.
Но раз уж это невозможно/неприемлемо, пусть.

> Нет, игра не в состоянии запустить звуковой ивент из банка, которого нет в списке банков игры.

Игра не может, FMOD может. Очень печально, конечно.
Спасибо за оперативный ответ.

**Comment by Uchuujin01** [comment]
> Вот в том-то и дело, что новые ивенты со старыми модами совершенно беззвучны. Было бы отлично иметь возможность как-то загружать их, но незатронутые (новые) ивенты работали стандартно.

Боюсь, нет возможности загрузить две версии банков - банк мода и банк стандартный, чтобы подхватывать недостающие в моде ивенты. У нас в распоряжении не так много памяти, к сожалению. Мы подумаем над этим, над модификацией системы модификации. Пришло тут сейчас на ум, что можно попробовать сделать отдельный банк с зарезервированным именем, например, mod.bank. И если он не пустой, то сначала ивент будет искаться в нем, а затем в базовых банках. Я конечно ничего не могу обещать, но, попробуем подумать в этом направлении.

**Comment by OXEPU3M** [comment]
Огромное спасибо.
